// Labbook: the experiment planner and the notebook.
(function(){
  var toExps = function(w){ w.selectNode('exps', '', ''); };
  var toJournal = function(w){ w.selectNode('journal', '', ''); };
  var NOEXP = 'This appears once you have an experiment open. Create one first, or open one from Experiments.';
  function anyExp(w){ return !!(w.LB && w.LB.data && w.LB.data.experiments && Object.keys(w.LB.data.experiments).length); }
  assistRegister('labbook', {
    name: 'Labbook',
    blurb: 'Labbook is where experiments are planned, run and written up. You create an experiment; it becomes dated steps with live calculators and a plate map; each day shows what is due, and ticking a step writes the Journal for you. Potencies from Echo Dose Response or Lumina land on the experiment, and the Report turns it all into a document.',
    first: ['start', 'new-exp', 'today', 'report'],
    avoid: ['#lb-timers'],
    screen: function(w){
      var n = (w.SEL && w.SEL.node) || {}, k = n.kind || 'home';
      if (k === 'expsec') return w.SEL.page ? 'exp' : 'folder';
      return k === 'nb' ? 'journal' : k;
    },
    diag: function(w){
      var d = [];
      if (w.LB && w.LB.data && !anyExp(w)) d.push({ msg: 'You have no experiments yet. **Create the first one.**', t: 'new-exp' });
      return d;
    },
    topics: [
      { id: 'start', t: 'How Labbook fits together', group: 'Getting started', on: ['home'],
        q: ['how does it work', 'overview', 'get started', 'how to use', 'tutorial', 'where do i begin', 'planner', 'journal', 'como funciona', 'como se usa', 'empezar', 'por donde empiezo', 'primeros pasos'],
        a: 'The unit of Labbook is the **experiment**. You design one; it expands into dated steps; each day shows the steps due that day. Four areas:',
        steps: ['**Planner:** Home, Today, Week and Experiments — what to do and how it is going.', '**Journal:** one page per day, written from what you ticked, plus free Notes.', '**Visualize:** charts of your experiments and potencies.', '**Designer:** build an experiment out of modules and save it to reuse.'],
        tip: 'Take the tour any time from the gear → Help.',
        go: [{ l: 'Take the tour', fn: 'startTour' }], see: ['new-exp', 'today', 'journal'] },
      { id: 'new-exp', t: 'Create an experiment', group: 'Getting started', on: ['home', 'exps', 'folder'],
        q: ['new experiment', 'create experiment', 'add experiment', 'start an experiment', 'plan an experiment', 'crear experimento', 'nuevo experimento', 'anadir experimento', 'empezar un experimento', 'plan'],
        steps: ['Press `⌘E`, or **+ New experiment** on Experiments.', 'Choose the **preset** and the **start date**, and answer the setup questions (plate format, cell line, counts…).', 'Check the dated steps in the preview.', 'Press **Create**.'],
        tip: '**More details** holds the code, target tag, title and aim. The code is filled in for you.',
        prep: toExps, show: [{ sel: '.xv-new', say: 'Start here, or press ⌘E anywhere.' }],
        go: [{ l: 'New experiment', fn: 'newExperimentFromAnywhere' }], see: ['presets', 'weekend', 'designer'] },
      { id: 'presets', t: 'Which preset do I choose?', group: 'Getting started', on: ['exps', 'folder'],
        q: ['preset', 'type', 'experiment type', 'western blot', 'hibit', 'ctg', 'nanobret', 'cell viability', 'kinetic degradation', 'reverse transfection', 'direct to biology', 'proteomics', 'cloning', 'custom', 'tipos de experimento', 'que tipo'],
        a: 'A preset is a starting plan for a kind of experiment: its steps, calculators and questions.',
        steps: ['**Western blot**, **HiBiT degradation**, **Cell viability**, **NanoBRET**, **Kinetic degradation**, **Reverse transfection**, **Direct-to-biology**, **Proteomics**, **Cloning / plasmid**.', '**Custom experiment** starts with one empty step.', 'The lab’s own curated versions sit beside them, and anything you save from the Designer appears as “yours”.'],
        see: ['blank', 'designer'] },
      { id: 'blank', t: 'Just a page: a blank experiment', group: 'Getting started', on: ['exps', 'home'],
        q: ['blank experiment', 'empty experiment', 'free page', 'no preset', 'notes only', 'experimento en blanco', 'pagina en blanco', 'sin preset', 'onenote'],
        a: 'A **Blank experiment** is a title, a date and somewhere to write. It is still a real experiment: you can add steps, a calculator or a plate map to it later.' },
      { id: 'weekend', t: 'A step falls on a weekend', group: 'Getting started', on: ['exps', 'home'],
        q: ['weekend', 'saturday', 'sunday', 'skip weekends', 'start on monday', 'fin de semana', 'sabado', 'domingo', 'saltar fin de semana'],
        a: 'The New-experiment preview names the weekday of every step and counts the ones on a weekend. Choose **Skip weekends** to move them to Monday (later steps keep their gaps) or **Start on Monday**. Nothing moves unless you choose it.' },
      { id: 'designer', t: 'Build an experiment from modules (Designer)', group: 'Getting started', on: ['design', 'exps', 'home'],
        q: ['designer', 'design an experiment', 'modules', 'custom design', 'save as a design', 'reuse an experiment', 'step by step', 'disenador', 'disenar experimento', 'modulos', 'guardar como diseno', 'reutilizar', 'wizard'],
        a: 'The Designer builds an experiment out of modules instead of a fixed preset.',
        steps: ['Choose the **type** and answer the **parameters**.', 'Pick and order the **modules** (seeding, compound addition, a read…).', 'Configure each one; each module knows what the steps above already put in the well, and how many days after the previous step it falls.', 'Review the whole plan, then create it — or save it as a design to reuse.'],
        tip: 'Move a module and the dates, and the volume each step starts from, recalculate.',
        go: [{ l: 'Open the Designer', fn: 'selectNode', args: ['design', '', ''] }] },
      { id: 'protocol-steps', t: 'Add an Archive protocol to an experiment', group: 'Getting started',
        q: ['protocol', 'archive protocol', 'gibson', 'transformation', 'miniprep', 'add protocol', 'protocolo', 'anadir protocolo', 'pcr', 'cloning protocol'],
        a: 'In the New-experiment window the **protocols** list adds Archive protocols to the plan. Each protocol stage becomes its own dated step, with the protocol’s live calculators, so two protocols can interleave on the calendar.',
        tip: 'A step remembers the protocol version it came from, so an old entry reads the same years later. If the protocol is corrected, you are offered the update; it is never forced.' },
      { id: 'today', t: 'What is due today', group: 'Every day', on: ['home', 'journal'],
        q: ['today', 'what do i do today', 'daily', 'due today', 'steps due', 'que toca hoy', 'hoy', 'pendientes', 'tareas de hoy', 'agenda'],
        a: 'Today lists the steps due, grouped by project and experiment, then anything **carried over**, your tasks, cultures needing attention, and the running experiments.',
        tip: 'A due step is one line; click it to open it in full. `⌘⇧J` jumps to Today from anywhere.',
        prep: toJournal, show: [{ sel: '.day-nav', say: 'The day you are looking at. The arrows move a day.', miss: 'Open **Today** from the left column first.' }], see: ['tick', 'carryover'] },
      { id: 'tick', t: 'Mark a step done', group: 'Every day', on: ['home', 'journal', 'exp'],
        q: ['tick', 'done', 'complete a step', 'check off', 'mark done', 'finish step', 'marcar', 'hecho', 'completar paso', 'terminar paso', 'tachar', 'checkbox'],
        a: 'Tick the box on a step, on Home, Today, the Journal day or the experiment: it is one record, so it is ticked everywhere. `⌘⏎` ticks the step under the cursor.',
        steps: ['Ticking stamps the time, which the Journal writes into that day.', 'If you tick it on a later day than planned, you are asked whether to **move the rest** by the same number of days, or that you **did it on the planned day** and are only recording it now, or **keep the plan**.', 'Ticking the last step asks how the experiment went; you can skip that.'],
        tip: 'Ticking a step also ticks the sub-steps inside it, and reopening it undoes only those.',
        prep: toJournal, show: [{ sel: '.blk-done', say: 'Tick here.', miss: 'No step is due on this day. Open a day with steps, or an experiment.' }] },
      { id: 'carryover', t: 'Steps carried over', group: 'Every day', on: ['journal', 'home'],
        q: ['carried over', 'carry over', 'overdue', 'late', 'missed steps', 'arrastrados', 'atrasados', 'pendientes de ayer', 'not done yet', 'behind'],
        a: 'Unfinished steps from the last three weeks are listed under the day as **carried over**. It is a list to decide on, not to work from:',
        steps: ['**Tick** it if you did it.', '**Move to this day** to do it now: it then appears with its full body above.', '**Snooze** it, or **Dismiss** it.'],
        warn: 'Past three weeks a step drops out of the list, but the experiment itself is marked as having overdue steps.' },
      { id: 'reschedule', t: 'Move a step or the whole plan', group: 'Every day', on: ['exp', 'journal', 'week'],
        q: ['move step', 'reschedule', 'change date', 'snooze', 'postpone', 'delay', 'push back', 'mover paso', 'cambiar fecha', 'aplazar', 'posponer', 'retrasar', 'move plan'],
        steps: ['Open a step’s **⋯** menu: **Snooze 1 day / 1 week** moves it and every later step of that experiment.', '**Change the date…** moves just that step (or, from a day header, that whole day).', 'Drag a step onto another day to re-date it.', '**Reschedule the steps after this…** moves everything after it by the same number of days.'],
        tip: 'Moving a step to the day before the read changes the incubation time in the text and the Methods automatically.',
        see: ['waits'] },
      { id: 'waits', t: 'Waits and timers', group: 'Every day', on: ['exp', 'journal'],
        q: ['wait', 'timer', 'incubation', 'countdown', 'alarm', 'overnight', 'how long', 'espera', 'temporizador', 'incubacion', 'cronometro', 'alarma', 'toda la noche', 'notification'],
        a: 'A step can carry a **wait** before the next one can start. Type it in the step’s ⋯ menu (**Add a wait**, later **Change the wait**) as “45 min”, “3 h”, “1 h 30” or “overnight”.',
        steps: ['`⌘⇧S` starts the wait after the step under the cursor, or press the play button on its chip.', 'Timers stack in the corner, name the step they came from, beep and keep the screen awake.', 'If the next step is dated **tomorrow**, an overnight incubation of 16 h is assumed for you.'],
        warn: 'Timers work while the browser is open. This is not an alarm clock: a closed browser cannot ring.',
        tip: 'The first timer asks for permission to notify you; that is the only time.' },
      { id: 'step-log', t: 'Write what actually happened', group: 'Every day', on: ['exp', 'journal'],
        q: ['log', 'what happened', 'note on a step', 'step note', 'annotate', 'deviation', 'comment', 'anotar', 'nota en un paso', 'que paso', 'comentario', 'notas del paso', 'observations'],
        a: 'Three places, each for a different scale:',
        steps: ['A **step** has notes, and a one-line **what happened** once ticked; that line goes straight into that day’s Journal page.', '**Observations** on the experiment are for the run as a whole.', 'The **Journal** day note is for everything else.'],
        tip: 'Notes on a step never change the protocol underneath, so “what the protocol says” and “what I did” stay separate.' },
      { id: 'photo', t: 'Photograph a gel or a plate', group: 'Every day', on: ['exp'],
        q: ['photo', 'picture', 'camera', 'take a photo', 'attach image', 'gel image', 'foto', 'imagen', 'camara', 'adjuntar imagen', 'subir foto', 'crop', 'recortar'],
        a: 'Use the camera on a step to add a picture straight to the experiment’s **Files**, captioned with the step’s name. You can crop and rotate it first. On a phone, holding **+** takes a photo into today’s note.',
        show: [{ sel: '.bench-photo', say: 'The camera is on every step.', miss: NOEXP }] },
      { id: 'calculators', t: 'Calculators inside a step', group: 'Experiments', on: ['exp'],
        q: ['calculator', 'recipe', 'volumes', 'master mix', 'how much', 'dilution', 'numbers in the step', 'inputs', 'overage', 'calculadora', 'receta', 'volumenes', 'cuanto', 'mezcla', 'numeros', 'sobrante', 'yours relink'],
        a: 'The numbers in a step come from the calculator under it, so the text and the recipe table never disagree. **Inputs** is folded under the recipe.',
        steps: ['Change an input and the recipe and the sentence update together.', 'A field the setup or the steps above fill in is tagged **from the setup** / **from the steps above**; one you typed is tagged **yours · re-link**.', 'Totals include the extra for dead volume, and say so.'],
        warn: 'A number you have recorded is never rewritten by the app: stocks change, and the number in an experiment is what that run used.',
        show: [{ sel: '.blk-calc', say: 'The calculator sits under its step.', miss: NOEXP }] },
      { id: 'plate-map', t: 'Draw a plate map', group: 'Experiments', on: ['exp'],
        q: ['plate map', 'plate layout', 'draw plate', 'wells', 'which compound where', 'plate editor', 'conditions', 'mapa de placa', 'placa', 'pocillos', 'que compuesto donde', 'layout', '96', '384', 'dose series', 'controls'],
        a: 'A plate map records what was in each well, so a run can be repeated or read back later. Press **Edit** on a map (or `⌘⇧P` in a step) to open the editor.',
        steps: ['**Drag a rectangle**, then **click the condition**: it applies at once and the selection stays.', 'Shift extends the box, `⌘` / `Ctrl`-click adds; `Delete` clears wells.', '`⌘C` `⌘X` `⌘V` copy a block of wells; `⌘Z` undoes.', 'For a dilution series, select the wells and use the series filler; a block gets the same points in each replicate.', '**Start from a layout…** offers ready-made maps.'],
        tip: 'Every map shows a colour grid and a written summary (“B1–D10 · SU-DHL-5 · JQ1 1 µM → 3.81 pM · 3 replicates”); the summary is what the search and the Methods read.',
        show: [{ sel: '.blk-plate', say: 'The plate map. **Edit** opens the editor.', miss: 'This experiment has no plate map yet. Add one from a step, or with `⌘⇧P`.' }], see: ['echo-picklist'] },
      { id: 'echo-picklist', t: 'Drop in an Echo picklist', group: 'Experiments', on: ['exp'],
        q: ['echo', 'picklist', 'transfer', 'csv from echo', 'labcyte', 'drop csv', 'check plates', 'lista de transferencia', 'archivo de echo', 'soltar csv', 'revisar placas', 'source plate', 'destination plate'],
        a: 'Drop the Echo transfer CSV on the square in **Files**. It is stored whole, so there is never any doubt which compounds were used: every destination plate, in order. Plate 1 fills the plate map with compound, concentration and volume.',
        steps: ['A transfer whose status is not OK never reached the plate, so it is not recorded; failed wells are listed and crossed out.', '**Check plates** shows each plate with the compound names over their blocks: one plate 1…X, or all together.'],
        show: [{ sel: '#fx-drop', say: 'Drop the picklist here.', miss: NOEXP }] },
      { id: 'results', t: 'Get potencies into the experiment', group: 'Experiments', on: ['exp'],
        q: ['results', 'dc50', 'potency', 'send results', 'from echo', 'from lumina', 'flagged', 'exclude a result', 'resultados', 'potencia', 'enviar resultados', 'desde echo', 'excluir', 'n=3', 'replicates statistics', 'geometric mean'],
        a: 'In dHUB, **Send to Labbook** in Echo Dose Response, Lumina, BCA or Blueprint attaches the numbers to an experiment (you are asked which one). A **Results** section appears with the potencies, and each keeps its QC flag.',
        steps: ['You can add a note to a measurement and **exclude** it: an excluded row stays in the table, struck through, but leaves the results sentence.', 'Repeat an experiment as a replicate and the Results show n biological replicates: technical duplicates are averaged first, and potencies use a geometric mean.'],
        tip: 'The fitter’s flag is its opinion; excluding is yours. Only yours removes a number from the text.' },
      { id: 'setup-edit', t: 'Change the setup of an experiment', group: 'Experiments', on: ['exp'],
        q: ['edit setup', 'change setup', 'change plate format', 'change cell line', 'setup', 'cambiar setup', 'cambiar formato', 'cambiar linea celular', 'refresh wording', 'update text from preset'],
        a: '**Setup** on the experiment re-applies your answers (format, cell line, counts) to the steps: volumes rescale and the text follows. Dates, ticks and notes are not touched.',
        tip: '**Refresh wording** updates steps you have not written in when a preset has been corrected; it shows both versions side by side.',
        show: [{ sel: '.exh-setup-edit', say: 'Edit the setup here.', miss: NOEXP }] },
      { id: 'close', t: 'Close an experiment and record the outcome', group: 'Experiments', on: ['exp'],
        q: ['close experiment', 'finish', 'outcome', 'verdict', 'worked', 'failed', 'complete an experiment', 'cerrar experimento', 'resultado', 'termino', 'funciono', 'fallo', 'archive', 'archivar', 'abandon', 'paused'],
        a: '**Close** asks how it ended (done, paused or abandoned) and then, if you like, whether it **worked**, partly worked, failed or was inconclusive. Nothing is inferred and nothing is required.',
        tip: 'A closed experiment stops asking for work: its unticked steps are no longer carried over.',
        show: [{ sel: '.exh-acts', say: 'Close is among the experiment’s actions.', miss: NOEXP }] },
      { id: 'replicate', t: 'Repeat an experiment', group: 'Experiments', on: ['exp', 'exps'],
        q: ['repeat', 'replicate', 'biological replicate', 'do it again', 'duplicate', 'copy experiment', 'repetir', 'replica', 'replicado biologico', 'duplicar', 'copiar experimento', 'again'],
        steps: ['**Repeat as replicate:** the same plan, dates rebased with the same gaps, ticks reset. Your parameter changes and notes are kept, because a replicate repeats what you actually did. The runs are linked as “replicate 2 of 3”.', '**Duplicate:** a fresh plan dated from today, with nothing ticked and no results.'],
        tip: 'Both are on the experiment’s actions, and on a row’s menu in Experiments.' },
      { id: 'report', t: 'The Report: the whole experiment as a document', group: 'Output', on: ['exp'],
        q: ['report', 'methods', 'methods paragraph', 'publication', 'write up', 'export', 'pdf', 'word', 'document', 'informe', 'metodos', 'parrafo de metodos', 'publicacion', 'exportar', 'documento', 'paper'],
        a: 'The **Report** is the last section of an experiment; it is folded until you open it. It gathers the aim, the run, the setup, a **Methods paragraph**, the plate map, deviations, what happened, results, observations, outcome and files, and every way out of the app is on it.',
        steps: ['**Record PDF** — everything. **Methods sheet** — only what a manuscript needs.', '**Bench sheet** — the steps to print and take to the lab. **What you need** — the materials and where they are.', '**Copy**, **Word**, **Data…** and **Plate PNG**.', 'Each section has a switch, so the page contains what you choose.'],
        show: [{ sel: '#sec-pub', say: 'Open the Report here.', miss: NOEXP }], see: ['methods-live', 'pdf-scope'] },
      { id: 'methods-live', t: 'The Methods paragraph writes itself', group: 'Output', on: ['exp'],
        q: ['methods paragraph', 'edit methods', 'methods stale', 'back to live', 'rebuild', 'wording', 'parrafo', 'editar metodos', 'volver a automatico', 'analysis software', 'prism'],
        a: 'The paragraph is built from the experiment every time you read it, so it always matches the steps. The moment you type in it, your wording is kept, and a note says when the steps have since changed.',
        tip: '**Back to live** hands control back. Past tense and only what someone needs to repeat the work: rationale and bench instructions are left out.' },
      { id: 'pdf-scope', t: 'Export a PDF of many experiments, or a month', group: 'Output',
        q: ['export pdf', 'pdf', 'print', 'export a project', 'export month', 'export journal', 'all experiments', 'imprimir', 'exportar proyecto', 'exportar mes', 'exportar diario', 'summary', 'resumen'],
        a: '**Export** opens a dialog with the page on the right and tick boxes on the left. **What to export** covers: this experiment, a project or folder, all experiments, a date range, one day, a month or the whole Journal. A bulk export gets a cover and an index.',
        tip: '“A summary, not the full records” gives one table for the lot.' },
      { id: 'data-out', t: 'Get the data out (JSON, CSV) or move an experiment', group: 'Output',
        q: ['data', 'json', 'csv', 'import experiment', 'export data', 'move between notebooks', 'send an experiment to a colleague', 'datos', 'importar experimento', 'exportar datos', 'mandar experimento', 'colega'],
        a: '**Data…** offers the experiment as JSON, its results and steps as CSV, and every result in the notebook as one CSV. The same picker imports a JSON experiment.',
        warn: 'An import is always a new record and says where it came from. Attachment bytes are not in the JSON; the backup carries those.' },
      { id: 'journal', t: 'The Journal', group: 'Journal', on: ['journal'],
        q: ['journal', 'diary', 'day page', 'daily note', 'free note', 'notes', 'notebook', 'diario', 'pagina del dia', 'nota diaria', 'notas', 'cuaderno', 'onenote'],
        a: 'The Journal is a list of days and a flat list of **Notes**. A day page **writes itself** from what you ticked that day: project, experiment code and title, then the time, the step and your one-line “what happened”. Below it is the day’s free note.',
        tip: 'Notes are for anything with no date. Pages that existed before were moved to the day they were written.',
        prep: toJournal, show: [{ sel: '.day-jr-card, .day-jr-open', say: 'The day’s free note.', miss: 'Open a day in the Journal first.' }], see: ['mentions'] },
      { id: 'mentions', t: '@, # and / in a note', group: 'Journal', on: ['journal', 'exp'],
        q: ['mention', 'link to an experiment', 'tag', 'slash menu', 'insert', 'table', 'checklist', 'at sign', 'hashtag', 'etiqueta', 'enlazar', 'insertar', 'menu barra', 'arroba', 'formatting', 'bold', 'formato'],
        steps: ['`@` links an experiment, protocol, antibody, plasmid or page.', '`#` adds a tag; searching a tag finds every place it was used.', '`/` opens the insert menu: plate map, table, image, link, date…', 'Select text and a small bar offers bold, italic, colour, size, lists and more.'] },
      { id: 'autocorrect', t: 'Text that corrects itself', group: 'Journal',
        q: ['autocorrect', 'micro sign', 'um to µm', 'degrees', 'sum', 'calculate in text', 'arrows', 'compound names', 'autocorreccion', 'micro', 'grados', 'suma', 'flechas', 'ul', 'ug', 'oC'],
        a: 'While you type, Labbook fixes the notation a keyboard cannot produce:',
        steps: ['`40 uM` → **40 µM**, `ul` → µL, `37 oC` → 37 °C.', '`9*9=` gives 81; `^` is a power.', '`naoh`, `nacl`, `dmso`, `tris` get their proper case.', '`->`, `<-`, `+/-`, `<=`, `>=` become arrows and signs.'],
        tip: '`⌘Z` takes a correction back. Pasted text is never touched.' },
      { id: 'search', t: 'Search everything', group: 'Finding things',
        q: ['search', 'find', 'cmd k', 'ctrl k', 'spotlight', 'find an experiment', 'search notes', 'search text', 'buscar', 'encontrar', 'buscador', 'buscar en notas', 'open by code'],
        a: '`⌘K` (`Ctrl+K`) searches names **and** what you wrote: step text, notes, day notes, observations, plate maps, Methods paragraphs and results. It forgives typos, accents and the other word for the same thing (“immunoblot” finds Western blot).',
        tip: '`⌘O` opens an experiment straight by its code.',
        show: [{ sel: '.tp-btn[onclick^="openSpot"]', say: 'Search is here.', miss: 'Inside dHUB, search is the box at the top of the page (`⌘K`).' }] },
      { id: 'shortcuts', t: 'Keyboard shortcuts', group: 'Finding things',
        q: ['shortcuts', 'keyboard', 'keys', 'hotkeys', 'atajos', 'teclado', 'teclas', 'atajos de teclado', 'commands'],
        a: function(ctx){
          var S = (ctx.w && ctx.w.SHORTCUTS) || [], mod = /Mac|iPhone|iPad/.test(navigator.platform || '') ? '⌘' : 'Ctrl+', out = [], groups = {}, order = [];
          S.forEach(function(s){
            if (s.where === 'text' && s.g !== 'Writing') return;
            var k = s.raw || (mod + (s.shift ? '⇧' : '') + s.show);
            if (!groups[s.g]) { groups[s.g] = []; order.push(s.g); }
            groups[s.g].push('`' + k + '` ' + s.lbl);
          });
          order.forEach(function(g){ out.push('**' + g + ':** ' + groups[g].slice(0, 8).join(' · ')); });
          return out.length ? out : 'Press `⌘/` to see the full list.';
        },
        tip: '`⌘/` shows the whole list; `⌘,` opens Settings.',
        go: [{ l: 'Show the full list', fn: 'openSettings', args: ['keys'] }] },
      { id: 'undo', t: 'Undo a mistake', group: 'Finding things',
        q: ['undo', 'redo', 'mistake', 'deleted by accident', 'oops', 'deshacer', 'error', 'borre sin querer', 'rehacer', 'ctrl z', 'cmd z'],
        a: '`⌘Z` / `Ctrl+Z` undoes, `⌘⇧Z` redoes: ticks, moves, plate edits, deletions. Typing inside a text box is undone by the browser as usual. If you deleted something, it is also in **Recover → Deleted items** for 60 days.',
        see: ['recover'] },
      { id: 'recover', t: 'Recover something deleted or lost', group: 'Your data',
        q: ['recover', 'deleted', 'restore', 'trash', 'recycle bin', 'version history', 'old version', 'backup file', 'snapshot', 'papelera', 'recuperar', 'restaurar', 'borrado', 'version anterior', 'historial de versiones', 'perdi', 'lost my work'],
        a: '**Recover** has four tabs:',
        steps: ['**Deleted items** — kept for 60 days, projects and folders with their experiments as one entry.', '**Versions** — earlier states of an experiment, including a copy that arrived from another device.', '**Snapshots** — the last week of automatic local snapshots.', '**Backup file** — restore from a file (it merges rather than replaces).'],
        go: [{ l: 'Open Recover', fn: 'openRecover' }] },
      { id: 'backup', t: 'Back up my notebook', group: 'Your data',
        q: ['backup', 'back up', 'save a copy', 'backup folder', 'auto backup', 'download backup', 'copia de seguridad', 'respaldo', 'guardar copia', 'carpeta de backup'],
        a: 'Labbook keeps its data in this browser and backs it up in two ways. **Back up now** (`⌘S`, or the backup note at the top) writes a file to a backup folder you chose; right-click the note to choose the folder.',
        steps: ['If no folder is chosen, an automatic backup keeps a local snapshot instead and asks once for a folder.', 'An automatic backup **never opens a download dialog**: a download only happens when you press a button.', 'A backup carries attachments too, and restoring merges instead of replacing.'],
        show: [{ sel: '#lb-backup-note', say: 'Click to back up now. Right-click to choose the folder.', miss: 'The backup note is in the top bar of the standalone build.' }],
        go: [{ l: 'Back up now', fn: 'doBackup', args: [true] }] },
      { id: 'saved', t: 'Is my work saved? What the status means', group: 'Your data',
        q: ['saved', 'sync', 'status', 'saved on this device', 'not saved', 'cloud', 'other device', 'guardado', 'sincronizar', 'estado', 'otro dispositivo', 'nube', 'phone and laptop', 'movil y portatil', 'offline'],
        a: 'The pill at the top says exactly where your work is. **Saved on this device** means it is in this browser only (a standalone build with no account). Signed in, it says it is synced, and changes made on another device arrive live; if the same experiment was changed in both places, yours is kept and theirs is saved in its Versions.',
        warn: '**Not saved!** means the browser refused the write (usually storage is full). Back up now and free space.',
        tip: 'The status is shown honestly: it never says “saved” for something that only lives on this device.' },
      { id: 'visualize', t: 'Charts of my experiments', group: 'Overview', on: ['viz'],
        q: ['visualize', 'charts', 'statistics', 'dashboard', 'success rate', 'heatmap', 'timeline', 'potency landscape', 'graficos', 'estadisticas', 'panel', 'tasa de exito', 'linea de tiempo'],
        a: '**Visualize** draws your notebook: tiles (experiments, running, success rate, steps ticked, measurements, overdue), an activity heatmap, the monthly rhythm, projects by status, verdicts per type, a timeline, and the **potency landscape** of every measurement Echo Dose Response sent. Filter by project, type and range; click any mark to open what is behind it.',
        go: [{ l: 'Open Visualize', fn: 'selectNode', args: ['viz', '', ''] }] },
      { id: 'week', t: 'The week at a glance', group: 'Overview', on: ['week'],
        q: ['week', 'weekly planner', 'calendar', 'this week', 'semana', 'planificador', 'calendario', 'esta semana'],
        a: '**Week** lays the steps and tasks of the week out by day, across all experiments. Drag a step to another day to re-date it; the menu on a step has the rest.',
        go: [{ l: 'Open Week', fn: 'selectNode', args: ['week', '', ''] }] },
      { id: 'codes', t: 'How experiment codes work', group: 'Experiments', on: ['exps', 'exp'],
        q: ['code', 'experiment code', 'prefix', 'project prefix', 'naming', 'name of experiment', 'codigo', 'prefijo', 'prefijo del proyecto', 'nombre del experimento', 'SP_NB'],
        a: 'A code reads **PREFIX_TYPE+DATE_TARGET**, for example `SP_NB20260826_BRD4`: the project’s two-letter prefix, the experiment type and start date, and an optional target.',
        tip: 'Each project got a prefix from its name. Click the prefix chip on the project header to change it; the experiments already in the project are re-coded after you confirm.' },
      { id: 'menus', t: 'Right-click, ⋯ and long-press', group: 'Finding things',
        q: ['right click', 'context menu', 'menu', 'more actions', 'long press', 'three dots', 'clic derecho', 'menu contextual', 'mas acciones', 'pulsacion larga', 'tres puntos'],
        a: 'Almost everything has a menu, reached three ways that open the same one: **right-click**, the **⋯** button, or a **long press** on a phone. Steps, experiments, projects, folders, plate maps, files and days each have their own.' },
      { id: 'phone', t: 'Using Labbook on a phone', group: 'Your data',
        q: ['phone', 'mobile', 'iphone', 'bench', 'at the bench', 'install', 'add to home screen', 'app', 'movil', 'telefono', 'en el banco', 'instalar', 'pantalla de inicio', 'pwa'],
        a: 'On a phone the bar along the bottom has **Home**, **Experiments**, **Journal**, **+** and **More**. An experiment opens on its steps as you run them: grouped by day, one row per step with a tick, the wait and a camera.',
        steps: ['Long-press a row for its menu.', 'Hold **+** to take a photo into today’s note.', 'The plate map opens full screen.'],
        tip: 'If you were given the installed version, use “Add to Home Screen”; it also works offline.' },
      { id: 'tour', t: 'Take the tour', group: 'Getting started',
        q: ['tour', 'walkthrough', 'guided tour', 'show me around', 'intro', 'help', 'recorrido', 'tutorial guiado', 'ensename', 'ayuda'],
        a: 'The tour walks through the real screens and points at the real controls: Home, Today, Experiments, an experiment and its Report, the Journal, Visualize and search. It ends where you started.',
        go: [{ l: 'Take the tour', fn: 'startTour' }] }
    ]
  });
})();
