// Lumina: dose-response for assays you pipette by hand.
(function(){
  var plate = function(w){ w.switchTab('input'); };
  var results = function(w){ w.switchTab('results'); };
  var FIT1 = 'The results appear once you have fitted curves: finish the plate and press **Fit curves**.';
  var NEXT = [null,
    { msg: 'Next: **drag across the wells** the dilution series covers.', t: 'gradient' },
    { msg: 'Next: **drag across the area** the compounds go in.', t: 'compounds' },
    { msg: 'Next: **drag across the control wells.**', t: 'controls' },
    { msg: 'Next: **name the compounds.**', t: 'names' },
    { msg: 'Next: **add the readings** — drop the reader file on the plate.', t: 'readings' }];
  assistRegister('lumina', {
    name: 'Lumina',
    blurb: 'Lumina fits dose–response curves for assays you pipette by hand. You draw the layout on the plate — which wells are which dilution series, which compound, which controls — drop the reader file onto it, and get potencies with their fits.',
    first: ['start', 'tour', 'assay-types', 'readings', 'export'],
    avoid: [],
    screen: function(w){ return w.document.querySelector('#pane-results.active') ? 'results' : 'plate'; },
    diag: function(w){
      var out = [], d = w.document;
      if (d.querySelector('#pane-results.active')) return out;
      var n = w._lmNextStep ? w._lmNextStep() : 0;
      if (n && NEXT[n]) out.push(NEXT[n]);
      return out;
    },
    topics: [
      { id: 'tour', t: 'Take a guided tour', group: 'Getting started', on: ['plate','results'],
        q: ['guided tour', 'take the tour', 'tour of this tool', 'show me around', 'visita guiada', 'recorrido guiado', 'enseñame la herramienta'],
        a: 'A one-minute tour moves through each part of this tool and points at what it is for. It is also on the **Guide** tab, where every part has a tour of its own.',
        go: [{ l: 'Take the tour', fn: 'appTour' }],
        show: { sel: '.tab[data-tab="guide"]', say: 'The Guide tab keeps the tour, and a tour for each part.' } },
      { id: 'start', t: 'Your first plate in five steps', group: 'Getting started', on: ['plate'],
        q: ['first plate', 'get started', 'how do i start', 'how to use', 'tutorial', 'walkthrough', 'empezar', 'como empiezo', 'como se usa', 'primeros pasos', 'quick start'],
        a: 'The five steps along the top of the plate say what is done and what is next; you can click any of them to jump there.',
        steps: ['Pick the **assay type** and the **plate size**.',
                '**Gradient:** drag across the wells one dilution series covers, then give the top concentration and the dilution factor.',
                '**Compounds:** drag across the area the compounds go in and press **Make compounds**.',
                '**Controls:** drag across the control wells and mark them.',
                '**Names:** type the compound names, or paste a column from Excel.',
                '**Readings:** drop the reader file on the plate, then press **Fit curves**.'],
        tip: 'Nothing is lost if you do them in a different order; the steps only say what is still missing.',
        prep: plate,
        show: [{ sel: '#assay-type', say: 'Choose the **assay type**. It decides how readings are normalised.' }, { sel: '#format-seg', say: 'Then the **plate size**.' },
               { sel: '#lm-steps', say: 'These five steps track your progress. Click one to go there.' }, { sel: '#well-grid', say: 'Then **drag across wells** on the plate to say what they are.' }],
        go: [{ l: 'Load an example plate', fn: 'loadLuminaTestData' }], see: ['gradient', 'compounds', 'readings'] },
      { id: 'assay-types', t: 'Which assay type do I pick?', group: 'Getting started', on: ['plate'],
        q: ['assay type', 'hibit', 'ctg', 'cell titer glo', 'displacement', 'gain of signal', 'dc50', 'ic50', 'ec50', 'dmax', 'which assay', 'tipo de ensayo', 'viability', 'degradation', 'viabilidad', 'degradacion'],
        a: 'The type sets how readings are normalised and what the potency is called everywhere: the table, the plot, the exports.',
        steps: ['**HiBiT degradation:** DC50 and Dmax.', '**CTG viability:** IC50 and Span.', '**Displacement:** IC50; it needs both a 100% and a 0% control.', '**Gain of signal:** EC50 and Emax.'],
        prep: plate, show: { sel: '#assay-type', say: 'Choose the assay type here.' } },
      { id: 'select-wells', t: 'Selecting wells', group: 'The plate', on: ['plate'],
        q: ['select wells', 'select', 'drag', 'range', 'shift', 'select a row', 'select all', 'select column', 'seleccionar pocillos', 'seleccionar', 'rango', 'a1:b11', 'rubber band', 'marquee'],
        steps: ['**Drag** across wells to select a rectangle.', '**Shift** extends the selection from where it started.', '`⌘` / `Ctrl` adds or removes wells.', 'A **row or column label** takes the whole line; the corner takes the plate.', 'A compound’s label takes the compound; a double-click takes its whole zone.', 'Or type a range such as `B2:C11` in the box above the panel and press Enter.', '`Esc` deselects.'],
        prep: plate, show: [{ sel: '#well-grid', say: 'Drag here.' }] },
      { id: 'gradient', t: 'Draw a dilution series (gradient)', group: 'The plate', on: ['plate'],
        q: ['gradient', 'dilution series', 'serial dilution', 'concentrations', 'top concentration', 'dilution factor', 'set gradient', 'serie de diluciones', 'diluciones', 'concentracion', 'factor de dilucion', 'highest at', 'points', 'puntos', 'direction', 'direccion'],
        a: 'A gradient is one dilution series drawn on the plate. Its points run along the direction you choose; the other way across the selection is replicates.',
        steps: ['Drag across the wells the series covers — any shape, any direction.', 'In the panel, give the **Top conc.**, its unit and the **Dilution** (fold between neighbouring points).', 'Choose **Highest at** (← → ↑ ↓).', 'Press **Set gradient**.'],
        tip: 'You can divide a plate into as many gradients as it holds. Wells shaded dark to light show which end is highest.',
        prep: plate, show: [{ sel: '#well-grid', say: 'Drag across the wells of one series, then set the numbers in the panel that appears.' }],
        see: ['compounds', 'select-wells'] },
      { id: 'compounds', t: 'Make compounds from a gradient', group: 'The plate', on: ['plate'],
        q: ['make compounds', 'compounds', 'zones', 'replicates', 'how many replicates', 'replicate rows or columns', 'compuestos', 'replicados', 'hacer compuestos', 'duplicates', 'triplicates', 'duplicados', 'triplicados', 'more compounds'],
        a: 'Once a gradient exists, tell Lumina how the replicates lie: the area you select is cut into bands of replicates across the gradient, one compound per band, numbered in reading order.',
        steps: ['Drag across the whole area the compounds occupy.', 'Choose the replicates per compound (1–4).', 'Off a gradient it also asks whether replicates are **rows** or **columns**.', 'Press **Make compounds**.'],
        tip: 'A compound never straddles two gradients, so two half-plate gradients give compounds per half. More compounds than fit continue on the next plate.',
        prep: plate, show: [{ sel: '#well-grid', say: 'Select the area the compounds go in.' }], see: ['names', 'more-plates'] },
      { id: 'controls', t: 'Mark the controls', group: 'The plate', on: ['plate'],
        q: ['controls', '100% control', '0% control', 'vehicle', 'dmso', 'untreated', 'normalise', 'normalize', 'normalization', 'controles', 'control 100', 'control 0', 'normalizar', 'positive control', 'negative control'],
        a: 'Each plate is normalised to its own controls, so they are marked once and apply to every plate.',
        steps: ['Drag across the wells that read 100% (the vehicle or untreated signal).', 'Press **100% control**.', 'For **displacement**, do the same for the **0% control**.'],
        warn: 'With no control marked, everything stays in raw counts: percent-based fit settings (fixed top or bottom, replicate SD, hook) stand aside, and the results say so.',
        prep: plate, show: [{ sel: '#well-grid', say: 'Select the control wells here.' }] },
      { id: 'names', t: 'Name your compounds', group: 'The plate', on: ['plate'],
        q: ['name compounds', 'compound names', 'rename compound', 'paste names', 'names', 'nombres', 'nombrar compuestos', 'nombre de compuestos', 'labels', 'list of compounds'],
        a: 'Compounds are numbered by position and named separately, so the layout never depends on what a compound is called.',
        steps: ['Open the **Names** step.', 'Type a name for each number, or paste a column from Excel; a pasted list fills downwards and adds plates as needed.'],
        go: [{ l: 'Open Names', fn: 'lmStepGo', args: [4] }], prep: plate, show: [{ sel: '#lm-steps', say: 'Click **Names**.' }] },
      { id: 'readings', t: 'Add the reader values', group: 'The plate', on: ['plate'],
        q: ['readings', 'reader file', 'add data', 'import', 'load data', 'pherastar', 'drop file', 'upload', 'excel file', 'lecturas', 'cargar datos', 'cargar archivo', 'importar', 'archivo del lector', 'luminescence', 'luminiscencia', 'signal'],
        a: 'Drop the reader export anywhere on the plate card, one file per plate. Several files dropped together fill Plate 1, 2, 3… in name order.',
        steps: ['Drop the file on the plate, or press **Choose files**.', 'A plate already loaded from a file of the same name is replaced, so dropping a run twice does not duplicate it.', 'A file whose grid is a different size from the plate says so instead of reading the wrong wells.'],
        tip: 'Double-click a well in the Readings view to type or correct one value. The colour follows the reading, so a dead row or column shows at a glance.',
        go: [{ l: 'Choose files', fn: 'lmPickFiles' }, { l: 'Open Readings', fn: 'lmStepGo', args: [5] }],
        prep: plate, show: [{ sel: '#lm-card', say: 'Drop the reader file anywhere on this card.' }], see: ['paste-excel', 'more-plates'] },
      { id: 'paste-excel', t: 'Paste readings from Excel', group: 'The plate', on: ['plate'],
        q: ['paste from excel', 'copy from excel', 'paste values', 'ctrl v', 'cmd v', 'pegar desde excel', 'pegar valores', 'pegar', 'without pherastar', 'other reader', 'csv', 'clipboard'],
        a: 'Any spreadsheet works, not only PHERAstar files. Copy the block of numbers in Excel and press `⌘V` (`Ctrl+V`) with the plate in view.',
        steps: ['Rows that carry their letters land by letter; title and header lines around them are skipped.', 'A bare block of numbers lands with its top-left at the selected well.', 'A `.csv` or `.txt` file goes through the same reader.'],
        prep: plate },
      { id: 'more-plates', t: 'More compounds than one plate holds', group: 'The plate', on: ['plate'],
        q: ['second plate', 'more plates', 'plate 2', 'multiple plates', 'many compounds', 'add plate', 'mas placas', 'segunda placa', 'varias placas', 'plate tabs', 'continue on next plate'],
        a: 'The layout is shared by every plate. Extra plates continue the compound numbering — plate 2 starts where plate 1 ended — and each plate is normalised to its own controls before the results are pooled.',
        tip: 'Wells are reported as `P2:C3` once there is more than one plate. Double-click a plate’s tab or press `F2` to rename it.',
        prep: plate, show: [{ sel: '#lm-plates', say: 'Plates are tabs here.' }], see: ['names', 'readings'] },
      { id: 'undo', t: 'Undo and clear', group: 'The plate', on: ['plate'],
        q: ['undo', 'redo', 'clear', 'reset', 'start over', 'clear layout', 'deshacer', 'borrar', 'empezar de nuevo', 'limpiar', 'mistake', 'error', 'oops'],
        a: '`⌘Z` (`Ctrl+Z`) or the **Undo** button takes back the last change to the layout. **Clear these wells** empties just the selection; **Clear layout** starts the plate over. `Delete` clears the selected wells.',
        prep: plate, show: [{ sel: '#lm-undo', say: 'Undo is here.', miss: 'Undo appears after you change the layout.' }] },
      { id: 'copy-block', t: 'Copy a block of layout', group: 'The plate', on: ['plate'],
        q: ['copy block', 'copy wells', 'duplicate layout', 'cut', 'paste layout', 'copiar bloque', 'copiar layout', 'repeat pattern'],
        a: 'Select a block of wells and press `⌘C`, then click where the top-left corner should go and press `⌘V`. `⌘X` cuts. The same shortcut pastes values copied from Excel, whichever you copied last.',
        prep: plate },
      { id: 'why-disabled', t: 'Why is Fit curves greyed out?', group: 'Fitting', on: ['plate'],
        q: ['fit curves disabled', 'cannot fit', 'fit button grey', 'not ready', 'no puedo ajustar', 'boton gris', 'fit does nothing', 'why cant i fit'],
        a: 'It stays disabled until the layout and readings are complete, and says what is missing beside it: **Set a gradient**, **Make compounds**, or **Add the readings**.',
        prep: plate, show: [{ sel: '#lm-fit', say: 'The reason is written next to this button.' }] },
      { id: 'fit', t: 'Fit the curves', group: 'Fitting', on: ['plate'],
        q: ['fit curves', 'fit', 'run analysis', 'calculate', 'get results', 'analyse', 'analyze', 'ajustar curvas', 'analizar', 'calcular', 'ajuste', '4pl', 'four parameter'],
        a: 'Press **Fit curves →** when the steps are done. Each compound gets a four-parameter logistic fit. Results never go stale: change the plate or a fit setting and the table refits itself.',
        prep: plate, show: [{ sel: '#lm-fit', say: 'Press this when the steps are done.' }] },
      { id: 'results-table', t: 'Reading the results table', group: 'Results', on: ['results'],
        q: ['results table', 'results', 'read results', 'what do the columns mean', 'ci', 'confidence interval', 'r2', 'hill', 'span', 'tabla de resultados', 'resultados', 'columnas', 'intervalo de confianza', 'potency', 'potencia'],
        a: 'One row per compound: the potency (DC50, IC50 or EC50, following the assay), its 95% confidence interval, the effect (Dmax, Span or Emax), the Hill slope and R². A QC chip appears only when something is flagged.',
        tip: '`↑` `↓` move through the compounds, `←` `→` switch between Fit and Raw, and `P` / `C` switch between Plot and Curve.',
        prep: results, show: [{ sel: '#results-table-wrap', say: 'Click a row to see its curve.' }], see: ['flags', 'exclude-point'] },
      { id: 'flags', t: 'Why is a curve flagged?', group: 'Results', on: ['results'],
        q: ['flagged', 'flag', 'qc', 'warning', 'bad curve', 'range', 'hook', 'low r2', 'replicates differ', 'curva marcada', 'aviso', 'fuera de rango', 'outside range', 'greater than', 'less than'],
        a: 'A flag says why a number should be looked at before it is used:',
        steps: ['**R² below the limit** — a poor fit.', '**Replicates differ** by more than the SD limit.', '**Hook** — the top doses rise again (HiBiT and CTG).', '**>range / <range** — the potency sits outside the doses tested, so it is an extrapolation.'],
        tip: 'A flagged curve keeps its number, visibly flagged. You can change every limit in **Fit settings**.',
        prep: results, show: [{ sel: '#rs-set-btn', say: 'The limits are in Fit settings.', miss: FIT1 }], see: ['fit-settings', 'exclude-point'] },
      { id: 'fit-settings', t: 'Fit settings', group: 'Results', on: ['results'],
        q: ['fit settings', 'constrain fit', 'fix top', 'fix bottom', 'fix hill', 'qc limits', 'thresholds', 'settings', 'ajustes del ajuste', 'fijar', 'limites', 'umbral'],
        a: 'The panel has two groups: **Flag a curve when…** sets the QC limits, and **Constrain the fit** fixes the top, the bottom or the Hill slope. A dot on the button means something differs from the defaults.',
        tip: 'Rows that do not apply to the assay type, or that a choice above has switched off, are dimmed rather than hidden, so nothing moves under the pointer.',
        prep: results, show: [{ sel: '#rs-set-btn', say: 'Fit settings open here.', miss: FIT1 }] },
      { id: 'exclude-point', t: 'Leave out a bad point', group: 'Results', on: ['results'],
        q: ['exclude point', 'remove point', 'outlier', 'leave out', 'ignore point', 'excluir punto', 'quitar punto', 'punto raro', 'put back', 'include point', 'refit'],
        a: 'On the curve, click a point to leave it out; the fit updates at once and a cross marks where it was. Click or right-click the cross to put it back.',
        prep: results, show: [{ sel: '#curve-canvas', say: 'Click a point on the curve.', miss: FIT1 }] },
      { id: 'units', t: 'Change the concentration units', group: 'Results', on: ['results'],
        q: ['units', 'nm', 'um', 'pm', 'molar', 'log', 'log10', 'unidades', 'cambiar unidades', 'change units', 'scale', 'escala'],
        a: 'The **Units** button sets the unit (Auto, or M to pM) and linear or log₁₀. It drives the table, the plot, copies and every export, so they always agree.',
        prep: results, show: [{ sel: '#rs-units-btn', say: 'Units are here.', miss: FIT1 }] },
      { id: 'plot', t: 'Plot one result against another', group: 'Results', on: ['results'],
        q: ['plot', 'scatter', 'chart', 'compare compounds', 'graph', 'grafico', 'comparar compuestos', 'dmax vs dc50', 'xy'],
        a: 'Switch **Curve** to **Plot** to draw any fitted quantity against any other; the default is potency against Dmax. Hollow red points are flagged, colour can follow the plate, and you can search a compound to dim the rest.',
        tip: 'Click a point to select that compound; double-click for its curve. **Save PNG** always uses a light background so it is ready for a slide.',
        prep: results, show: [{ sel: '#rs-tabs', say: 'Switch to Plot here.', miss: FIT1 }] },
      { id: 'export', t: 'Export the results', group: 'Results', on: ['results'],
        q: ['export', 'save results', 'download', 'excel', 'csv', 'prism', 'copy table', 'png', 'exportar', 'descargar', 'guardar resultados', 'copiar tabla', 'get data out'],
        steps: ['**Excel workbook** — results, raw data, Prism tables and the fit settings.', '**Results (.csv)** — the table as a plain file.', '**Copy table** — paste into Excel, Prism or a notebook.', '**Raw data (.csv)** — one row per well, normalised.', '**Plot as image (.png)**.'],
        tip: 'Exports use the unit you picked in **Units**.',
        prep: results, show: [{ sel: '#rs-exp-btn', say: 'Everything comes out through Export.', miss: FIT1 }] },
      { id: 'send-labbook', t: 'Send the potencies to Labbook', group: 'Results', on: ['results'], needs: 'labbook',
        q: ['labbook', 'send to labbook', 'notebook', 'experiment record', 'enviar a labbook', 'cuaderno', 'attach results'],
        a: 'Inside dHUB, **Send to Labbook** attaches the potencies to an experiment. They land on its Results tab with their flags and the reason for each flag, and feed the Methods paragraph.',
        prep: results, show: [{ sel: '#rs-lb', say: 'Send them from here.' }] }
    ]
  });
})();
