// Ribbon: protein structures as figures.
(function(){
  var NEED = 'This appears once a structure is loaded. Type a PDB code first, for example **5T35**.';
  function open(sec){ return function(w){ if (w.rbOpenSec) w.rbOpenSec(sec); else { var d = w.document.querySelector('details.rb-sec[data-sec="' + sec + '"]'); if (d) d.open = true; } }; }
  var KB = {
    name: 'Ribbon',
    blurb: 'Ribbon draws a protein structure as a figure. Load one from the PDB or AlphaFold, or open your own file; colour the chains, label them, pull out a ligand and the residues around it, and export a picture at print resolution.',
    first: ['start', 'load', 'colour', 'label', 'export'],
    avoid: ['#legend'],   // the colour key sits bottom-right where the bubble does
    screen: function(w){ return w.document.body.classList.contains('rb-empty') ? 'empty' : 'viewer'; },
    diag: function(w){
      var d = [], b = w.document.body;
      if (b.classList.contains('rb-no3d')) d.push({ msg: '**The 3D viewer could not be loaded.** It is fetched from the internet the first time. Reconnect and press **Try again** in the viewer.', t: 'offline' });
      else if (b.classList.contains('rb-empty')) d.push({ msg: 'Next: **type a PDB code**, a UniProt id or a protein name — or drop a file on the viewer.', t: 'load' });
      return d;
    },
    topics: [
      { id: 'start', t: 'Your first figure in five steps', group: 'Getting started', on: ['empty', 'viewer'],
        q: ['first figure', 'get started', 'how do i start', 'how to use', 'tutorial', 'walkthrough', 'empezar', 'como empiezo', 'como se usa', 'primeros pasos', 'quick start'],
        a: 'Everything is on one screen: the structure on the left, the controls on the right — where ChimeraX and PyMOL keep them — in tabs down the right edge: **Open · Models · Colour · Analyse · Figure · Designs**. Click the open tab again to fold the panel away.',
        steps: ['**Load** a structure: a PDB code (try `5T35`), a UniProt id, a protein name, or a file.',
                'Pick the **style** and the **colour** along the top.',
                'Click a chain to **colour and label** it, or open **Models** to pull out a ligand and its pocket.',
                '**Save the design** if you want to come back to it.',
                '**Export** the picture.'],
        tip: 'Press **F** any time to fit the structure to the view.',
        show: [{ sel: '#pdbInput', say: 'Start by typing a code here.' }], see: ['load', 'colour', 'export'] },
      { id: 'load', t: 'Load a structure', group: 'Structures', on: ['empty', 'viewer'],
        q: ['load', 'open', 'pdb', 'pdb code', 'fetch', 'download structure', 'find a protein', 'search', 'uniprot', 'cargar', 'abrir', 'buscar proteina', 'codigo pdb', 'estructura'],
        a: 'One box takes three kinds of text, and works out which it is.',
        steps: ['A **PDB code** (`1CRN`, or the long form `pdb_00001crn`) opens that entry.', 'A **UniProt id** (`P04637`) or an AlphaFold id opens the AlphaFold model.', 'Anything else is a **name** — Ribbon lists matching PDB entries and the AlphaFold model of the protein.'],
        tip: 'The examples under the box open in one click.',
        show: [{ sel: '#pdbInput', say: 'Type here and press **Go** or Enter.' }, { sel: '#exampleChips', say: 'Or press one of these.' }], see: ['alphafold', 'file'] },
      { id: 'alphafold', t: 'AlphaFold models and confidence', group: 'Structures', on: ['empty', 'viewer'],
        q: ['alphafold', 'af model', 'predicted structure', 'plddt', 'confidence', 'prediction', 'modelo alphafold', 'prediccion', 'confianza'],
        a: 'A UniProt id opens the AlphaFold model of that protein and colours it by **pLDDT**, how sure AlphaFold is of each residue: dark blue above 90, light blue 70–90, yellow 50–70 and orange below 50.',
        tip: 'Low-confidence regions are usually flexible loops or tails, not a wrong structure — which is why they look like spaghetti.',
        warn: 'A model is a prediction, not an experiment. The colour key is on the viewer and can be added to the exported picture.',
        show: [{ sel: '.example-chip[data-pdb="P04637"]', say: 'The AF p53 example opens one.' }] },
      { id: 'file', t: 'Open your own file', group: 'Structures', on: ['empty', 'viewer'],
        q: ['file', 'open file', 'drop', 'drag and drop', 'my structure', 'local file', 'docking', 'cif', 'gz', 'archivo', 'abrir archivo', 'arrastrar', 'mi estructura'],
        a: 'Press **Open file…** or drop a file anywhere on the page: `.pdb`, `.ent`, `.cif`, `.mmcif`, `.pqr`, and the same gzipped (`.gz`).',
        tip: 'A file that is not a structure is refused and the one on screen stays. A design saved on a file is applied when you open that file again.',
        show: [{ sel: '#openFileBtn', say: 'Press here, or drop a file on the viewer.' }] },
      { id: 'move', t: 'Rotate, zoom and fit', group: 'The view', on: ['viewer'],
        q: ['rotate', 'zoom', 'move', 'pan', 'fit', 'reset view', 'center', 'spin', 'auto rotate', 'girar', 'zoom', 'mover', 'centrar', 'ajustar'],
        a: ['**Drag** rotates, the **scroll wheel** (or a pinch) zooms, a **right-drag** moves the structure.', '**Fit** brings the whole structure back into view: the button with the corners, or **F**.'],
        tip: 'Until you move it yourself, the structure re-fits when the window changes. **S** turns it slowly.',
        show: [{ sel: '#resetViewBtn', say: 'Fit to view.', miss: NEED }, { sel: '#spinBtn', say: 'Auto-rotate.', miss: NEED }] },
      { id: 'colour', t: 'Style, colour and the palette', group: 'Look', on: ['viewer'],
        q: ['colour', 'color', 'colours', 'palette', 'style', 'cartoon', 'surface', 'stick', 'rainbow', 'secondary structure', 'pastel', 'hue', 'saturation', 'color por cadena', 'estilo', 'paleta', 'colores'],
        a: ['**Style** (Cartoon, Surface, Stick) and **Colour** are along the top: one colour for all, by chain, a rainbow from N- to C-terminus, by secondary structure, or by B-factor (confidence, for AlphaFold).',
            'Under **Appearance**, the **All colours** sliders tune every colour at once, in every mode — raise Light and lower Sat for a pastel, paper-style look.'],
        tip: 'A colour you pick for a chain, or a highlight, stays on top of the mode.',
        show: [{ sel: '#topColor', say: 'Colour mode.', miss: NEED }, { sel: '#hslS', say: 'The palette sliders.', miss: NEED }], prep: open('appearance'), see: ['chain', 'surface'] },
      { id: 'chain', t: 'Colour and label a chain', group: 'Chains', on: ['viewer'],
        q: ['chain', 'colour a chain', 'label a chain', 'name a chain', 'tag', 'cadena', 'colorear cadena', 'etiquetar cadena', 'nombre de cadena'],
        a: 'Click a chain in the structure — or its name in the **Chains** list, which works from the keyboard — and a small panel opens: pick its colour (or type a hex), and type a **label**. The label is a tag on the figure, joined to the chain by a line; drag it where you want it.',
        tip: 'The other chains fade while the panel is open, so you can see which one you are on. **Esc** closes the panel.',
        show: [{ sel: '#chainList', say: 'Every chain, with its molecule name.', miss: NEED }], see: ['hide', 'label'] },
      { id: 'hide', t: 'Hide a chain, or show only one', group: 'Chains', on: ['viewer'],
        q: ['hide chain', 'show only', 'isolate', 'remove chain', 'solo', 'eye', 'ocultar cadena', 'mostrar solo', 'aislar', 'quitar cadena'],
        a: 'In the **Chains** list the **eye** hides a chain and the **target** shows only that one (press it again to show them all). **Show all** appears when anything is hidden.',
        tip: 'A hidden chain takes its labels with it and is left out of the export; the view re-fits to what is left.',
        show: [{ sel: '#chainList .ch-eye', say: 'The eye.', miss: NEED }] },
      { id: 'label', t: 'Label residues and move the labels', group: 'Labels', on: ['viewer'],
        q: ['label residue', 'tag residues', 'residue label', 'annotate', 'text', 'move label', 'font', 'etiqueta', 'residuo', 'anotar', 'mover etiqueta'],
        a: ['Press **Tag residues** (or **T**), then click atoms: each click puts a label on that residue, and a second click on the same residue removes it. **Esc** leaves tag mode.',
            'Every label — chain or residue — is drag-able, moves with the arrow keys when focused (**Shift** for bigger steps), and is removed with **Delete**. The font, size, shape and colours are under **Labels**.'],
        tip: 'The text of a residue label can be edited in the Labels list.',
        show: [{ sel: '#resTagBtn', say: 'Tag residues.', miss: NEED }] },
      { id: 'highlight', t: 'Highlight residues', group: 'Highlight', on: ['viewer'],
        q: ['highlight', 'residues', 'range', 'domain', 'interface', 'a:45-60', 'resaltar', 'dominio', 'rango', 'interfaz', 'residuos'],
        a: 'Under **Highlight**, type residue ranges as `chain:first-last` — `A:45-60, B:100` — and press **Add**. They are coloured in the figure, in every mode and in the surface; tick the box to draw their side chains as sticks.',
        tip: 'A range the structure does not have is refused with the reason (chains and numbering are the structure\'s own). The colour dot cycles through the palette.',
        prep: open('highlight'), show: [{ sel: '#hlInput', say: 'Type a range here.', miss: NEED }] },
      { id: 'ligand', t: 'Ligands and the pocket around them', group: 'Highlight', on: ['viewer'],
        q: ['ligand', 'protac', 'pocket', 'binding site', 'drug', 'compound', 'molecular glue', 'ternary complex', 'ligando', 'bolsillo', 'sitio de union', 'complejo ternario'],
        a: ['**Highlight › Ligands** lists what is bound in the structure — a PROTAC or glue included. Click one to **zoom** to it, click its **colour dot** to change its carbon colour (so it stands out from the protein), and press the dashed circle for its **pocket**: the residues within the radius you set, as sticks.',
            '**Show ligands** and **Show waters** are under Chains.'],
        tip: 'Ions are drawn but not listed. Try `5T35`: a VHL–PROTAC–BRD4 ternary complex.',
        prep: open('chains'), show: [{ sel: '#ligList', say: 'The ligands.', miss: NEED }] },
      { id: 'measure', t: 'Measure a distance or an angle', group: 'Measure', on: ['viewer'],
        q: ['measure', 'distance', 'angle', 'angstrom', 'contact', 'hydrogen bond', 'h-bond', 'ruler', 'medir', 'distancia', 'angulo', 'contacto', 'puente de hidrogeno'],
        a: ['Press **Measure** (the ruler, or **M**) and click **two atoms** for a distance, or **three** for an angle at the middle one (switch under **Measure**). A dashed line and its value stay on the figure.',
            'An atom you measure has its residue drawn as sticks, so the side chain is there to see. The list under Measure can be copied as a table, and the values follow the model when you step through an NMR ensemble.'],
        tip: 'A measurement label can be dragged like any other label and is removed with **Delete**. Its line is part of the export, and goes with **Include labels**.',
        prep: open('measure'), show: [{ sel: '#measBtn', say: 'The ruler.', miss: NEED }], see: ['label'] },
      { id: 'interface', t: 'The interface between two chains', group: 'Highlight', on: ['viewer'],
        q: ['interface', 'protein protein interface', 'contacts', 'buried surface', 'bsa', 'ternary complex', 'cooperativity', 'residues in contact', 'interfaz', 'superficie enterrada', 'contactos', 'cooperatividad', 'complejo ternario'],
        a: ['Under **Interface**, pick two chains (the chips suggest the ones that touch most), and Ribbon finds the residues of each within the distance you set — any atom of one near any atom of the other. They are coloured and drawn as sticks, and the card gives the number of contacts and the **buried surface area** in Å².',
            'The closest residue pairs are listed with their distance; the ruler measures one in the figure. **Add as highlights** keeps the two sets, **Copy residues** gives them as `A:45-60, B:100`, and **Copy table** gives every pair for a spreadsheet.'],
        tip: 'For a PROTAC ternary complex this is the protein–protein interface the degrader brings about: 5T35 chains D and A.',
        warn: 'The buried surface is the accessible area of each chain alone less that of the two together (probe 1.4 Å), so it is the area lost by both sides; half of it is the usual "per side" figure.',
        prep: open('interface'), show: [{ sel: '#ifA', say: 'Pick the two chains.', miss: NEED }], see: ['measure', 'highlight'] },
      { id: 'compare', t: 'Superimpose a second structure', group: 'Compare', on: ['viewer'],
        q: ['superimpose', 'superpose', 'align', 'overlay', 'compare structures', 'rmsd', 'second structure', 'two structures', 'superponer', 'alinear', 'comparar estructuras', 'segunda estructura', 'solapar'],
        a: ['Under **Compare**, type a PDB code or UniProt id (or open a file) and it is laid over the structure you have. Ribbon pairs the residues of the two chains by **sequence alignment**, fits the second onto the first with a rigid motion that **leaves out the outliers** (anything further than twice the RMSD, repeated), and reports the **RMSD** and how many residues were used.',
            'It picks the best pair of chains; the two lists change that. The whole second structure moves, ligands included, so you can see whether a ligand sits in the same place. **Put it back** returns it to where its file had it.'],
        tip: 'A ligand in two structures of the same protein: align on the protein, then hide the second one\'s cartoon in Colour and keep its sticks — or just look at them together.',
        warn: 'The fit is only as meaningful as the chains: it warns when the RMSD is large or the sequences share little. It does not search for a structural match between unrelated proteins.',
        prep: open('compare'), show: [{ sel: '#ovInput', say: 'Type a code here and press **Add**.', miss: NEED }], see: ['interface'] },
      { id: 'values', t: 'Colour by conservation, variants or your own numbers', group: 'Look', on: ['viewer'],
        q: ['conservation', 'conserved', 'alignment', 'variants', 'mutations', 'mutation', 'snp', 'hotspot', 'colour by value', 'per residue', 'rmsf', 'dms', 'custom colours', 'conservacion', 'conservado', 'alineamiento', 'variantes', 'mutaciones', 'valores por residuo'],
        a: ['Under **Values**, three ways to colour residues by something you know about them:',
            '**Alignment** — paste a multiple alignment (FASTA or Clustal; the sequences must already be aligned) and Ribbon scores every column (1 − its entropy, weighted down by gaps) and maps it onto the chain: deep red where conserved, teal where variable.',
            '**Variants** — type `R175H, G245S, A:R248Q, 249`: each is highlighted with its side chain and labelled with its name; a wild-type letter that is not what the structure has is reported.',
            '**Table** — one number per residue (`A:45 0.8`, or `45,0.8`) for anything: RMSF, a deep-mutational score, a hit rate. Residues without a value stay grey.'],
        tip: 'The colour key names what the numbers are and goes into the export. **Reverse the colours** swaps the ends; the palette sliders still tune them.',
        warn: 'An alignment of a different protein is refused (too few identical residues), rather than coloured at random.',
        prep: open('values'), show: [{ sel: '#valSeg', say: 'Alignment, variants or a table.', miss: NEED }], see: ['highlight', 'colour'] },
      { id: 'surface', t: 'A molecular surface', group: 'Look', on: ['viewer'],
        q: ['surface', 'molecular surface', 'transparent', 'opacity', 'superficie', 'opacidad'],
        a: 'Choose **Surface** in the style: the cartoon stays inside a translucent surface of the visible chains. The **Surface** slider that appears sets its opacity, and a colour change recolours it without recomputing it.',
        tip: 'Very large structures take a few seconds to build a surface.',
        show: [{ sel: '#styleSeg', say: 'Style.' }] },
      { id: 'designs', t: 'Save a design', group: 'Designs', on: ['empty', 'viewer'],
        q: ['design', 'save', 'saved', 'preset', 'remember', 'load design', 'guardar', 'diseño', 'recordar'],
        a: 'A **design** keeps the structure, every colour and label, the highlights, the hidden chains **and the camera**, so loading it gives back the same figure. A name already in use asks before it is replaced; a deleted design can be restored from the message.',
        tip: 'Designs are kept in this browser, and sync between your devices when the Hub is signed in.',
        prep: open('designs'), show: [{ sel: '#designName', say: 'Name it and press **Save**.' }] },
      { id: 'export', t: 'Export a picture', group: 'Export', on: ['viewer'],
        q: ['export', 'download', 'png', 'jpeg', 'dpi', 'resolution', 'image', 'figure', 'copy image', 'slide', 'paper', 'exportar', 'descargar', 'imagen', 'resolucion', 'copiar imagen'],
        a: ['The **download** button along the top (or **⌘/Ctrl E**) opens the export: background (transparent, white or dark), PNG or JPEG, and 300, 600 or 1200 dpi. The picture is rendered at that size and **cropped to the structure**.',
            '**Copy** puts it on the clipboard for a slide. Inside dHUB, **Send to Labbook** attaches it to an experiment. With confidence colouring there is a tick for the **colour key**.'],
        tip: 'Labels are drawn into the picture exactly where you put them, unless **Include labels** is off.',
        show: [{ sel: '#exportBtn2', say: 'Export.', miss: NEED }] },
      { id: 'panels', t: 'A figure of several panels (A, B, C)', group: 'Export', on: ['viewer'],
        q: ['panels', 'panel', 'multi panel', 'multipanel', 'figure', 'side by side', 'compose', 'compare views', 'letters', 'a b c', 'paneles', 'figura', 'varios paneles', 'lado a lado', 'componer'],
        a: ['Save each view as a design (**Designs › Save**), then press **Multi-panel figure…** under the list. Pick the designs in the order of the panels, choose a **row**, a **column** or a **grid**, and press **Make the figure**.',
            'Each panel is exported exactly as the normal export would draw it, with its own colours, labels and camera, then laid out with the letters **A B C** (or a b c, or none). Download it, copy it, or send it to Labbook.'],
        tip: 'The designs may be of different structures: Ribbon loads each one for its picture, and puts the figure you had back afterwards. A design of a file you opened can only be a panel while that file is open.',
        warn: 'Stop ends it after the panel being drawn. A very large figure is scaled down to fit what a browser can save.',
        prep: open('designs'), show: [{ sel: '#panelsBtn', say: 'Multi-panel figure.', miss: NEED }] },
      { id: 'target', t: 'Open a hit\'s target from Hit Finder', group: 'Structures', on: ['viewer','empty'],
        q: ['hit finder', 'target', 'open target', 'pocket of a hit', 'binding site', 'where does it bind', 'structure of the target', 'from hit finder', 'gene', 'blanco', 'diana', 'sitio de union', 'abrir la proteina'],
        a: ['In **Hit Finder**, open a compound and press **Open <target> in Ribbon**. Ribbon finds the protein, opens the best-resolved structure of it that has a real ligand in it (not glycerol or sulfate), draws that ligand and the residues around it, and zooms in.',
            'If the protein has PDB entries but none with a ligand, the best-resolved entry opens without a pocket. If it has none at all, the AlphaFold model opens.'],
        warn: 'The pocket is the ligand that is in the crystal, not your compound. The note under the structure\'s title says so and names both.',
        tip: 'You can also type a gene name (BRD4) into the box and pick from the list. The Hit Finder route only does that choice for you.' },
      { id: 'script', t: 'Take the figure into PyMOL or ChimeraX', group: 'Export', on: ['viewer'],
        q: ['pymol', 'chimerax', 'chimera', 'script', 'pml', 'cxc', 'session', 'export script', 'continue in pymol', 'ray trace', 'render', 'guion', 'sesion', 'exportar a pymol'],
        a: ['In the export dialog, **PyMOL script** and **ChimeraX script** save the figure as commands: the structure, the style, every residue in the colour it has on screen (palette tuning, chain colours, highlights, the interface and values included), hidden chains, ligands and pockets, sticks, labels, measurements and the direction you are looking from.',
            'Open it in the program (**File › Run script** in PyMOL, **File › Open** in ChimeraX). It fetches the structure by its PDB code or AlphaFold link; for a file you opened, keep the file next to the script.'],
        tip: 'The program frames the structure itself, so the zoom and the window shape are its own. The last lines of the script, commented out, save a high-resolution picture.',
        warn: 'A second structure superposed in Ribbon is not part of the script.',
        show: [{ sel: '#exportBtn2', say: 'Export, then the two script buttons at the bottom.', miss: NEED }] },
      { id: 'models', t: 'Models of an NMR structure', group: 'Structures', on: ['viewer'],
        q: ['nmr', 'models', 'ensemble', 'frames', 'conformers', 'modelos', 'conjunto', 'conformeros'],
        a: 'A file with several models (an NMR ensemble) shows a small control at the bottom of the viewer: the arrows or the slider step through the models.',
        show: [{ sel: '#frame-ctl', say: 'The model control.', miss: 'This structure has a single model.' }] },
      { id: 'projection', t: 'Perspective or orthographic', group: 'Look', on: ['viewer'],
        q: ['projection', 'orthographic', 'perspective', 'depth', 'proyeccion', 'ortografica', 'perspectiva'],
        a: 'Under **Appearance › Projection**, **Orthographic** removes perspective, so equal things are the same size however far they are — the usual choice for a figure that compares parts.',
        prep: open('appearance'), show: [{ sel: '#projSeg', say: 'Projection.', miss: NEED }] },
      { id: 'shortcuts', t: 'Keyboard shortcuts', group: 'Getting started', on: ['empty', 'viewer'],
        q: ['shortcuts', 'keyboard', 'keys', 'hotkeys', 'atajos', 'teclado', 'teclas'],
        a: ['**F** fit the structure to the view · **T** tag residues · **S** auto-rotate · **⌘/Ctrl E** export · **Esc** close the panel or dialog, leave tag mode.', 'The same list is under the gear in the header. They do nothing while you are typing in a box.'] },
      { id: 'offline', t: 'The 3D viewer does not load', group: 'When something is wrong', on: ['empty', 'viewer'],
        q: ['not loading', 'viewer not loading', 'blank', 'offline', 'no internet', 'cdn', 'error', 'no carga', 'sin internet', 'en blanco', 'visor'],
        a: 'The 3D library is fetched from the internet the first time, from three mirrors in turn, and checked against a fingerprint. If none answers, the viewer says so and everything else (designs, settings) still works. Reconnect and press **Try again** in the viewer.',
        tip: 'Fetching a structure needs the internet as well (RCSB or AlphaFold); opening your own file does not, once the viewer has loaded.',
        show: [{ sel: '#veRetry', say: 'Try again.', miss: 'The viewer has loaded, so there is nothing to retry.' }] }
    ]
  };
  // The panel is tabs: whatever a topic points at is brought on screen first (its tab, its section).
  KB.topics.forEach(function(t){
    if (!t.show) return;
    var own = t.prep;
    t.prep = function(w){ if (own) own(w); if (w.rbReveal) t.show.forEach(function(x){ try { w.rbReveal(x.sel); } catch (e) {} }); };
  });
  assistRegister('ribbon', KB);
})();
