// Ribbon: protein structures as figures.
(function(){
  var NEED = 'This appears once a structure is loaded. Type a PDB code first, for example **5T35**.';
  function open(sec){ return function(w){ if (w.rbOpenSec) w.rbOpenSec(sec); else { var d = w.document.querySelector('details.rb-sec[data-sec="' + sec + '"]'); if (d) d.open = true; } }; }
  var KB = {
    name: 'Ribbon',
    blurb: 'Ribbon draws a protein structure as a figure. Load one from the PDB or AlphaFold, or open your own file; colour the chains, label them, pull out a ligand and the residues around it, and export a picture at print resolution.',
    first: ['start', 'tabs', 'command', 'select', 'export'],
    avoid: ['#legend'],   // the colour key sits bottom-right where the bubble does
    screen: function(w){ return w.document.body.classList.contains('rb-empty') ? 'empty' : 'viewer'; },
    diag: function(w){
      var d = [], b = w.document.body;
      if (b.classList.contains('rb-no3d')) d.push({ msg: '**The 3D viewer could not be loaded.** It is fetched from the internet the first time. Reconnect and press **Try again** in the viewer.', t: 'offline' });
      else if (b.classList.contains('rb-empty')) d.push({ msg: 'Next: **type a PDB code**, a UniProt id or a protein name — or drop a file on the viewer.', t: 'load' });
      return d;
    },
    topics: [
      { id: 'start', t: 'Your first figure in five steps', group: 'Getting started', on: ['empty', 'viewer'],
        q: ['first figure', 'get started', 'how do i start', 'how to use', 'tutorial', 'walkthrough', 'empezar', 'como empiezo', 'como se usa', 'primeros pasos', 'quick start'],
        a: 'Everything is on one screen: the structure on the left, the controls on the right — where ChimeraX and PyMOL keep them — in tabs down the right edge: **Open · Models · Colour · Analyse · Figure · Designs**. Click the open tab again to fold the panel away.',
        steps: ['**Load** a structure: a PDB code (try `5T35`), a UniProt id, a protein name, or a file.',
                'Pick the **style** and the **colour** along the top.',
                'Click a chain to **colour and label** it, or open **Models** to pull out a ligand and its pocket.',
                '**Save the design** if you want to come back to it.',
                '**Export** the picture.'],
        tip: 'Press **F** any time to fit the structure to the view.',
        show: [{ sel: '#pdbInput', say: 'Start by typing a code here.' }], see: ['load', 'colour', 'export'] },
      { id: 'load', t: 'Load a structure', group: 'Structures', on: ['empty', 'viewer'],
        q: ['load', 'open', 'pdb', 'pdb code', 'fetch', 'download structure', 'find a protein', 'search', 'uniprot', 'cargar', 'abrir', 'buscar proteina', 'codigo pdb', 'estructura'],
        a: 'One box takes three kinds of text, and works out which it is.',
        steps: ['A **PDB code** (`1CRN`, or the long form `pdb_00001crn`) opens that entry.', 'A **UniProt id** (`P04637`) or an AlphaFold id opens the AlphaFold model.', 'Anything else is a **name** — Ribbon lists matching PDB entries and the AlphaFold model of the protein.'],
        tip: 'The examples under the box open in one click.',
        show: [{ sel: '#pdbInput', say: 'Type here and press **Go** or Enter.' }, { sel: '#exampleChips', say: 'Or press one of these.' }], see: ['alphafold', 'file'] },
      { id: 'alphafold', t: 'AlphaFold models and confidence', group: 'Structures', on: ['empty', 'viewer'],
        q: ['alphafold', 'af model', 'predicted structure', 'plddt', 'confidence', 'prediction', 'modelo alphafold', 'prediccion', 'confianza'],
        a: 'A UniProt id opens the AlphaFold model of that protein and colours it by **pLDDT**, how sure AlphaFold is of each residue: dark blue above 90, light blue 70–90, yellow 50–70 and orange below 50.',
        tip: 'Low-confidence regions are usually flexible loops or tails, not a wrong structure — which is why they look like spaghetti.',
        warn: 'A model is a prediction, not an experiment. The colour key is on the viewer and can be added to the exported picture.',
        show: [{ sel: '.example-chip[data-pdb="P04637"]', say: 'The AF p53 example opens one.' }] },
      { id: 'file', t: 'Open your own file', group: 'Structures', on: ['empty', 'viewer'],
        q: ['file', 'open file', 'drop', 'drag and drop', 'my structure', 'local file', 'docking', 'cif', 'gz', 'archivo', 'abrir archivo', 'arrastrar', 'mi estructura'],
        a: 'Press **Open file…** or drop a file anywhere on the page: `.pdb`, `.ent`, `.cif`, `.mmcif`, `.pqr`, and the same gzipped (`.gz`).',
        tip: 'A file that is not a structure is refused and the one on screen stays. A design saved on a file is applied when you open that file again.',
        show: [{ sel: '#openFileBtn', say: 'Press here, or drop a file on the viewer.' }] },
      { id: 'move', t: 'Rotate, zoom and fit', group: 'The view', on: ['viewer'],
        q: ['rotate', 'zoom', 'move', 'pan', 'fit', 'reset view', 'center', 'spin', 'auto rotate', 'girar', 'zoom', 'mover', 'centrar', 'ajustar'],
        a: ['**Drag** rotates, the **scroll wheel** (or a pinch) zooms, a **right-drag** moves the structure.', '**Fit** brings the whole structure back into view: the button with the corners, or **F**.'],
        tip: 'Until you move it yourself, the structure re-fits when the window changes. **S** turns it slowly.',
        show: [{ sel: '#resetViewBtn', say: 'Fit to view.', miss: NEED }, { sel: '#spinBtn', say: 'Auto-rotate.', miss: NEED }] },
      { id: 'colour', t: 'Style, colour and the palette', group: 'Look', on: ['viewer'],
        q: ['colour', 'color', 'colours', 'palette', 'style', 'cartoon', 'surface', 'stick', 'rainbow', 'secondary structure', 'pastel', 'hue', 'saturation', 'color por cadena', 'estilo', 'paleta', 'colores'],
        a: ['**Style** (Cartoon, Surface, Stick) and **Colour** are along the top: one colour for all, by chain, a rainbow from N- to C-terminus, by secondary structure, or by B-factor (confidence, for AlphaFold).',
            'In the **Colour** tab, **Look** has one-click styles and the lighting; under **Appearance**, the **All colours** sliders tune every colour at once, in every mode — raise Light and lower Sat for a pastel, paper-style look.'],
        tip: 'A colour you pick for a chain, or a highlight, stays on top of the mode.',
        show: [{ sel: '#topColor', say: 'Colour mode.', miss: NEED }, { sel: '#hslS', say: 'The palette sliders.', miss: NEED }], prep: open('appearance'), see: ['chain', 'surface'] },
      { id: 'chain', t: 'Colour and label a chain', group: 'Chains', on: ['viewer'],
        q: ['chain', 'colour a chain', 'label a chain', 'name a chain', 'tag', 'cadena', 'colorear cadena', 'etiquetar cadena', 'nombre de cadena'],
        a: 'Click a chain in the structure — or its name in the **Models** list, which works from the keyboard — and a small panel opens: pick its colour (or type a hex), and type a **label**. The label is a tag on the figure, joined to the chain by a line; drag it where you want it.',
        tip: 'The other chains fade while the panel is open, so you can see which one you are on. **Esc** closes the panel.',
        show: [{ sel: '#chainList', say: 'Every chain, with its molecule name.', miss: NEED }], see: ['hide', 'label'] },
      { id: 'hide', t: 'Hide a chain, or show only one', group: 'Chains', on: ['viewer'],
        q: ['hide chain', 'show only', 'isolate', 'remove chain', 'solo', 'eye', 'ocultar cadena', 'mostrar solo', 'aislar', 'quitar cadena'],
        a: 'In **Models** the **eye** hides a chain and the **target** shows only that one (press it again to show them all). **Show all** appears when anything is hidden.',
        tip: 'A hidden chain takes its labels with it and is left out of the export; the view re-fits to what is left.',
        show: [{ sel: '#chainList .ch-eye', say: 'The eye.', miss: NEED }] },
      { id: 'label', t: 'Label residues and move the labels', group: 'Labels', on: ['viewer'],
        q: ['label residue', 'tag residues', 'residue label', 'annotate', 'text', 'move label', 'font', 'etiqueta', 'residuo', 'anotar', 'mover etiqueta'],
        a: ['Press **Tag residues** (or **T**), then click atoms: each click puts a label on that residue, and a second click on the same residue removes it. **Esc** leaves tag mode.',
            'Every label — chain or residue — is drag-able, moves with the arrow keys when focused (**Shift** for bigger steps), and is removed with **Delete**. The font, size, shape and colours are under **Labels**.'],
        tip: 'The text of a residue label can be edited in the Labels list.',
        show: [{ sel: '#resTagBtn', say: 'Tag residues.', miss: NEED }] },
      { id: 'highlight', t: 'Highlight residues', group: 'Highlight', on: ['viewer'],
        q: ['highlight', 'residues', 'range', 'domain', 'interface', 'a:45-60', 'resaltar', 'dominio', 'rango', 'interfaz', 'residuos'],
        a: 'Under **Highlight**, type residue ranges as `chain:first-last` — `A:45-60, B:100` — and press **Add**. They are coloured in the figure, in every mode and in the surface; tick the box to draw their side chains as sticks.',
        tip: 'A range the structure does not have is refused with the reason (chains and numbering are the structure\'s own). The colour dot cycles through the palette.',
        prep: open('highlight'), show: [{ sel: '#hlInput', say: 'Type a range here.', miss: NEED }] },
      { id: 'ligand', t: 'Ligands and the pocket around them', group: 'Highlight', on: ['viewer'],
        q: ['ligand', 'protac', 'pocket', 'binding site', 'drug', 'compound', 'molecular glue', 'ternary complex', 'ligando', 'bolsillo', 'sitio de union', 'complejo ternario'],
        a: ['**Models › Ligands** lists what is bound in the structure — a PROTAC or glue included. Click one to **zoom** to it, click its **colour dot** to change its carbon colour (so it stands out from the protein), and press the dashed circle for its **pocket**: the residues within the radius you set, as sticks.',
            '**Show** (beside Ligands) and **Show waters** are in Models too.'],
        tip: 'Ions are drawn but not listed. Try `5T35`: a VHL–PROTAC–BRD4 ternary complex.',
        prep: open('chains'), show: [{ sel: '#ligList', say: 'The ligands.', miss: NEED }] },
      { id: 'measure', t: 'Measure a distance or an angle', group: 'Measure', on: ['viewer'],
        q: ['measure', 'distance', 'angle', 'angstrom', 'contact', 'hydrogen bond', 'h-bond', 'ruler', 'medir', 'distancia', 'angulo', 'contacto', 'puente de hidrogeno'],
        a: ['Press **Measure** (the ruler, or **M**) and click **two atoms** for a distance, or **three** for an angle at the middle one (switch under **Measure**). A dashed line and its value stay on the figure.',
            'An atom you measure has its residue drawn as sticks, so the side chain is there to see. The list under Measure can be copied as a table, and the values follow the model when you step through an NMR ensemble.'],
        tip: 'A measurement label can be dragged like any other label and is removed with **Delete**. Its line is part of the export, and goes with **Include labels**.',
        prep: open('measure'), show: [{ sel: '#measBtn', say: 'The ruler.', miss: NEED }], see: ['label'] },
      { id: 'interface', t: 'The interface between two chains', group: 'Highlight', on: ['viewer'],
        q: ['interface', 'protein protein interface', 'contacts', 'buried surface', 'bsa', 'ternary complex', 'cooperativity', 'residues in contact', 'interfaz', 'superficie enterrada', 'contactos', 'cooperatividad', 'complejo ternario'],
        a: ['Under **Interface**, pick two chains (the chips suggest the ones that touch most), and Ribbon finds the residues of each within the distance you set — any atom of one near any atom of the other. They are coloured and drawn as sticks, and the card gives the number of contacts and the **buried surface area** in Å².',
            'The closest residue pairs are listed with their distance; the ruler measures one in the figure. **Add as highlights** keeps the two sets, **Copy residues** gives them as `A:45-60, B:100`, and **Copy table** gives every pair for a spreadsheet.'],
        tip: 'For a PROTAC ternary complex this is the protein–protein interface the degrader brings about: 5T35 chains D and A.',
        warn: 'The buried surface is the accessible area of each chain alone less that of the two together (probe 1.4 Å), so it is the area lost by both sides; half of it is the usual "per side" figure.',
        prep: open('interface'), show: [{ sel: '#ifA', say: 'Pick the two chains.', miss: NEED }], see: ['measure', 'highlight'] },
      { id: 'compare', t: 'Superimpose a second structure', group: 'Compare', on: ['viewer'],
        q: ['superimpose', 'superpose', 'align', 'overlay', 'compare structures', 'rmsd', 'second structure', 'two structures', 'superponer', 'alinear', 'comparar estructuras', 'segunda estructura', 'solapar'],
        a: ['Under **Compare**, type a PDB code or UniProt id (or open a file) and it is laid over the structure you have. Ribbon pairs the residues of the two chains by **sequence alignment**, fits the second onto the first with a rigid motion that **leaves out the outliers** (anything further than twice the RMSD, repeated), and reports the **RMSD** and how many residues were used.',
            'It picks the best pair of chains; the two lists change that. The whole second structure moves, ligands included, so you can see whether a ligand sits in the same place. **Put it back** returns it to where its file had it.'],
        tip: 'A ligand in two structures of the same protein: align on the protein, then hide the second one\'s cartoon in Colour and keep its sticks — or just look at them together.',
        warn: 'The fit is only as meaningful as the chains: it warns when the RMSD is large or the sequences share little. It does not search for a structural match between unrelated proteins.',
        prep: open('compare'), show: [{ sel: '#ovInput', say: 'Type a code here and press **Add**.', miss: NEED }], see: ['interface'] },
      { id: 'values', t: 'Colour by conservation, variants or your own numbers', group: 'Look', on: ['viewer'],
        q: ['conservation', 'conserved', 'alignment', 'variants', 'mutations', 'mutation', 'snp', 'hotspot', 'colour by value', 'per residue', 'rmsf', 'dms', 'custom colours', 'conservacion', 'conservado', 'alineamiento', 'variantes', 'mutaciones', 'valores por residuo'],
        a: ['Under **Values**, three ways to colour residues by something you know about them:',
            '**Alignment** — paste a multiple alignment (FASTA or Clustal; the sequences must already be aligned) and Ribbon scores every column (1 − its entropy, weighted down by gaps) and maps it onto the chain: deep red where conserved, teal where variable.',
            '**Variants** — type `R175H, G245S, A:R248Q, 249`: each is highlighted with its side chain and labelled with its name; a wild-type letter that is not what the structure has is reported.',
            '**Table** — one number per residue (`A:45 0.8`, or `45,0.8`) for anything: RMSF, a deep-mutational score, a hit rate. Residues without a value stay grey.'],
        tip: 'The colour key names what the numbers are and goes into the export. **Reverse the colours** swaps the ends; the palette sliders still tune them.',
        warn: 'An alignment of a different protein is refused (too few identical residues), rather than coloured at random.',
        prep: open('values'), show: [{ sel: '#valSeg', say: 'Alignment, variants or a table.', miss: NEED }], see: ['highlight', 'colour'] },
      { id: 'surface', t: 'A molecular surface', group: 'Look', on: ['viewer'],
        q: ['surface', 'molecular surface', 'transparent', 'opacity', 'superficie', 'opacidad'],
        a: 'Choose **Surface** in the style: the cartoon stays inside a translucent surface of the visible chains. The **Surface** slider that appears sets its opacity, and a colour change recolours it without recomputing it.',
        tip: 'Very large structures take a few seconds to build a surface.',
        show: [{ sel: '#styleSeg', say: 'Style.' }] },
      { id: 'designs', t: 'Save a design', group: 'Designs', on: ['empty', 'viewer'],
        q: ['design', 'save', 'saved', 'preset', 'remember', 'load design', 'guardar', 'diseño', 'recordar'],
        a: 'A **design** keeps the structure, every colour and label, the highlights, the hidden chains **and the camera**, so loading it gives back the same figure. A name already in use asks before it is replaced; a deleted design can be restored from the message.',
        tip: 'Designs are kept in this browser, and sync between your devices when the Hub is signed in.',
        prep: open('designs'), show: [{ sel: '#designName', say: 'Name it and press **Save**.' }] },
      { id: 'export', t: 'Export a picture', group: 'Export', on: ['viewer'],
        q: ['export', 'download', 'png', 'jpeg', 'dpi', 'resolution', 'image', 'figure', 'copy image', 'slide', 'paper', 'exportar', 'descargar', 'imagen', 'resolucion', 'copiar imagen'],
        a: ['The **download** button along the top (or **⌘/Ctrl E**) opens the export: background (transparent, white or dark), PNG or JPEG, and 300, 600 or 1200 dpi. The picture is rendered at that size and **cropped to the structure**.',
            '**Copy** puts it on the clipboard for a slide. Inside dHUB, **Send to Labbook** attaches it to an experiment. With confidence colouring there is a tick for the **colour key**.'],
        tip: 'Labels are drawn into the picture exactly where you put them, unless **Include labels** is off.',
        show: [{ sel: '#exportBtn2', say: 'Export.', miss: NEED }] },
      { id: 'panels', t: 'A figure of several panels (A, B, C)', group: 'Export', on: ['viewer'],
        q: ['panels', 'panel', 'multi panel', 'multipanel', 'figure', 'side by side', 'compose', 'compare views', 'letters', 'a b c', 'paneles', 'figura', 'varios paneles', 'lado a lado', 'componer'],
        a: ['Save each view as a design (**Designs › Save**), then press **Multi-panel figure…** under the list. Pick the designs in the order of the panels, choose a **row**, a **column** or a **grid**, and press **Make the figure**.',
            'Each panel is exported exactly as the normal export would draw it, with its own colours, labels and camera, then laid out with the letters **A B C** (or a b c, or none). Download it, copy it, or send it to Labbook.'],
        tip: 'The designs may be of different structures: Ribbon loads each one for its picture, and puts the figure you had back afterwards. A design of a file you opened can only be a panel while that file is open.',
        warn: 'Stop ends it after the panel being drawn. A very large figure is scaled down to fit what a browser can save.',
        prep: open('designs'), show: [{ sel: '#panelsBtn', say: 'Multi-panel figure.', miss: NEED }] },
      { id: 'target', t: 'Open a hit\'s target from Hit Finder', group: 'Structures', on: ['viewer','empty'],
        q: ['hit finder', 'target', 'open target', 'pocket of a hit', 'binding site', 'where does it bind', 'structure of the target', 'from hit finder', 'gene', 'blanco', 'diana', 'sitio de union', 'abrir la proteina'],
        a: ['In **Hit Finder**, open a compound and press **Open <target> in Ribbon**. Ribbon finds the protein, opens the best-resolved structure of it that has a real ligand in it (not glycerol or sulfate), draws that ligand and the residues around it, and zooms in.',
            'If the protein has PDB entries but none with a ligand, the best-resolved entry opens without a pocket. If it has none at all, the AlphaFold model opens.'],
        warn: 'The pocket is the ligand that is in the crystal, not your compound. The note under the structure\'s title says so and names both.',
        tip: 'You can also type a gene name (BRD4) into the box and pick from the list. The Hit Finder route only does that choice for you.' },
      { id: 'script', t: 'Take the figure into PyMOL or ChimeraX', group: 'Export', on: ['viewer'],
        q: ['pymol', 'chimerax', 'chimera', 'script', 'pml', 'cxc', 'session', 'export script', 'continue in pymol', 'ray trace', 'render', 'guion', 'sesion', 'exportar a pymol'],
        a: ['In the export dialog, **PyMOL script** and **ChimeraX script** save the figure as commands: the structure, the style, every residue in the colour it has on screen (palette tuning, chain colours, highlights, the interface and values included), hidden chains, ligands and pockets, sticks, labels, measurements and the direction you are looking from.',
            'Open it in the program (**File › Run script** in PyMOL, **File › Open** in ChimeraX). It fetches the structure by its PDB code or AlphaFold link; for a file you opened, keep the file next to the script.'],
        tip: 'The program frames the structure itself, so the zoom and the window shape are its own. The last lines of the script, commented out, save a high-resolution picture.',
        warn: 'A second structure superposed in Ribbon is not part of the script.',
        show: [{ sel: '#exportBtn2', say: 'Export, then the two script buttons at the bottom.', miss: NEED }] },
      { id: 'models', t: 'Models of an NMR structure', group: 'Structures', on: ['viewer'],
        q: ['nmr', 'models', 'ensemble', 'frames', 'conformers', 'modelos', 'conjunto', 'conformeros'],
        a: 'A file with several models (an NMR ensemble) shows a small control at the bottom of the viewer: the arrows or the slider step through the models.',
        show: [{ sel: '#frame-ctl', say: 'The model control.', miss: 'This structure has a single model.' }] },
      { id: 'projection', t: 'Perspective or orthographic', group: 'Look', on: ['viewer'],
        q: ['projection', 'orthographic', 'perspective', 'depth', 'proyeccion', 'ortografica', 'perspectiva'],
        a: 'Under **Appearance › Projection**, **Orthographic** removes perspective, so equal things are the same size however far they are — the usual choice for a figure that compares parts.',
        prep: open('appearance'), show: [{ sel: '#projSeg', say: 'Projection.', miss: NEED }] },
      { id: 'shortcuts', t: 'Keyboard shortcuts', group: 'Getting started', on: ['empty', 'viewer'],
        q: ['shortcuts', 'keyboard', 'keys', 'hotkeys', 'atajos', 'teclado', 'teclas'],
        a: ['**F** fit · **T** tag residues · **M** measure · **S** auto-rotate · **Q** the sequence · **/** the command line · **⌘/Ctrl Z** undo, **⌘⇧Z** redo · **⌘/Ctrl E** export · **⌘-click** a residue selects it · **Esc** close, stop, or clear the selection.', 'The same list is under the gear in the header. They do nothing while you are typing in a box.'] },
      { id: 'tabs', t: 'The panel and its tabs', group: 'Getting started', on: ['empty', 'viewer'],
        q: ['panel', 'tabs', 'menu', 'where is', 'sidebar', 'right panel', 'hide panel', 'pestañas', 'menu', 'panel derecho', 'donde esta'],
        a: ['The controls are in tabs down the right edge: **Open** (find a structure), **Models** (chains, ligands and everything else in the scene, each with an eye), **Colour** (styles, light, palettes, values, highlights), **Analyse** (interactions, lysines, clashes, pockets, measurements, interfaces, a second structure, AlphaFold\'s error map), **Figure** (views, films, the scale bar, labels) and **Designs**.',
            'Click the open tab again to fold the panel away and give the structure the room; any tab brings it back.'],
        tip: 'The arrow keys move between tabs when one has the focus.', show: [{ sel: '#rbRail', say: 'The tabs.' }] },
      { id: 'scene', t: 'Put things away without deleting them', group: 'Chains', on: ['viewer'],
        q: ['models panel', 'eye', 'hide labels', 'hide measurements', 'hide highlights', 'hide ions', 'toggle', 'ocultar etiquetas', 'ocultar medidas', 'ojo'],
        a: '**Models › Also in the scene** lists what you have added — highlights, measurements, labels, a second structure, ions, the selection — each with an eye. The eye takes it off the figure and keeps it, so you can try a figure with and without in one click. A design remembers what is put away, and the scripts leave it out.',
        prep: open('chains'), show: [{ sel: '#modelExtras', say: 'Everything else in the scene.', miss: NEED }] },
      { id: 'sequence', t: 'The sequence above the structure', group: 'Selection', on: ['viewer'],
        q: ['sequence', 'sequence viewer', 'residue numbers', 'letters', 'amino acids', 'secuencia', 'aminoacidos', 'ver la secuencia'],
        a: ['The bar above the structure is the sequence of a chain (the chips switch chain, **All** shows every one), numbered every ten, with helices and strands as a band on top, and each letter in the colour its residue has on screen.',
            'Click a letter to select it, drag across for a range, **Shift** to extend, **⌘/Ctrl** to add; double-click zooms to it. The residue under the pointer is marked in the structure, and the other way round. **Q** shows and hides it.'],
        show: [{ sel: '#seqBtn', say: 'Sequence (Q).', miss: NEED }], see: ['select', 'command'] },
      { id: 'select', t: 'Select residues and act on them', group: 'Selection', on: ['viewer'],
        q: ['select', 'selection', 'pick residues', 'box select', 'choose residues', 'seleccionar', 'seleccion', 'elegir residuos'],
        a: ['Select residues from the **sequence**, with **⌘-click** (Ctrl-click) in the structure, with the **Select** button in the toolbar (a click selects, **Shift-drag** draws a box), or in the command line: `select within 5 of ligand`.',
            'The selection is green on screen — never in an export, a script or a design. Beside the sequence: **Zoom**, **Colour** (a highlight), **Sticks**, **Label**, and the cross to clear (or **Esc**).'],
        show: [{ sel: '#selBtn', say: 'Select mode.', miss: NEED }], see: ['sequence', 'command'] },
      { id: 'command', t: 'The command line', group: 'Selection', on: ['viewer'],
        q: ['command', 'command line', 'commands', 'type commands', 'console', 'script', 'chimerax commands', 'pymol commands', 'autocomplete', 'tab', 'comandos', 'linea de comandos', 'consola', 'autocompletar'],
        a: ['Under the structure (**/** to get there): type what you want — `color ligand yellow`, `select within 5 of ligand`, `show sel as sticks`, `hide waters`, `label chain A "BRD4"`, `interactions MZ1`, `lysines A D`, `preset ternary`, `lighting soft`, `movie turn gif`. **Tab** takes the grey suggestion; **↑** brings back what you ran; `help` lists every command, `help color` one.',
            'Selections speak plain words and the ChimeraX and PyMOL spellings alike: `chain A`, `/A:45-60`, `A:45-60`, `:LYS`, `lys`, `name CA`, `@NZ`, `ligand`, `ions`, `waters`, `helix`, `hydrophobic`, `within 5 of ligand`, `byres`, `interface`, `pocket`, `sel`, with `and`, `or`, `not` and brackets. Join commands with `;`.'],
        tip: 'The suggestions know this structure: its chains, residue names and ligands. A line you typed before is offered first when you start it the same way.',
        warn: 'There is no command line on a phone — the panel does everything there. In the Hub, ⌘K stays the Hub\'s search.',
        show: [{ sel: '#cmdInput', say: 'Type here (or press /).', miss: NEED }] },
      { id: 'look', t: 'Lighting, styles and palettes', group: 'Look', on: ['viewer'],
        q: ['lighting', 'light', 'shadows', 'ambient occlusion', 'depth cue', 'fog', 'style', 'preset', 'look', 'publication', 'cover', 'colour blind', 'colorblind', 'okabe', 'viridis', 'iluminacion', 'sombras', 'estilos', 'daltonico', 'portada'],
        a: ['**Colour › Look**: one-click **styles** (Clean, Ternary complex, Ligand pocket, Surface, Cover, Confidence) that set the colours, light, outline, background and projection — and never touch your labels, highlights or measurements.',
            '**Lighting**: Simple, Soft (crevices darken a little), Full (deep shadows — best on a surface) or Flat (a drawn look). **Depth cue** fades what is further away. **Chain colours** offers Okabe–Ito and Tol, made to stay apart for colour-blind readers; values can use viridis or cividis.'],
        tip: 'A chain colour that disappears on the background is pointed out under the palette.', prep: open('look'), show: [{ sel: '#presetGrid', say: 'The styles.', miss: NEED }] },
      { id: 'interactions', t: 'What a ligand makes with the protein', group: 'Analyse', on: ['viewer'],
        q: ['interactions', 'hydrogen bonds', 'h-bonds', 'salt bridge', 'pi stacking', 'hydrophobic contacts', 'halogen bond', 'plip', 'binding mode', 'interacciones', 'puentes de hidrogeno', 'apilamiento', 'modo de union'],
        a: ['**Analyse › Interactions**: pick a ligand (or a chain) and what to look against, and press **Find**. Hydrogen bonds, hydrophobic contacts, π-stacking, cation–π, halogen bonds and metals are drawn as dashed lines in their colours, the residues as sticks, and listed with their distances; chips switch each kind on and off; the table copies.',
            'Between two chains it also finds salt bridges.'],
        warn: 'Found from distances and angles in the file, heavy atoms only (there are no hydrogens in most files). A ligand\'s charges are not in the file, so salt bridges are only found between chains.',
        prep: open('interact'), show: [{ sel: '#interGo', say: 'Find interactions.', miss: NEED }] },
      { id: 'lysines', t: 'Lysines a ligase can reach (degraders)', group: 'Analyse', on: ['viewer'],
        q: ['lysine', 'lysines', 'ubiquitination', 'ubiquitin', 'degrader', 'protac', 'ternary', 'e3', 'reachable', 'lisinas', 'ubiquitinacion', 'degradador'],
        a: '**Analyse › Reachable lysines**: the target\'s lysines on the surface and within the distance you set of the ligase, nearest first, with how exposed each one is and how far it is from the degrader. They are coloured orange (nearer is deeper) and drawn as sticks. The target and the ligase are guessed from the entry (VHL, CRBN, DCAF… are ligases) and can be changed.',
        warn: 'This is the geometry of one pose. Which lysine is ubiquitinated also depends on the E2 and on how the complex moves.',
        prep: open('lysines'), show: [{ sel: '#lysGo', say: 'Find lysines.', miss: NEED }] },
      { id: 'pockets', t: 'Find pockets', group: 'Analyse', on: ['viewer'],
        q: ['pocket', 'pockets', 'cavity', 'cavities', 'binding pocket', 'druggable', 'bolsillo', 'cavidad', 'sitio de union'],
        a: '**Analyse › Pockets** looks for buried cavities in the chains shown — empty places with protein around them in most directions — and lists them by volume, with the residues that line them and any ligand already in them. Click one to see it alone and select its residues.',
        tip: 'In 5T35 the two largest are the ones that hold MZ1.', prep: open('pockets'), show: [{ sel: '#pocketGo', say: 'Find pockets.', miss: NEED }] },
      { id: 'clashes', t: 'Clashes and contacts', group: 'Analyse', on: ['viewer'],
        q: ['clash', 'clashes', 'overlap', 'steric', 'contacts', 'choques', 'solapamiento', 'esterico'],
        a: '**Analyse › Clashes and contacts**: between two chains, a ligand and a chain, or the selection and something else. Atoms whose van der Waals spheres overlap by 0.6 Å or more are clashes (red dashes); contacts are counted from −0.4 Å.',
        prep: open('clashes'), show: [{ sel: '#clGo', say: 'Check.', miss: NEED }] },
      { id: 'property', t: 'Colour by charge or hydrophobicity', group: 'Look', on: ['viewer'],
        q: ['charge', 'electrostatics', 'electrostatic', 'coulombic', 'hydrophobicity', 'hydrophobic surface', 'kyte doolittle', 'carga', 'electrostatica', 'hidrofobicidad'],
        a: 'In the **Colour** menu along the top: **Charge** (red negative, blue positive — Coulomb\'s law from the residues\' own charges, ε = 4r) and **Hydrophobicity** (Kyte–Doolittle: teal water-loving, orange oily). Both read best on a **Surface**.',
        warn: 'The charge is an estimate from the residues alone: no ligands, no pKa shifts, no ions.', show: [{ sel: '#topColor', say: 'Colour mode.', miss: NEED }] },
      { id: 'pae', t: 'AlphaFold\'s error map', group: 'Analyse', on: ['viewer'],
        q: ['pae', 'predicted aligned error', 'error map', 'domains', 'confident', 'mapa de error', 'dominios'],
        a: 'For an AlphaFold model, **Analyse › AlphaFold error map** shows how sure the model is of where each residue sits relative to every other (dark = sure). Two domains each confident on their own but not relative to each other are two dark squares. Drag a box on the map to select those residues; **Hide residues under pLDDT 70** keeps what the model is sure of.',
        prep: open('pae'), show: [{ sel: '#paeCanvas', say: 'The error map.', miss: 'This appears for an AlphaFold model: type a UniProt id, for example **P04637**.' }] },
      { id: 'undo', t: 'Undo and redo', group: 'Getting started', on: ['viewer'],
        q: ['undo', 'redo', 'take back', 'mistake', 'deshacer', 'rehacer', 'volver atras'],
        a: '**⌘/Ctrl Z** undoes, **⌘⇧Z** (or Ctrl+Y) redoes — also the arrows in the toolbar and `undo` in the command line. Everything a design keeps can be undone; dragging a slider is one step. Turning the structure is not an edit, so it is never undone.',
        show: [{ sel: '#undoBtn', say: 'Undo.', miss: NEED }] },
      { id: 'views', t: 'Views and films', group: 'Export', on: ['viewer'],
        q: ['view', 'views', 'camera', 'saved view', 'movie', 'film', 'video', 'gif', 'animation', 'rotate video', 'vista', 'pelicula', 'video', 'animacion'],
        a: ['**Figure › Views**: turn the structure to an angle you like and press **Add view**; a click on its picture brings the camera back exactly. Designs keep their views.',
            '**Figure › Film** records the structure turning, rocking, or flying through your views, as a video (MP4 in Safari, WebM in Chrome — both play in PowerPoint and Keynote) or a GIF.'],
        prep: open('views'), show: [{ sel: '#viewAdd', say: 'Add view.', miss: NEED }] },
      { id: 'roundtrip', t: 'Edit a figure that is in Labbook', group: 'Export', on: ['viewer', 'empty'],
        q: ['labbook', 'edit figure', 'update figure', 'notebook', 'send to labbook', 'edit in ribbon', 'cuaderno', 'editar figura', 'actualizar figura'],
        a: 'A figure sent to Labbook keeps the design it was made from. In the experiment\'s **Files**, **Edit in Ribbon** opens it here as it was — structure, colours, labels, camera. Change it, and **Export → Update in Labbook** replaces the picture there, keeping the caption you wrote in Labbook.',
        warn: 'A figure of a file you opened from your computer cannot be reopened from Labbook: the file is not in the notebook.' },
      { id: 'mutants', t: 'A mutant scan from Echo, on the protein', group: 'Look', on: ['viewer', 'empty'],
        q: ['mutant', 'mutants', 'mutation scan', 'alanine scan', 'echo', 'dc50 shift', 'mutantes', 'barrido de mutantes', 'escaneo de alanina'],
        a: 'In **Echo Dose Response**, groups named like `BRD4_Y97A` beside a group `BRD4` (or `BRD4 WT`) are read as mutants. **Mutants on the structure** opens the AlphaFold model of the protein here, with each mutated residue coloured by log2 of its DC50 against the wild type\'s, labelled (`Y97A ×8.0`) and drawn with its side chain. A mutant with no curve at all is drawn at the top of the scale and labelled “no effect”.',
        tip: 'The AlphaFold model is used because it is numbered as the protein is, so Y97 is residue 97.' },
      { id: 'offline', t: 'The 3D viewer does not load', group: 'When something is wrong', on: ['empty', 'viewer'],
        q: ['not loading', 'viewer not loading', 'blank', 'offline', 'no internet', 'cdn', 'error', 'no carga', 'sin internet', 'en blanco', 'visor'],
        a: 'The 3D library is fetched from the internet the first time, from three mirrors in turn, and checked against a fingerprint. If none answers, the viewer says so and everything else (designs, settings) still works. Reconnect and press **Try again** in the viewer.',
        tip: 'Fetching a structure needs the internet as well (RCSB or AlphaFold); opening your own file does not, once the viewer has loaded.',
        show: [{ sel: '#veRetry', say: 'Try again.', miss: 'The viewer has loaded, so there is nothing to retry.' }] }
    ]
  };
  // The panel is tabs: whatever a topic points at is brought on screen first (its tab, its section).
  KB.topics.forEach(function(t){
    if (!t.show) return;
    var own = t.prep;
    t.prep = function(w){ if (own) own(w); if (w.rbReveal) t.show.forEach(function(x){ try { w.rbReveal(x.sel); } catch (e) {} }); };
  });
  assistRegister('ribbon', KB);
})();
