// Echo Dose Response: from an Echo picklist and a plate reader to a DC50 for every compound — and a planner for the Echo.
(function(){
  var analysisOn = function(){ var pa = document.getElementById('panel-analysis'); if (pa && !pa.classList.contains('active')) switchPanel('analysis', document.querySelectorAll('.outer-tab')[0]); };
  var setupOpen = function(){ var m = document.getElementById('setup-modal'); return !!(m && !m.classList.contains('hidden') && getComputedStyle(m).display !== 'none'); };
  var closeSetup = function(){ if (setupOpen()) closeSetupModal(); };
  var tabGo = function(id){ return function(){ analysisOn(); closeSetup(); var t = document.getElementById('tabbtn-' + id); if (t) t.click(); }; };
  var setupGo = function(sub){ return function(){ analysisOn(); if (!setupOpen()) openSetupModal(); switchSetupTab(sub); }; };
  var tabSel = function(id){ return '#tabbtn-' + id; };
  var withText = function(root, tag, re){ return function(){ return [].slice.call(document.querySelectorAll(root + ' ' + tag)).filter(function(e){ return re.test(e.textContent); })[0]; }; };
  var MISS = 'This fills in once an analysis has been run.';
  tourRegister({
    id: 'echo', name: 'Echo Dose Response',
    blurb: 'Echo Dose Response fits a 4-parameter curve to every compound of a plate-reader screen dosed with a Labcyte Echo. Drop the Echo transfer file and the reader files, say where the controls are, and it gives you **DC50, Dmax and a quality flag** for each — with the curves, the plates and every export. A **Gradient Planner** designs the dose series for the Echo.',
    where: function(){
      var g = document.getElementById('panel-gradient'); if (g && g.classList.contains('active')) return 'gradient';
      if (setupOpen()) { var a = document.querySelector('.setup-stab.active'); return 'setup-' + (a ? a.getAttribute('data-tab') : 'files'); }
      var t = document.querySelector('#panel-analysis .tab.active'); return t ? t.id.replace('tabbtn-', '') : null;
    },
    data: { label: 'Load the example and analyse it',
      has: function(){ var n = document.getElementById('rc'); return !!(n && +n.textContent > 0); },
      can: function(){ return !(echoFiles && echoFiles.length) && !Object.keys(readerFiles || {}).length; },
      load: function(){ analysisOn(); if (!setupOpen()) openSetupModal(); switchSetupTab('files'); loadTestData(); setTimeout(function(){ try { runPipeline(); } catch (e) {} }, 1800); }, wait: 25000 },
    intro: [{ t: 'Welcome to Echo Dose Response',
      b: 'Files in, **a DC50 for every compound** out: Setup reads the Echo transfer file and the reader files, a 4-parameter curve is fitted to each compound, and the tabs show the numbers, the curves, the plates and the exports. About a minute; **Esc** leaves it at any point.',
      nodata: 'The results tabs need an analysis to show anything. The button loads the bundled example (one transfer file, six reader plates) and runs it — only if you press it.' }],
    outro: [{ t: 'Come back any time', sel: tabSel('guide'), place: 'bottom', go: tabGo('guide'),
      b: 'The **Guide** tab has all of this in writing, plus Properties, Console, Protocol and Source Plate — each with its own tour — the words used, and what to do when a number looks wrong.' }],
    quick: [
      'Open **Setup** (it opens by itself the first time). On **Files**, drop the Echo transfer file and one reader file per plate — or **Load test data** to look around.',
      'On **Assay**, name the run, say which wells are the vehicle controls (`B12-O12`) and how plates are grouped.',
      'Look at **Review** — it says how many curves will be fitted and what is wrong — then press **Run Analysis**.',
      'Read **Results**; open **Curves** to see and edit the fits; use **Plots** and **Plate** to look for patterns and plate problems.',
      'Take the numbers out with the buttons on Results — inside dHUB, **Send to Labbook** and **Send to Hit Finder** carry them on.'],
    tabs: [
      { id: 'setup-files', label: 'Setup › Files', tag: 'Setup', sel: '.setup-stab[data-tab="files"]', go: setupGo('files'), head: false,
        lead: 'Where the data comes in. Setup opens by itself while there is nothing to look at, and comes back any time with the **Setup** button.',
        do: ['Drop the **Echo transfer CSV** (or choose it). Several files are fine.',
          'Drop the **PHERAstar** XLS/XLSX files — **one per plate**, each named exactly like the plate barcode in the Echo file.',
          'Optionally add a **SMILES** CSV for structures and properties.',
          '**Open project** / **Save project** keep a whole setup — files, settings and what you left out — in one `.echo.json`.'],
        ref: [['Echo CSV', 'Needs **Sample ID**, **Destination Plate Barcode**, **Destination Well** and **Destination Concentration**. The unit is read from **Destination Concentration Units** (M if absent). Comma, semicolon and tab files all work. A transfer whose **Transfer Status** is not OK never reached the plate and is left out.'],
          ['PHERAstar XLS / XLSX', 'The lettered grid is found automatically (or give its A01 cell on Assay). A cell that is not a number — OVRFLW, blank — is left unread; it is never counted as 0 %, and the Console says how many.'],
          ['SMILES CSV', 'Two columns, **Sample ID** and **SMILES**. Needs the chemistry toolkit (RDKit), fetched from the internet the first time — offline, only structures are unavailable.'],
          ['Load test data', 'A bundled example: one Echo CSV and six plates. It is only used when you press it.']],
        watch: [{ k: 'tip', t: 'A file name that does not match any barcode is the usual reason a plate has no data. **Review** names the plates that have no reader file.' }],
        steps: [
          { sel: '#setup-pane-files', t: 'Two kinds of file', place: 'right',
            b: 'The **Echo transfer file** says what went into every well; the **PHERAstar files** — one per plate, named like its barcode — say what the wells read. Drop them here, or press **Load test data** to look around.' }] },

      { id: 'setup-assay', label: 'Setup › Assay', tag: 'Setup', sel: '.setup-stab[data-tab="assay"]', go: setupGo('assay'), head: false,
        lead: 'What this run is, and which wells are the 100 % reference. The two settings that decide every number: the control wells and how plates are grouped.',
        do: ['Give the run an **Assay ID** — a date or experiment code. A name must be given; an analysis with the same name in History is the next version of the same analysis.',
          'Choose the **Assay type** (HiBiT degradation, CellTiter-Glo viability, displacement, gain of signal) and, if you like, say what the screen is (**Role**, **Target**, **Cells**, **Time**) — Hit Finder reads it.',
          'Type the **control wells** — `B12-O12`, a rectangle like `B22:O23`, single wells, or any mix — or press **⊞ Grid** and paint them.',
          'Choose **Group plates by**: the target or cell line a curve is compared within. The preview under it lists the groups found.'],
        ref: [['Control wells', 'The vehicle-only wells: each plate is normalised to the mean of these. They cannot be blank — name them, or tick **No normalisation**.'],
          ['Group plates by', 'Read from the plate barcode (the reader file name): the text before the first “-”, before the last “-”, the whole name, or **My own table** (one barcode = group per line, `*` matches any text).'],
          ['Smart DMSO control', 'Instead of the plain mean, learns the reference from each plate’s own controls: a plainly wrong control is left out and row, odd/even-row and left-to-right effects are corrected only where the data show they are real. Off, the numbers are exactly the plain plate mean.'],
          ['PHERAstar data location', 'The A01 cell of the lettered grid, only if it is not found automatically.'],
          ['Multiple assay types', 'Analyse HiBiT and viability plates of one transfer file together, with a panel each.']],
        watch: [{ k: 'warn', t: 'With neither control wells nor **No normalisation**, the analysis stops and says so — it never fits raw counts as if they were percentages.' }],
        steps: [
          { deep: true, sel: '#p-assay', t: 'Name the run', place: 'right',
            b: 'The **Assay ID** names the exports and the History entry. Run it again with the same name and it becomes the next **version** of one analysis, not a copy.' },
          { sel: '#p-ctrl', t: 'Where the controls are', place: 'right',
            b: 'The vehicle-only wells every plate is scaled to: `B12-O12`, a rectangle `B22:O23`, or a mix. **⊞ Grid** lets you paint them. This is the single setting that moves every number.' },
          { deep: true, sel: '#p-group-mode', t: 'Group plates by', place: 'right',
            b: 'The group is what a curve is compared within and what colours its badge — usually the target. It is read from the plate barcode; the preview lists what was found.' }] },

      { id: 'setup-analysis', label: 'Setup › Analysis', tag: 'Setup', sel: '.setup-stab[data-tab="analysis"]', go: setupGo('analysis'), head: false, full: false,
        lead: 'How a curve is fitted and when it is flagged. The defaults suit a HiBiT degradation screen; change one at a time and look at the Review.',
        do: ['**Echo header rows to skip** — metadata rows above the column header in the Echo CSV (8 for standard Echo Plate Reformat output).',
          'Set the **flags**: hook effect threshold, minimum R², maximum replicate SD. Each can be switched off with its box.',
          'Set the **constraints**: top (usually 100 %), a fixed or free bottom and Hill slope, and a floor on the bottom.'],
        ref: [['Hook effect threshold (Δ%)', 'A hook is signal that rises again at the highest doses. If the mean at the top dose exceeds the mean two steps lower by more than this, that point is flagged (orange ×) and left out of the fit. Default 10. Right-click the curve in Curves to put it back.'],
          ['Min R² for fit', 'A curve below this is still reported, but flagged. Default 0.8.'],
          ['Max replicate SD', 'Largest SD (% of control) tolerated at any concentration before the curve is flagged as noisy. Default 25.'],
          ['Top constrain · Fix bottom · Fix Hill', 'Constrain the 4-parameter fit. A top ≤ 0, a Hill slope ≤ 0 or a fixed bottom above the top stops the run with the reason, instead of flagging every curve.'],
          ['An emptied number', 'Falls back to its default, and the Console says so.']],
        steps: [
          { sel: '#hook-effect-field', t: 'The hook effect', place: 'bottom',
            b: 'Signal that comes back at the highest doses is flagged and left out of the fit, so one hooking point cannot drag the curve. Raise the threshold to be more tolerant.' }] },

      { id: 'setup-output', label: 'Setup › Output', tag: 'Setup', sel: '.setup-stab[data-tab="output"]', go: setupGo('output'), head: false, full: false,
        lead: 'What the exports contain and how a flat curve is reported.',
        do: ['Leave **Flat curves** on to report a curve that barely moves as **n.d.** — it has no midpoint.',
          'Tick the columns you want in the CSV and the results table: DC50, Dmax, pDC50, absolute DC50, LogDC50, Hill, R², flag and reason, top, bottom, confidence intervals, the normalisation audit.'],
        ref: [['n.d.', 'With Flat curves on (the default), a flat curve’s potency, logs, Hill and limits read n.d. in the table, exports, Properties and Labbook, and it is left off potency plots; Dmax and R² stay. The fitted number is still in the data — hover the cell.'],
          ['Normalisation audit', 'Whether a curve’s potency changes with how it was normalised — see Results.']],
        steps: [
          { sel: '#p-nd', t: 'Flat curves', place: 'bottom',
            b: 'A curve that barely moves has no real midpoint. With this on, its potency reads **n.d.** everywhere instead of a number nobody measured.' }] },

      { id: 'setup-review', label: 'Setup › Review', tag: 'Setup', sel: '.setup-stab[data-tab="review"]', go: setupGo('review'), head: false,
        lead: 'Before anything is fitted: the files are read with the settings as they stand, and it says what is about to happen and what is wrong.',
        do: ['Read the first line: **how many curves** will be fitted, in how many groups.',
          'Every problem has a button that takes you to the setting: plates with no reader file, controls sitting on compound wells, curves with too few readings, plates whose controls are unread or noisy.',
          'Press **Run Analysis**. It updates as you change anything.'],
        ref: [['Plates', 'One line per plate: reader file, group (editable), wells dosed, controls read, control mean ± CV.']],
        steps: [
          { sel: '#rv-body', t: 'Check before you fit', place: 'left',
            b: 'It reads the files with the current settings — nothing is fitted yet — and says how many curves it will make and what is wrong, each problem with a button to the setting. Then **Run Analysis**.',
            miss: 'Once files are loaded, this says how many curves will be fitted and lists what to fix first.' }] },

      { id: 'results', label: 'Results', sel: tabSel('results'), go: tabGo('results'), needs: 'data',
        lead: 'One row for every curve: potency, effect, fit quality and a flag for anything that deserves a second look. Everything you export starts here.',
        do: ['Read the three tiles: compounds, fits (compound × group) and how many are flagged.',
          'Click a column header to sort (ascending → descending → reset). Hover a cell for the fitted number behind an n.d.',
          'Open **Normalisation** under the tiles to see how every curve was normalised and whether the method changes the answer.',
          'Take the numbers out with the buttons above the table, then open **Curves** to look at the ones you doubt.'],
        ref: [['DC50 (nM)', 'The concentration giving half of the maximal effect — the EC50 of the 4-parameter fit, in nM.'],
          ['Dmax (%)', 'The span of the fitted curve: **top − bottom**. With the top fixed at 100 % it is 100 % − bottom; with a free top it follows where the curve actually starts.'],
          ['LogDC50 · pDC50', 'log₁₀ of the midpoint in M, and its negative — easy to compare across orders of magnitude.'],
          ['Hill', 'Steepness. Near 1 is typical; above 2 can mean cooperativity or an artefact.'],
          ['R²', 'Fit quality. Below your minimum it is flagged.'],
          ['Flag · Reason', 'Why a curve deserves a look: low R², noisy replicates, a hook, a midpoint beyond the doses tested (`EC50>range`, `EC50<range`), no effect.'],
          ['95 % CI', 'The confidence interval of the DC50.'],
          ['Normalisation · vs plain mean', 'How the 100 % reference of the curve’s plates was set, and whether the potency changes if the plain plate mean is used instead — **Same** or **Differs**.'],
          ['Buttons', '**Copy TSV**, **Results XLSX**, **Screen CSV** (the lossless table Hit Finder reads), **Raw Data CSV**, **Generate curve PDFs** (one PDF per group), **Send to Labbook**, and inside dHUB **Send to Hit Finder**, **Compare…** (two analyses from History).']],
        watch: [{ k: 'tip', t: 'A curve flagged *No effect* barely moves — its potency is n.d. and it is left off potency plots. A midpoint beyond the doses tested is a bound, not a value.' }],
        steps: [
          { sel: '#results-panel .results-tbl-scroll', t: 'One row per curve', place: 'top', miss: MISS,
            b: 'DC50, Dmax, Hill, R², the flag and why, the confidence interval and how the curve was normalised. **Click a header to sort**; hover an n.d. for the number behind it.' },
          { deep: true, sel: '#results-panel .res-tiles', t: 'At a glance', place: 'bottom', miss: MISS,
            b: 'Compounds, fits (a compound against each target is a fit) and how many are flagged.' },
          { deep: true, sel: '#results-panel details', t: 'How it was normalised', place: 'bottom', miss: MISS,
            b: 'Every curve is also fitted with the plain plate mean as a check. **Same** means the method does not matter for it; **Differs** is worth a look before you quote the number.' },
          { deep: true, sel: withText('#results-panel', 'button', /Copy TSV/), t: 'Take the numbers out', place: 'bottom', miss: MISS,
            b: 'Copy the table, export to Excel or CSV, make a PDF per group, or send the potencies to **Labbook** (they land on the experiment’s Results tab); inside dHUB the whole screen can go to **Hit Finder**.' }] },

      { id: 'curves', label: 'Curves', sel: tabSel('curves'), go: tabGo('curves'), needs: 'data',
        lead: 'Each compound’s fit, with its replicates. This is where you judge a curve and fix it: leave out a point, put a hook back, resolve a flag — the fit is redone the way the analysis did it.',
        do: ['Pick a **group** and a **compound**, or step with ← → or the scroll wheel.',
          '**Right-click** a point: the menu lists every replicate at that concentration with its reading — **leave out one**, or **all of them**, and point at a row to see which dot it is. A left-out replicate becomes a grey ×; right-click it to put it back. A toast says what the potency did, and `⌘Z` undoes it.',
          'Switch to **Compare** to overlay several compounds, and **Fix Y** to put every curve on the same scale (−15 to 120 % of control).',
          '**Download** a PNG or PDF — the figure is exactly what is on screen, axes and zoom included.'],
        ref: [['Single · Compare', 'One compound with full stats, or several overlaid. A compared curve is a compound × group; the list is sortable by DC₅₀ or Dmax.'],
          ['Right-click', 'On any point (replicate, mean dot or ×): one menu for that concentration — **Exclude** each replicate by its reading, **Exclude all N replicates**, **Put back**. On an orange hook ×: **Include the hook concentrations in the fit**. A little off a point it picks the nearest one and says so. On the Flag in the stats bar: **Resolve flag**.'],
          ['Style · Ref', '**Style** sets colours and weights for the figure; **Ref** pins a reference curve to compare the others against.'],
          ['Zoom', 'Double-click the plot, or press **⊙ Zoom**, to reset the view.'],
          ['Undo', '`⌘Z` / `Ctrl+Z` undoes a curve edit, `⌘⇧Z` / `Ctrl+Y` redoes it — here and on the Plate tab.']],
        watch: [{ k: 'tip', t: 'An edit refits with the analysis’s own settings, so the flags and the confidence interval follow it. Results and Plots update when you leave the tab.' }],
        steps: [
          { sel: '#cv-canvas', t: 'The fit, and your edits', place: 'top', miss: MISS,
            b: 'Mean ± SD with the 4-parameter line and the DC50. **Right-click a point** to leave out one replicate or the whole concentration; the curve is refitted at once and a grey × can be put back the same way. `⌘Z` undoes it.' },
          { deep: true, sel: '#cv-mode-compare', t: 'Compare curves', place: 'bottom', miss: MISS,
            b: 'Overlay several compounds — for the same compound against different targets, or two analogues. **Download** exports the overlay, or each curve on its own, on the axes you see.' },
          { deep: true, sel: '#cv-stats', t: 'The numbers under the curve', place: 'top', miss: MISS,
            b: 'DC50, Dmax, pDC50, Hill, R² and the flag for this curve. Right-click the Flag to **resolve** it once you have looked.' }] },

      { id: 'scatter', label: 'Plots', sel: tabSel('scatter'), go: tabGo('scatter'), needs: 'data',
        lead: 'The whole screen as pictures: any fitted parameter against another, the distribution per group, or one target against another to find selective compounds.',
        do: ['Choose **Scatter**, **Box plot** or **Selectivity** at the top.',
          'On a scatter, pick the **X** and **Y** parameter (default LogDC₅₀ against Dmax — potency against efficacy) and a **Unit**.',
          'Type in **Search** to light up matching compounds; **Names** labels the points; **Group** draws a hull around each group.',
          '**□ Select** a rectangle of points and **Copy IDs**; **PNG** and **CSV (filtered)** take what you see.'],
        ref: [['Box plot', 'One box per group for DC50, Dmax, LogDC50, Hill or R²; a group filter and **Flagged** to include or leave out curves that failed quality.'],
          ['Selectivity', 'Target X against target Y for the same compound. Diagonal bands at ±N log units — green selective for Y, red for X, grey within the threshold; the fold selectivity is 10^|y−x|. **Only shared compounds** hides compounds present in one group.'],
          ['Curve on hover', 'Hover a point for a small curve of that compound.'],
          ['Undo / redo', '`Ctrl+Z` / `Ctrl+Y` step through your filter changes.']],
        steps: [
          { sel: '#sc-section', t: 'Any parameter against any other', place: 'bottom', miss: MISS,
            b: 'Potency against effect by default. Change the axes or the unit, **search** a compound to light it up, and **drag a rectangle** to pick compounds. Box plot and Selectivity are one click away at the top.' }] },

      { id: 'plate', label: 'Plate', sel: tabSel('plate'), go: tabGo('plate'), needs: 'data',
        lead: 'Every plate as a map — to see what the readings and the fits look like where they came from, and to catch a plate problem before it becomes a potency.',
        do: ['**Maps**: choose **Colour by** — raw luminescence, normalised %, compound, group, fitted DC50 or Dmax, Echo transfers — and the **Scale** (per plate, group or all plates). **Clip outliers** sets the range from the 2nd–98th percentile.',
          'Type in **Find** to dim everything but a compound, group, plate or well. **Right-click** (or Shift-click) a well to leave it out of its curve — or put it back.',
          '**Plate QC**: Z′, signal to background, control CV, drift and edge effect for each plate.',
          '**Compare**: one plate against another, matched by compound and dose (or by well).'],
        ref: [['Plate QC', 'From the raw control wells: **Z′** (when 0 % wells are set), S/B, control CV, drift down the rows and across the columns, edge effect, and the reference the normalisation used. The verdict uses the control CV when Z′ cannot be computed, and says so.'],
          ['Compare', 'Scatter with the identity line, r, median ratio and the share within tolerance, plus the ten worst pairs. Same-well matching adds a difference map.'],
          ['Echo transfers', 'Colours wells by what the Echo did; a failed transfer is drawn crossed in red.'],
          ['Wells CSV', 'Every well — or only the ones your search matches — with raw, normalised signal, role, whether it is left out of its fit, and the Echo status.'],
          ['Send to Labbook', 'Attaches the QC table and each plate as a picture to an experiment.']],
        steps: [
          { sel: '#plate-body', t: 'Every plate as a map', place: 'top', miss: MISS,
            b: '**Colour by** raw luminescence, normalised %, compound, group, fitted potency or Echo transfers. **Find** dims all but one compound. **Right-click a well** to leave it out of its curve.' },
          { deep: true, sel: '#plate-panel .plate-view', t: 'Maps, QC, Compare', place: 'bottom', miss: MISS,
            b: '**Plate QC** gives Z′, S/B, control CV, drift and edge effect for every plate; **Compare** sets one plate against another, matched by compound and dose.' }] },

      { id: 'props', label: 'Properties', sel: tabSel('props'), go: tabGo('props'), full: false, tag: 'needs a SMILES file',
        lead: 'Structures and computed properties for every compound, once a SMILES file has been added on Setup › Files.',
        do: ['Add a **SMILES CSV** (Sample ID and SMILES) on Setup › Files and run the analysis.',
          'Click a column header to sort. A compound fitted against several targets lists each target’s value.',
          'Click a SMILES cell to copy the whole string.'],
        ref: [['Ro5', 'Lipinski rule of five: flags MW ≥ 500, logP ≥ 5, more than 10 H-bond acceptors or more than 5 donors, and counts violations.'],
          ['MW', 'The average molecular weight (not the monoisotopic mass).']],
        watch: [{ k: 'warn', t: 'Structures and properties use RDKit, fetched from the internet the first time. Offline, this tab says so and everything else still works.' }],
        steps: [{ sel: '#props-panel', t: 'Structures and properties', place: 'top', miss: 'Add a SMILES file on Setup › Files and run the analysis to fill this tab.',
          b: 'One row per compound with its structure, molecular weight, logP, polar surface area and rule-of-five violations. Sort by any column.' }] },

      { id: 'log', label: 'Console', sel: tabSel('log'), go: tabGo('log'), full: false,
        lead: 'Everything the analysis did, line by line with the time: files read, wells left unread, control wells left out, settings that fell back to a default, warnings. Open it when a number surprises you.',
        do: ['Read from the top: files, then each plate, then the fits.',
          'Look for lines about **unread wells**, **left out** control wells, **failed transfers** and **settings that fell back**.'],
        steps: [{ sel: '#log-panel', t: 'What the analysis did', place: 'top',
          b: 'A line for every file read, every plate and every decision the analysis made for you — leaving out a control well, falling back to a default — with the time.' }] },

      { id: 'history', label: 'History', sel: tabSel('history'), go: tabGo('history'),
        lead: 'Every analysis you run is kept, by name. Run the same Assay ID again and it becomes the next version of the same analysis; open an old one, re-analyse it with one setting changed, or compare two versions.',
        do: ['Click an analysis to see its **versions**; **Load** shows one, **Re-analyse…** puts its input files and settings back in Setup.',
          'Choose two versions and press **Compare**: each DC50 as a fold change, how many stayed within 1.5×, 2×, 3× or 10×, newly flagged and no-longer-flagged curves, and a log–log scatter.',
          '**Pin** ★ an analysis or version to keep it when space runs short.'],
        ref: [['One entry per name', 'The Assay ID is the identity: any run called the same is a new version of one analysis, whatever its files. A blank or default name is “unnamed”; rename it with the pencil, and renaming to an existing name merges them.'],
          ['Versions', 'The same settings and the same outcome add nothing (they count as a re-run); a different setting is the next version and says what changed (“Min R² 0.8 → 0.9”). Editing curves of a loaded analysis updates that version.'],
          ['Where it lives', 'In this browser’s IndexedDB. Inside dHUB it is also backed up and synced between your devices — merged, never replaced. Input files stay on the device (up to ~80 MB).']],
        steps: [
          { sel: '#history-panel', t: 'Analyses, by name', place: 'top',
            b: 'One line per analysis, with its versions underneath. **Re-analyse…** brings the files and settings back to Setup; **Compare** sets two versions side by side, compound by compound.',
            miss: 'Every analysis you run appears here.' }] },

      { id: 'protocol', label: 'Protocol', sel: tabSel('protocol'), go: tabGo('protocol'), full: false,
        lead: 'The settings of this analysis written out as a sheet — assay, grouping, normalisation, thresholds and constraints — ready to copy into a Methods section.',
        do: ['Run an analysis; the sheet fills in.', 'Copy the lines you need.'],
        steps: [{ sel: '#protocol-panel', t: 'The analysis as a protocol', place: 'top', miss: MISS,
          b: 'Assay, plate grouping, the normalisation and how many control wells were left out, hook threshold, minimum R², maximum SD, constraints — exactly what this run used.' }] },

      { id: 'survey', label: 'Source Plate', sel: tabSel('survey'), go: tabGo('survey'), full: false,
        lead: 'What is left in each well of the Echo source plate, from an Echo survey file — and which wells fall short of what a run needs.',
        do: ['Drop the **Echo survey CSV** (well volumes in nL).', 'Read the plate: low wells stand out; transfers that failed or came from other plates are not counted.'],
        steps: [{ sel: '#survey-panel', t: 'Survey of the source plate', place: 'top',
          b: 'Drop an Echo survey file to see the volume left in every well, and where a run would run short.' }] },

      { id: 'gradient', label: 'Gradient Planner', sel: function(){ return document.querySelectorAll('.outer-tab')[1]; }, go: function(){ closeSetup(); switchPanel('gradient', document.querySelectorAll('.outer-tab')[1]); },
        lead: 'Plans the dose series for the Echo: how many nanolitres of which stock go into each well, in 2.5 nL drops. It uses a single source plate and adds intermediate dilutions only when the source cannot reach a point.',
        do: ['**1 Assay** — pick a preset (HiBiT, FP, TR-FRET, AlphaScreen, D2B), the assay volume and the maximum DMSO.',
          '**2 Dose series** — top concentration, number of points and dilution factor. The strip shows the plan against the rings the Echo can really dispense.',
          '**3 Source & intermediates** — your stock concentration. The planner uses Source alone when that reaches every point and adds intermediates only when it cannot; **✦ Suggest** chooses them, **+ Add** is for doing it by hand.',
          '**4 Transfer plan** — for every point, the stock chosen, the volume and the concentration that results. Type a volume to override it.',
          '**5 Intermediate plate** — how much of each stock to prepare for your run size, and the pre-fill.',
          '**Export CSV** writes the transfer plan the Echo method is set up from; **Copy summary** copies a text version.'],
        ref: [['Status', '✓ within 0.2 % of the plan, ~ within 5 %, “N % off” in red when a point cannot be reached closely.'],
          ['Stock choice', 'For each point, the stock that lands nearest the plan; a tie goes to the more concentrated stock. Every well is backfilled to the same DMSO total, so a smaller transfer saves nothing.'],
          ['Intermediates', 'Always made in one step from Source, never from another intermediate. Editing them by hand takes them out of automatic mode; **✦ Suggest** hands them back.'],
          ['Stock volumes', 'For each compound, what each well holds, how much the run draws and what is spare — red and “short by” when it will not be enough.']],
        watch: [{ k: 'tip', t: 'Typing into a box never loses your place: the planner re-plans after a short pause, and a half-typed number such as `0.` is left alone.' }],
        steps: [
          { deep: true, sel: '#eg-preset', t: '1 · The assay', place: 'right',
            b: 'Start from a **preset** — HiBiT, FP, TR-FRET, AlphaScreen, D2B — or set the assay volume and the maximum DMSO yourself. Every well is backfilled to the same DMSO total.' },
          { deep: true, sel: '#eg-ladder', t: '2 · The dose series', place: 'bottom',
            b: 'The top concentration, the number of points and the dilution factor. The strip shows your plan against the rings the Echo can really dispense.' },
          { deep: true, sel: '#eg-stocks-container', t: '3 · Source and intermediates', place: 'left',
            b: 'Your stock goes in **Source**. Intermediates appear only when Source cannot reach a point — press **✦ Suggest** to let the planner choose them; they are always made from Source.' },
          { sel: '#eg-table', t: '4 · The transfer plan', place: 'top', miss: 'The plan appears once the assay, the series and the source are filled in.',
            b: 'For every point: which stock, how many nL, and the concentration that results. ✓ is within 0.2 % of the plan, “N % off” in red is not reachable. **Export CSV** is what the Echo method is set up from.' },
          { deep: true, sel: '#eg-bf-card', t: '5 · The intermediate plate', place: 'top', miss: 'This appears when the plan uses intermediates.',
            b: 'How much of each intermediate to prepare for your run, the pre-fill, and what each source well will have left — red when it will not be enough.' }] }
    ],
    words: [
      ['DC50 · EC50 · IC50', 'The concentration giving half of the maximal effect. Echo Dose Response reports it as DC50 for degradation and IC50 or EC50 for other assays.'],
      ['Dmax', 'The span of the curve (top − bottom): how much of the signal the compound removes at most.'],
      ['4PL', 'The 4-parameter logistic curve: bottom, top, midpoint and Hill slope.'],
      ['Hook', 'Signal that comes back at the highest concentrations. Those points are left out of the fit.'],
      ['Flag', 'The fitter’s opinion that a curve needs a look. Only **your** exclusions change what is reported; a flag never deletes a number.'],
      ['n.d.', 'No midpoint: the curve barely moves.'],
      ['Bound', 'A midpoint beyond the doses tested (`EC50>range` or `EC50<range`) — a limit, not a value.'],
      ['Vehicle · control', 'The wells with solvent only: the 100 % reference.'],
      ['Z′ · S/B · CV', 'Plate quality: separation between the controls, signal to background and the scatter of the controls.'],
      ['Group', 'What a curve is compared within — usually the target — read from the plate barcode.']],
    faq: [
      ['A plate has no data', 'Its reader file name does not match the plate barcode in the Echo CSV. **Setup › Review** names plates with no reader file; check the exact spelling, ignoring the extension.'],
      ['Every curve is flagged “EC50>range”', 'The midpoint is beyond the highest dose — the compounds are weaker than the series reaches, or the concentrations in the transfer file are in a different unit. Check the **Destination Concentration Units** column.'],
      ['A curve looks wrong', 'Open it in **Curves**: right-click an odd replicate to leave it out, or put back a hook. The fit is redone with the analysis’s own settings.'],
      ['The numbers moved when I switched Smart DMSO control', 'That is what it is for. Results → **Normalisation** says, for each curve, whether the method changes the potency.'],
      ['“Run Analysis” stops with a message', 'A setting cannot be right: an empty control range, a top constraint ≤ 0, a Hill slope ≤ 0 or a fixed bottom above the top. The message names it.'],
      ['PDF export or structures do not work', 'jsPDF and RDKit are fetched from the internet the first time. Offline, those two features are unavailable — everything else works.'],
      ['Where are my past analyses?', '**History** keeps one entry per Assay ID. Inside dHUB it is backed up to your account; otherwise it lives only in this browser.']],
    keys: [['← →  or the wheel', 'Curves: previous / next compound'], ['Double-click', 'Curves: reset the zoom'], ['⌘Z / Ctrl+Z  ·  ⌘⇧Z / Ctrl+Y', 'Undo / redo curve edits and Plots filters'],
      ['[  and  ]', 'Step through the tabs'], ['/', 'Go to the search of the view you are on'], ['← → Home End', 'Move along the tab list'], ['Esc', 'Close Setup']]
  });
})();
