// Hit Finder: from many analysed screens to a short list of hits.
(function(){
  var tab = function(id){ return '#hf-tabs .tab[data-tab="' + id + '"]'; };
  var go = function(id){ return function(){ hfTab(id); }; };
  var MISS_STRUCT = 'This appears once a structures file is added on this tab.';
  tourRegister({
    id: 'hitfinder', name: 'Hit Finder',
    blurb: 'Hit Finder turns the screens you analysed in Echo Dose Response into a short list of hits. **You say what a hit is** — potency, effect, selectivity, viability window — and it shows who passes, who almost does, and who cannot be judged yet.',
    where: function(){ return HF.ui.tab; },
    fresh: function(){ return !(HF.screens && HF.screens.size) && !HF.resumeOffer; },
    data: { label: 'Load the example screen', has: function(){ return !!(HF.screens && HF.screens.size); }, load: function(){ loadHitFinderTestData(); } },
    intro: [{ t: 'Welcome to Hit Finder',
      b: 'It turns the screens you analysed in Echo Dose Response into a short list of hits. **You say what a hit is** — potency, effect, selectivity, viability — and it shows who passes, who almost does, and who cannot be judged yet. About a minute; **Esc** leaves it at any point.',
      nodata: 'Most tabs need a screen to show anything: press the button to load a made-up one — only if you want to.' }],
    outro: [{ t: 'Come back any time', sel: tab('guide'), place: 'bottom', go: go('guide'),
      b: 'The **Guide** tab keeps all of this in writing: a tour for each tab, the words used, and what to do when something looks wrong.' }],
    quick: [
      'On **Screens**, add the screens Echo analysed — or press **Example screen** to look around first.',
      'Check the **slot** of each group: what it is for (primary, viability, counter-screen…).',
      'On **Criteria**, start from a preset and change the numbers until the sentences say what you mean by a hit.',
      'On **Hits**, read the funnel to see where compounds fell out, then open a compound to see why.',
      'On **Export**, take the workbook, a one-page summary or a cherry-pick list to re-test.'],
    tabs: [
      { id: 'screens', label: 'Screens', sel: tab('screens'), go: go('screens'),
        lead: 'Where the data comes in. Add the screens Echo Dose Response analysed, and say what each group is for. Everything stays in this browser.',
        do: ['Press **From Echo** to pick analyses saved in Echo Dose Response’s History, or **Open files…** for a Screen CSV, an Excel sheet, older Echo or Lumina results, or a saved project. Files can also be dropped anywhere on the page.',
          'Check the **Slot** of each group: Primary (where hits come from), Anti-target, Viability, Counter-screen, Rescue or Control. Criteria speak in slots, never in file names, so a new run of the same experiment drops into the same place.',
          'Correct the **Role**, **Target**, **Cells** and **Time** if they were read wrongly; ✕ removes a screen.',
          'Read the **Compounds** card: who is missing from which screen, and names that look like the same compound. Merge only the ones you recognise.'],
        ref: [['Role', 'What kind of experiment the screen is: degradation, viability, counter-screen, rescue, binding or other.'],
          ['Slot', 'What a group is for in the judgement. A **guess** pill means the app worked it out from the screen’s role and size — **Looks right** confirms them all.'],
          ['Curves / Not fitted', 'How many dose–response curves were read, and how many compounds Echo could not fit.'],
          ['Several versions', 'If a few versions of one Echo analysis are loaded, only the newest counts — they are re-analyses of the same wells. Two groups of the same slot inside one run are technical replicates and are averaged first; separate runs combine as independent runs (n).']],
        watch: [{ k: 'tip', t: 'Your session is autosaved in this browser and offered back when you return. **Save project** on the Export tab makes a file you can move.' },
          { k: 'warn', t: 'Names that differ by more than case, spaces, `-` or `_` are different compounds. The app **suggests** merges (a leading zero, a salt suffix, a one-letter typo) but never makes them for you.' }],
        steps: [
          { sel: ['#pane-screens .src-bar', '#pane-screens .es-a'], t: 'Three ways in', place: 'bottom',
            b: '**From Echo** reads the analyses saved in Echo Dose Response, **Open files…** takes a Screen CSV, an Excel sheet or a saved project, and **Example screen** loads a made-up one. Dropping files anywhere on the page works too.' },
          { sel: '#hf-slots', needs: 'data', t: 'What each group is for', place: 'top',
            b: 'Every group gets a **slot**: Primary, Anti-target, Viability, Counter-screen, Rescue or Control. Criteria are written in slots, so the next run of the same experiment drops straight in. A **guess** pill means the app worked it out; **Looks right** confirms.',
            miss: 'Once a screen is loaded, this table lists every screen and group with what each is for.' },
          { sel: '#hf-compounds', needs: 'data', deep: true, t: 'Who is where', place: 'top',
            b: 'Which compounds appear in which screens. A primary compound with no viability result stays **Unverified** — never a hit. Names that look alike are suggested as the same compound, and merged only when you say so.',
            miss: 'Once screens are loaded, this card counts compounds per slot and flags names that may be the same compound.' }] },

      { id: 'criteria', label: 'Criteria', sel: tab('criteria'), go: go('criteria'), needs: 'data',
        lead: 'Say what a hit is. Each criterion is a gate on one slot — potency in the primary screen, effect, viability window, selectivity — with a pass edge, a borderline edge, and what to do when the number cannot be read.',
        do: ['Pick a **preset** in **Start from**: a strict degrader screen, a lenient first pass… It sets every gate at once.',
          'Read the sentence under each criterion — it says in words what the numbers now mean — and move them. The counts and the histogram update as you type.',
          'Choose how it counts: **Gate** must pass, **Score** only ranks, **Advisory** is shown and never decides. Then what happens when the number cannot be read: **Unverified**, **Fail** or **Skip**.',
          '**Add a criterion…** brings in effect, selectivity, viability window, counter-screen window, rescue, hook window, fit quality, curve coverage and more. **Save as preset…** keeps your own set.'],
        ref: [['Borderline', 'Between the pass edge and the borderline edge. A compound inside it is not rejected — it is **Borderline**.'],
          ['Bounds', 'A potency of `> 10 µM` is a bound, not a number. It conclusively fails “DC50 ≤ 100 nM” and passes “≥ 1 µM”; it never enters a mean.'],
          ['Hook', 'A hook is not a defect. Dmax is the effect with the hook left out, and the **productive window** is how far above its DC50 the compound still works.'],
          ['Gate · Score · Advisory', 'Gate: must pass for a hit. Score: counts towards the ranking. Advisory: shown for information only.'],
          ['Unverified · Fail · Skip', 'What to do when a number is unreadable. A missing number is never a pass and never a zero — it is unknown.']],
        watch: [{ k: 'tip', t: 'Changing a number never re-draws the card under your pointer — only what depends on it is patched — so you can drag a histogram edge and watch the counts.' }],
        steps: [
          { sel: '#pane-criteria .crit-top .l', t: 'Start from a preset', place: 'bottom',
            b: 'A preset sets every gate at once. Change anything and it is yours; **Save as preset…** keeps it. **Add a criterion…** brings in effect, selectivity, viability window, counter-screen, hook window and more.',
            miss: 'The criteria need a loaded screen to read.' },
          { sel: '#crit-list .crit', t: 'One criterion, in words', place: 'bottom',
            b: 'A gate on one slot: “At most 100 nM; borderline up to 300 nM.” Between the edges a compound is **Borderline**. **Gate** must pass, **Score** only ranks, **Advisory** never decides — and the last box says what to do when the number cannot be read.' },
          { sel: '#crit-list .crit [id^="hist-"]', deep: true, t: 'See where your compounds fall', place: 'top',
            b: 'The histogram shows the whole screen against this criterion; the counts above it update as you move a number — pass, borderline, fail. **Drag its edges** to move them.' }] },

      { id: 'hits', label: 'Hits', sel: tab('hits'), go: go('hits'), needs: 'data',
        lead: 'The result: every compound sorted into Hit, Borderline, Unverified or Rejected, ranked, with the funnel that shows where the others fell out.',
        do: ['Read the **funnel**: each row is a gate, with how many compounds stay and how many drop there. Press a row to list only the compounds that stopped at it.',
          'Filter with the **tier** chips, search with `/`, and change **Rank by**.',
          'Click a compound to open its drawer: every gate with its number, the curves in each screen, any hook, and why it ended where it did. `j` / `k` step through the list.',
          'Make **your call** — Hit, Maybe or Reject (`h` `m` `x`) with a note. It is kept beside the tier and never changes it.'],
        ref: [['Hit', 'Passes every gate. A hit never stands on a gate that could not be read.'],
          ['Borderline', 'Inside a borderline edge, or a near miss.'],
          ['Unverified', 'A gate could not be read — for example no viability result. Never promoted to a hit.'],
          ['Rejected', 'Failed at least one gate; the drawer says which.'],
          ['Score', 'Keeps rising past the pass edge, so a 4 nM compound beats a 90 nM one that passes the same gate. The list is ranked by tier, then by the score the compound is **guaranteed** to have.'],
          ['Potency ×/÷', 'The spread between independent runs, as a fold factor — potencies are averaged in log space.']],
        watch: [{ k: 'tip', t: 'Near misses and compounds close to an edge are called out in the drawer — those are the ones worth a second look.' }],
        steps: [
          { sel: '#hf-funnel', t: 'The funnel', place: 'bottom',
            b: 'Each row is a gate, in order: how many compounds stay and how many drop there. **Press a row** to list only the compounds that stopped at it.' },
          { sel: '#pane-hits .tchips', deep: true, t: 'Four tiers', place: 'bottom',
            b: '**Hit** passes every gate. **Borderline** is inside an edge. **Unverified** has a gate that could not be read — never promoted to a hit. **Rejected** failed one. Search with `/`.' },
          { sel: '#hits-scroll', deep: true, t: 'The ranked list', place: 'top',
            b: 'Ranked by tier, then by a score that keeps rising past the pass edge. Potency carries its spread (×/÷), a `>` is a bound and never a number, and the last column says why a compound is where it is.' },
          { sel: '#hf-drawer.open .dr-bd', t: 'Open a compound', place: 'left',
            go: function(){ var l = HF.hitList || []; if (l.length) hfOpenDrawer(l[0]); },
            after: function(){ hfCloseDrawer(); },
            b: 'Every gate with its number, the curves in each screen, any hook, and **your call** — Hit, Maybe or Reject (`h` `m` `x`) with a note. Your call sits beside the tier and never changes it. `j` / `k` step through the list.' }] },

      { id: 'plots', label: 'Plots', sel: tab('plots'), go: go('plots'), needs: 'data',
        lead: 'Every gate as a picture, drawn from the same numbers as the table. Drag a rectangle on any plot and the same compounds light up in all of them.',
        do: ['Read **Potency and effect** first: potency across, effect up, with the corner your criteria call a hit shaded.',
          'Check the **productive window**, **selectivity**, **viability window** and **counter-screen window** — below the dashed line a compound is as potent there as in the primary screen.',
          'Drag a rectangle on one plot; the **Selection** chip on Hits then lists exactly those compounds.',
          'Take a plot away with **Table**, **SVG**, **PNG** or **CSV** on its header.'],
        ref: [['Marks', 'A ring is a flagged curve, an arrow a bound (the midpoint is beyond the doses tested), a diamond a curve with a hook.'],
          ['Shaded corner', 'What your criteria call a hit on that plot — it moves when you change a criterion.'],
          ['SVG / PNG', 'Drawn by the same function as the screen, on a white page with print weights.']],
        steps: [
          { sel: '#pl-dmax', t: 'Potency and effect', place: 'right',
            b: 'Each point is a compound in the primary screen — potency across, effect up. The shaded corner is what your criteria call a hit. A ring is a flagged curve, an arrow a bound, a diamond a hook. **Drag a rectangle** to pick compounds; they light up in every plot.' },
          { sel: '#pl-window', deep: true, t: 'Productive window', place: 'left',
            b: 'How far above its DC50 a compound still works before a hook. A wide window means a forgiving dose range for follow-up.' },
          { sel: '#pl-anti', deep: true, t: 'Selectivity and windows', place: 'right',
            b: 'Selectivity, viability and counter-screen windows follow one pattern: **below the dashed line** the compound is as potent there as in the primary screen — the wrong place to be.' },
          { sel: '#pl-dmax .btn', deep: true, t: 'Take it with you', place: 'bottom',
            b: '**Table**, **SVG**, **PNG** and **CSV** on every plot’s header. The picture is made by the same code as the screen, so it is the one you were looking at.' }] },

      { id: 'chem', label: 'Chemistry', sel: tab('chem'), go: go('chem'), needs: 'data', tag: 'optional',
        lead: 'Optional. Add a file of structures and this tab draws them, computes properties, grades the hits against drug-likeness rules, and shows the series, the activity cliffs and structural alerts.',
        do: ['Press **Add structures…** and choose a CSV, Excel or `.smi` file with a compound name and a SMILES (or load a results file that has a SMILES column). They are matched to compounds by name.',
          'Read **Drug-likeness**: how many hits pass each rule set. **Use as a gate** adds one to the criteria.',
          'Look at **the series** — groups of similar compounds, a map, closest neighbours — and the **activity cliffs**: alike in structure, far apart in potency.',
          'Treat **structural alerts** as a short list of reasons to look twice, never as a verdict.'],
        ref: [['Rule sets', 'Lipinski Ro5, Veber, Egan, Ghose, bRo5 and a degrader-aware working rule — Ro5 alone rejects almost every degrader.'],
          ['A property in the file', 'wins over a computed one, and the tab says where each value came from.'],
          ['Salt', 'Only the largest piece is the compound.']],
        watch: [{ k: 'warn', t: 'The chemistry toolkit (RDKit) is fetched from the internet the first time. Offline, structures are not drawn — everything else in Hit Finder still works.' }],
        steps: [
          { sel: ['#pane-chem .src-bar', '#pane-chem .es-a'], t: 'Structures are optional', place: 'bottom',
            b: 'Add a CSV, Excel or `.smi` file with a name and a SMILES for each compound. They are matched by name. RDKit, the chemistry toolkit, is fetched online the first time.' },
          { sel: '#pane-chem .prof-t', deep: true, t: 'Drug-likeness', place: 'top', miss: MISS_STRUCT,
            b: 'How many hits pass each rule set — Lipinski, Veber, Egan, Ghose, bRo5 and a degrader-aware one. **Use as a gate** adds a rule to your criteria; an unread rule counts as unread, never as passed.' },
          { sel: '#chem-series', deep: true, t: 'The series', place: 'top', miss: MISS_STRUCT,
            b: 'Compounds grouped by similarity, a map of them, **activity cliffs** (alike in structure, far apart in potency) and structural alerts — a short screen, not a verdict.' }] },

      { id: 'export', label: 'Export', sel: tab('export'), go: go('export'), needs: 'data',
        lead: 'Everything that leaves Hit Finder. The workbook can rebuild the list from the file; the project holds the whole session.',
        do: ['**Download workbook** for everything: summary, hits, every compound, the criteria used, funnel, screens and slots, your calls, the cherry-pick list, the screen data and provenance.',
          '**Print / save as PDF** makes a one-page summary: the criteria, the attrition and the hits with their numbers.',
          '**Save project** writes the whole session — screens, slots, criteria, your calls, merges — to a `.hitfinder.json` you can open on another machine.',
          'In **Cherry-pick**, choose which tiers to re-test and download the list: each compound with a 10-point dilution centred on its potency.'],
        ref: [['Workbook, opened again', '**Open files…** on Screens accepts the workbook: its screens come back and its criteria are offered, and every compound lands in the same tier.'],
          ['Cherry-pick series', 'Ten points, 3-fold, centred on the potency; a compound with a hook keeps its top points past the hook; a bound says it has no midpoint. Rejected compounds are left out, and anything you called a hit is always in.'],
          ['Numbers', 'Numbers are numbers and missing is blank, never 0. Nothing that starts `= + - @` leaves in a file unless it is a number.']],
        steps: [
          { sel: '#ex-xlsx', t: 'The workbook', place: 'right',
            b: 'Everything, so the list can be rebuilt from the file: hits, every compound, the **criteria used**, the funnel, your calls, the cherry-pick list, the screen data and where it came from.' },
          { sel: function(){ return [].slice.call(document.querySelectorAll('#pane-export .ex-c')).filter(function(c){ return /Cherry/.test(c.textContent); })[0]; }, deep: true, t: 'Cherry-pick for re-test', place: 'left',
            b: 'Choose the tiers and download what to put back on a plate: each compound with a 10-point series centred on its potency. A hook keeps its top points; a bound says it has no midpoint.' },
          { sel: function(){ return [].slice.call(document.querySelectorAll('#pane-export .ex-c')).filter(function(c){ return /^Project/.test(c.textContent.trim()); })[0]; }, deep: true, t: 'Save the session', place: 'right',
            b: '**Save project** keeps the screens, slots, criteria, your calls and merges in one file. Your session is also autosaved in this browser.' }] }
    ],
    words: [
      ['Slot', 'What a group of a screen is for: primary, anti-target, viability, counter-screen, rescue or control.'],
      ['Gate', 'A criterion a hit must pass. A **score** criterion only ranks; an **advisory** one is shown and never decides.'],
      ['Tier', 'Hit · Borderline · Unverified · Rejected.'],
      ['Bound', 'A potency such as `> 10 µM` or `< 1 nM`: the midpoint is beyond the doses tested, so it is a limit, not a value.'],
      ['n.d.', 'No midpoint — the curve barely moves. Its fitted number is kept in the data and left off potency plots.'],
      ['Hook', 'Signal that comes back at the highest doses. It is left out of the fit; Dmax is the effect without it.'],
      ['Productive window', 'The last productive dose divided by the DC50: how forgiving the dose range is.'],
      ['Viability window', 'The viability IC50 divided by the primary DC50: how far from toxicity the compound degrades.'],
      ['Independent runs (n)', 'Separate runs of the same screen. Their potencies are combined as geometric means.'],
      ['Your call', 'Hit, Maybe or Reject with a note — beside the tier, never changing it.']],
    faq: [
      ['A compound I expected is “Unverified”', 'One of its gates could not be read — usually no result for it in the viability or counter-screen. **Screens → Compounds** lists who is missing where. If you would rather not require that gate, set its “if unreadable” box to **Skip**.'],
      ['A compound with a hook is not rejected', 'On purpose: a hook is not a defect. The hook is left out of the fit, Dmax is the effect without it, and the **productive window** says how forgiving the doses are.'],
      ['The same compound appears twice', 'Case, spaces, `-` and `_` are already one name. A leading zero, a salt suffix or a one-letter typo is only **suggested** on Screens → Compounds; press **Same compound** if it is.'],
      ['Structures are not drawn', 'RDKit is fetched from the internet the first time. Offline, structures and the series are unavailable; everything else works.'],
      ['I sent a screen from Echo and my earlier work is gone', 'The session before it is kept as “previous”. Hit Finder offers **Pick up where you left off?** on the Screens tab.'],
      ['Where is my data?', 'Only in this browser, autosaved. Nothing is uploaded. **Save project** makes a file to move or keep.']],
    keys: [['/', 'Find a compound (Hits)'], ['j  or  ↓', 'Next compound in the drawer'], ['k  or  ↑', 'Previous compound'], ['h  m  x', 'Your call: hit, maybe, reject'], ['Esc', 'Close the drawer'], ['← →  Home  End', 'Move between tabs']]
  });
})();
