// Lumina: dose-response for assays you pipette by hand — you draw the layout, drop the reader file, get the potencies.
(function(){
  var plate = function(){ switchTab('input'); };
  var step = function(i){ return function(){ switchTab('input'); lmStepGo(i); }; };
  var stepBtn = function(i){ return function(){ return document.querySelectorAll('#lm-steps .lm-step')[i - 1]; }; };
  var MISS = 'This fills in once the layout is complete and the curves are fitted.';
  tourRegister({
    id: 'lumina', name: 'Lumina',
    blurb: 'Lumina fits dose–response curves for assays you **pipette by hand**. You draw the layout on the plate — which wells are which dilution series, which compound, which controls — drop the reader file onto it, and get potencies with their fits.',
    where: function(){ var t = document.querySelector('.tab.active'); var id = t ? t.getAttribute('data-tab') : 'input'; return id === 'input' ? 'plate' : id; },
    data: { label: 'Load an example plate', has: function(){ return Object.keys((state && state.wellData) || {}).length > 0; }, load: function(){ switchTab('input'); loadLuminaTestData(); } },
    intro: [{ t: 'Welcome to Lumina',
      b: 'You **draw the layout** on the plate, drop the reader file onto it, and get a potency for every compound. Five steps along the top say what is done and what is next. About a minute; **Esc** leaves it at any point.',
      nodata: 'The example plate has a finished layout and readings, so the tour can show every step and the results. It is only loaded if you press the button.' }],
    outro: [{ t: 'Come back any time', sel: '.tab[data-tab="guide"]', place: 'bottom', go: function(){ switchTab('guide'); },
      b: 'The **Guide** tab keeps all of this in writing — each step of the plate and the results, with a tour of each — plus the words used and what to do when something looks wrong.' }],
    quick: [
      'Pick the **assay type** and the **plate size** at the top of the Plate tab.',
      '**1 Gradient** — drag across the wells one dilution series covers; give the top concentration and the dilution factor.',
      '**2 Compounds** — drag across the area the compounds go in; **Make compounds**. **3 Controls** — mark the 100 % wells (and 0 % for displacement).',
      '**4 Names** — type or paste the compound names. **5 Readings** — drop the reader file on the plate, or paste values from Excel.',
      'Press **Fit curves →**. The Results tab has the potencies, the curves, a plot, and every export.'],
    tabs: [
      { id: 'plate', label: 'Plate', sel: '.tab[data-tab="input"]', go: plate,
        lead: 'Where you describe the experiment. One card, laid out in the order the work is done: what the assay is and how big the plate is, then five steps, then the plate itself with a panel beside it that only appears when you select wells.',
        do: ['Choose the **assay type** — it sets how readings are normalised and what the potency is called — and the plate size, 96 or 384 wells.',
          '**Drag across wells** on the plate to say what they are: a rectangle, **Shift** to extend, `⌘` / `Ctrl` to add, a row or column label for a whole line, the corner for the whole plate. Or type a range such as `B2:C11`.',
          'The panel beside the plate asks what the selection is — a gradient, compounds, a control — and shows only that form. Press **Enter** to apply.',
          'More compounds than one plate holds? Press **+** to add a plate: the layout is shared, the compounds continue, and each plate is normalised to its own controls.'],
        ref: [['Assay type', '**HiBiT degradation** — DC50 and Dmax. **CTG viability** — IC50 and Span. **Displacement** — IC50; needs both a 100 % and a 0 % control. **Gain of signal** — EC50 and Emax. The name follows the assay everywhere: table, curve, plot, exports.'],
          ['Five steps', 'Each says what is done (“11 pts · 1 µM → 16.9 pM”) and what is not; click one to select that part of the layout. They can be done in any order.'],
          ['Plates', 'Tabs of one experiment. Wells read as `P2:C3` once there are several plates. Double-click a tab or press `F2` to rename it; a plate loaded from a file is named after the file.'],
          ['Undo', '`⌘Z` / `Ctrl+Z` or the **Undo** button takes back a layout change. `Delete` clears the selected wells; **Clear layout** starts the plate over.'],
          ['Copy a block', '`⌘C` / `⌘X`, click where the top-left corner should go, `⌘V` — the same shortcut pastes values copied from Excel, whichever you copied last.']],
        watch: [{ k: 'tip', t: 'A well’s colour tells you what it is: each compound has a colour, shaded dark at its top concentration, so the direction of the series reads without a number. Controls have their own colour.' }],
        steps: [
          { sel: '#lm-card .lm-head', t: 'The assay and the plate', place: 'bottom',
            b: 'The **assay type** decides how readings are normalised and what the potency is called — DC50, IC50 or EC50. Then 96 or 384 wells. **+** adds a plate that continues the same layout.' },
          { sel: '#lm-steps', t: 'Five steps, in any order', place: 'bottom',
            b: 'Gradient · Compounds · Controls · Names · Readings. Each says what is done and what is not; **click one** to select that part of the layout. Nothing is lost if you do them in a different order.' },
          { deep: true, sel: '#well-grid', t: 'Drag to say what wells are', place: 'right',
            b: '**Drag** a rectangle; **Shift** extends it, `⌘` / `Ctrl` adds or removes wells, a row or column label takes the whole line. The panel on the right asks what the selection is.' }] },

      { id: 'gradient', label: 'Plate › 1 Gradient', tag: 'Plate', sel: stepBtn(1), go: step(1), head: false,
        lead: 'A gradient is one dilution series, drawn on the plate. Its points run along the direction you choose; the other way across the selection is replicates.',
        do: ['Drag across the wells the series covers — any shape, any direction. A plate can be divided into as many gradients as it holds.',
          'In the panel give the **Top conc.**, its unit and the **Dilution** (the fold between neighbouring points).',
          'Choose **Highest at** — ← → ↑ ↓ — and press **Set gradient**.'],
        ref: [['Points and replicates', 'Read off the shape of your selection — you never type them. The preview says “11 points × 2 replicates · 1 µM → 16.9 pM” before you apply.'],
          ['Shading', 'Wells are shaded dark to light, so the end that holds the top concentration is visible.']],
        watch: [{ k: 'tip', t: 'Column and row headers print the concentration when every gradient well under them shares it; otherwise the well prints it.' }],
        steps: [{ sel: '#lm-sel', t: '1 · Gradient', place: 'left',
          b: 'Drag across the wells one dilution series covers, then give the **top concentration**, the **dilution** and which end is highest. Points and replicates come from the shape of what you selected.' }] },

      { id: 'compounds', label: 'Plate › 2 Compounds', tag: 'Plate', sel: stepBtn(2), go: step(2), head: false,
        lead: 'Tell Lumina how the replicates lie: the area you select is cut into bands of replicates across the gradient — one compound per band, numbered in reading order.',
        do: ['Drag across the whole area the compounds go in.', 'Choose the **replicates per compound** (1–4). Off a gradient it also asks whether replicates are **rows** or **columns**.', 'Press **Make compounds**.'],
        ref: [['Bands', 'A compound never straddles two gradients, so two half-plate gradients give compounds per half. Controls and wells with no gradient are left out.'],
          ['More plates', 'More compounds than fit continue on the next plate: plate 2 starts where plate 1 ended.']],
        steps: [{ sel: '#lm-sel', t: '2 · Compounds', place: 'left',
          b: 'Select the area the compounds occupy, say how many replicates each has (1–4), and press **Make compounds**: one compound per band of replicates, numbered in reading order.' }] },

      { id: 'controls', label: 'Plate › 3 Controls', tag: 'Plate', sel: stepBtn(3), go: step(3), head: false,
        lead: 'Each plate is normalised to its own controls, so they are marked once and apply to every plate.',
        do: ['Drag across the wells that read 100 % — the vehicle or untreated signal — and press **100 % control**.', 'For **displacement**, do the same for the **0 % control**.'],
        ref: [['Without controls', 'Everything stays in raw counts. The percent-based fit settings (fixed top or bottom, replicate SD, hook) stand aside, and the Results say so.']],
        watch: [{ k: 'warn', t: 'Marking no control is allowed, but then no number is a percentage. Mark at least the 100 % wells unless you really want raw counts.' }],
        steps: [{ sel: '#lm-sel', t: '3 · Controls', place: 'left',
          b: 'The wells that read 100 % — vehicle or untreated — and, for displacement, the 0 % wells. Each plate is normalised to **its own** controls before the results are pooled.' }] },

      { id: 'names', label: 'Plate › 4 Names', tag: 'Plate', sel: stepBtn(4), go: step(4), head: false,
        lead: 'Compounds are numbered by position and named separately, so the layout never depends on what a compound is called.',
        do: ['Open **Names**.', 'Type a name for each number, or paste a column from Excel: a pasted list fills downwards and adds plates as needed.'],
        steps: [{ sel: '#lm-body', t: '4 · Names', place: 'top',
          b: 'Type a name for each compound, or **paste a column from Excel** — it fills downwards and adds plates as needed. Names attach to numbers, so renaming never touches the layout.' }] },

      { id: 'readings', label: 'Plate › 5 Readings', tag: 'Plate', sel: stepBtn(5), go: step(5), head: false,
        lead: 'The reader’s numbers, onto the plate. Drop the export anywhere on the plate card, one file per plate — or paste values copied from any spreadsheet.',
        do: ['**Drop** the reader file on the plate, or press **Choose files**. Several files dropped together fill Plate 1, 2, 3… in name order.',
          'Or copy a block of numbers in Excel and press `⌘V` / `Ctrl+V` with the plate in view. Rows that carry their letters land by letter; a bare block lands with its top-left at the selected well.',
          'The wells are coloured by the reading, so a dead row or column shows at a glance. **Double-click** a well to type or correct one value.'],
        ref: [['Any reader', 'PHERAstar files are read directly; a `.csv`, `.txt` or Excel sheet with no PHERAstar layout goes through the same reader as pasted values. Decimal commas are understood.'],
          ['Same name twice', 'A plate loaded from a file of the same name is replaced, so dropping a run twice does not duplicate it.'],
          ['Wrong size', 'A file whose grid is a different size from the plate says so, instead of reading the wrong wells.']],
        steps: [{ sel: '#lm-card', t: '5 · Readings', place: 'left',
          b: 'Drop the reader file **anywhere on the plate card** — one file per plate — or paste values from Excel with `⌘V`. The wells take the colour of the reading, so a bad row shows at once.' }] },

      { id: 'results', label: 'Results', sel: '.tab[data-tab="results"]', go: function(){ switchTab('results'); }, needs: 'data',
        lead: 'One row per compound, and the curve beside it. Results never go stale: change the plate or a fit setting and the table refits itself.',
        do: ['Read the table: potency (DC50, IC50 or EC50, following the assay), its 95 % confidence interval, the effect (Dmax, Span or Emax), Hill slope, R². A QC chip appears only when something is flagged.',
          'Click a row, or step with `↑` `↓`. `←` `→` switch the curve between **Fit** and **Raw signal**; `P` and `C` switch **Plot** and **Curve**.',
          'On the curve, **click a point to leave it out** — the fit updates at once and a cross marks where it was. Click or right-click the cross to put it back.',
          '**Plot** draws any fitted quantity against any other; **Units** sets the unit and linear or log; **Export** takes everything out.'],
        ref: [['Flags', '**R² below the limit** · **Replicates differ** beyond the SD limit · **Hook** (top doses rise again) · **>range / <range**: the potency sits outside the doses tested, so it is an extrapolation. A flagged curve keeps its number, visibly flagged.'],
          ['Fit settings', 'Two groups: **Flag a curve when…** (QC limits) and **Constrain the fit** (fix top, bottom or Hill). A dot on the button means something differs from the defaults. Rows that do not apply are dimmed, never hidden.'],
          ['Units', 'Auto, or M to pM, linear or log₁₀ — it drives the table, the plot, copies and every export, so they always agree.'],
          ['Export', '**Excel** (results, raw data, Prism tables and the fit settings) · **Results (.csv)** · **Copy table** · **Raw data (.csv)** · **Plot as image (.png)**. Inside dHUB, **Send to Labbook** attaches the potencies to an experiment.'],
          ['Plot', 'Default is potency against Dmax. Hollow red points are flagged; colour can follow the plate; search a compound to dim the rest. Click a point to select it, double-click for its curve. **Save PNG** always uses a light background.']],
        watch: [{ k: 'tip', t: '`⌘Z` on Results undoes curve edits only — layout edits are undone on the Plate tab, and the toast says so. A curve is never left with fewer than three points.' }],
        steps: [
          { sel: '#results-table-wrap', t: 'One row per compound', place: 'right', miss: MISS,
            b: 'Potency with its 95 % interval, the effect, Hill and R², and a QC chip only when something is flagged. **Click a row** or step with `↑` `↓`.' },
          { sel: '#curve-canvas', t: 'The curve — and your edits', place: 'left', miss: MISS,
            b: '**Click a point** to leave it out; the fit is redone at once and a cross marks where it was. Click the cross to put it back. `←` `→` flip between the fit and the raw signal.' },
          { deep: true, sel: '#rs-acts', t: 'Settings, units, export', place: 'bottom', miss: MISS,
            b: '**Fit settings** set the QC limits and constraints; **Units** drives the table, plot and every export; **Export** takes out Excel, CSV, a copyable table, raw data and the plot as a picture.' },
          { deep: true, sel: '#rs-tabs', t: 'Plot', place: 'left', miss: MISS,
            b: 'Switch **Curve** to **Plot** to draw any fitted quantity against any other — potency against Dmax by default. Hollow red points are flagged.' }] }
    ],
    words: [
      ['Gradient', 'One dilution series drawn on the plate.'],
      ['Compound (zone)', 'A band of replicates across a gradient. Numbered by position and named separately.'],
      ['100 % / 0 % control', 'The wells every plate is normalised to: vehicle or untreated (100 %), and for displacement the fully displaced wells (0 %).'],
      ['DC50 · IC50 · EC50', 'The concentration giving half of the effect. The name follows the assay type.'],
      ['Dmax · Span · Emax', 'The size of the effect: Dmax for degradation, Span for viability, Emax for gain of signal.'],
      ['Hook', 'Signal that rises again at the top doses; those points are left out of the fit.'],
      ['>range · <range', 'The midpoint sits outside the doses tested — an extrapolation, not a measurement.'],
      ['Raw counts', 'What the results show when no control is marked: no number is a percentage.']],
    faq: [
      ['“Fit curves” is greyed out', 'It waits until the layout and readings are complete, and says what is missing beside the button: **Set a gradient**, **Make compounds** or **Add the readings**.'],
      ['The numbers look huge or negative', 'No control is marked, so everything is in raw counts. Mark the 100 % wells on step 3.'],
      ['My readings landed in the wrong wells', 'The file’s grid must match the plate size; Lumina says when it does not. If a file has titles above the numbers, paste the block instead and click the well where its top-left corner should go.'],
      ['A potency says “>range”', 'The midpoint is higher than the highest dose tested — the compound is weaker than the series reaches. Extend the series, or report it as a bound.'],
      ['I changed the layout and the results changed', 'On purpose: results never go stale. They are refitted whenever the plate or a setting changes.'],
      ['Which assay type?', 'HiBiT degradation for a degrader screen (DC50, Dmax); CTG viability for cell viability (IC50, Span); Displacement for a tracer displaced by your compound; Gain of signal for an assay that rises with dose.'],
      ['Can I use a reader other than PHERAstar?', 'Yes. Copy the 96- or 384-well block from any spreadsheet and press `⌘V` with the plate in view.']],
    keys: [['Drag', 'Select a rectangle of wells'], ['Shift · ⌘ / Ctrl', 'Extend · add or remove wells'], ['Enter', 'Apply the panel (and advance the compound name)'], ['Delete', 'Clear the selected wells'],
      ['⌘C  ⌘X  ⌘V', 'Copy, cut and paste a block — or paste values from Excel'], ['⌘Z  ⌘⇧Z', 'Undo / redo (Plate); curve edits only (Results)'], ['F2', 'Rename the plate'],
      ['↑ ↓  ← →', 'Results: compound · fit / raw'], ['P  C', 'Results: Plot · Curve']]
  });
})();
