#!/usr/bin/env python3
"""Carry the help assistant (tools/assist/) into the shell and into every app that has notes.

    python3 tools/sync_assist.py            # write
    python3 tools/sync_assist.py --check    # exit 1 if a target is out of date

What goes where:
  * the shell gets the kit, the host (what the assistant may ask the Hub), and EVERY app's notes —
    inside dHUB there is one bubble and it answers for whatever the person can open;
  * an app gets the kit and its own notes, tools/assist/kb/<folder>.js — on its own it draws its own
    bubble, inside the Hub it stays quiet;
  * an app with no notes yet gets nothing: no dead kit.
Edit tools/assist/ only. The copies say so in their first comment.
"""
import sys, re, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
A = ROOT / 'tools/assist'
CSS = (A / 'assist.css').read_text(encoding='utf-8').rstrip('\n')
KIT = (A / 'assist.js').read_text(encoding='utf-8').rstrip('\n')
HOST = (A / 'host-shell.js').read_text(encoding='utf-8').rstrip('\n')
KBS = {p.stem: p.read_text(encoding='utf-8').rstrip('\n') for p in sorted((A / 'kb').glob('*.js'))}

def targets():
    out = ['shell/hub-shell.html']
    for p in sorted((ROOT / 'apps').glob('*/*.html')):
        if p.parent.name in KBS and p.stem == p.parent.name:
            out.append(str(p.relative_to(ROOT)))
    return out

def js_block(target):
    if target.startswith('shell/'):
        parts = [HOST, KIT] + [KBS['hub']] + [KBS[k] for k in sorted(KBS) if k != 'hub']
        src = 'tools/assist/{host-shell,assist,kb/*}.js'
    else:
        stem = pathlib.Path(target).stem
        parts = [KIT, KBS[stem]]
        src = 'tools/assist/assist.js + kb/' + stem + '.js'
    body = '\n'.join(parts)
    if '</script' in body.lower():
        sys.exit('a </script> inside the assistant source would end the block early')
    return '/* assist-js:begin — generated by tools/sync_assist.py from ' + src + '; do not edit here */\n' + body + '\n/* assist-js:end */'

CSS_BLK = '/* assist-css:begin — generated by tools/sync_assist.py from tools/assist/assist.css; do not edit here */\n' + CSS + '\n/* assist-css:end */'

def patch(src, target):
    out = src
    for tag, blk, wo, wc, head in (('assist-css', CSS_BLK, '<style>\n', '\n</style>\n', True),
                                   ('assist-js', js_block(target), '<script>\n', '\n</script>\n', False)):
        pat = re.compile(r'/\* ' + tag + r':begin.*?/\* ' + tag + r':end \*/', re.S)
        if pat.search(out):
            out = pat.sub(lambda m: blk, out, count=1)
        else:   # the real closing tag is the one on a line of its own — the strings inside JS also contain them
            i = out.index('\n</head>') + 1 if head else out.rindex('\n</body>') + 1
            out = out[:i] + wo + blk + wc + out[i:]
    return out

def main():
    check = '--check' in sys.argv
    bad = 0
    for t in targets():
        p = ROOT / t
        src = p.read_text(encoding='utf-8')
        new = patch(src, t)
        if new != src:
            if check: print('OUT OF DATE  ' + t); bad += 1
            else: p.write_text(new, encoding='utf-8'); print('updated      ' + t)
        else:
            print('current      ' + t)
    sys.exit(1 if bad else 0)
main()
