#!/usr/bin/env python3
"""Carry the right-click menu kit (tools/ctxkit/ctxkit.css + ctxkit.js) into every page that has one.

The kit is the menu component only — ctxBind/ctxOpen and their look. What a page offers on a
right-click is that page's own business (Lumina: wells, plates, results; the shell: cards and rail).

    python3 tools/sync_ctxkit.py            # write
    python3 tools/sync_ctxkit.py --check    # exit 1 if a target is out of date

A target that already has the markers is updated in place; one that does not gets the CSS as a new
<style> before </head> and the JS as a new <script> before </body>. Edit the kit in tools/ctxkit/
only — the copies say so in their first comment.
"""
import sys, re, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
TARGETS = ['apps/lumina/lumina.html', 'shell/hub-shell.html']
CSS = (ROOT / 'tools/ctxkit/ctxkit.css').read_text(encoding='utf-8').rstrip('\n')
JS = (ROOT / 'tools/ctxkit/ctxkit.js').read_text(encoding='utf-8').rstrip('\n')
CSS_BLK = '/* ctx-kit:begin — generated by tools/sync_ctxkit.py from tools/ctxkit/ctxkit.css; do not edit here */\n' + CSS + '\n/* ctx-kit:end */'
JS_BLK = '/* ctx-kit-js:begin — generated by tools/sync_ctxkit.py from tools/ctxkit/ctxkit.js; do not edit here */\n' + JS + '\n/* ctx-kit-js:end */'

def patch(src):
    out = src
    for tag, blk, wrap_open, wrap_close, anchor in (
        ('ctx-kit', CSS_BLK, '<style>\n', '\n</style>\n', '</head>'),
        ('ctx-kit-js', JS_BLK, '<script>\n', '\n</script>\n', '</body>')):
        pat = re.compile(r'/\* ' + re.escape(tag) + r':begin.*?/\* ' + re.escape(tag) + r':end \*/', re.S)
        if pat.search(out):
            out = pat.sub(lambda m: blk, out, count=1)
        else:
            # the real closing tag is the one on a line of its own — '</head>' also appears inside JS strings
            head = anchor == '</head>'
            i = out.index('\n</head>') + 1 if head else out.rindex('\n</body>') + 1
            out = out[:i] + wrap_open + blk + wrap_close + out[i:]
    return out

def main():
    check = '--check' in sys.argv
    bad = 0
    for t in TARGETS:
        p = ROOT / t
        src = p.read_text(encoding='utf-8')
        new = patch(src)
        if new != src:
            if check:
                print('OUT OF DATE  ' + t); bad += 1
            else:
                p.write_text(new, encoding='utf-8'); print('updated      ' + t)
        else:
            print('current      ' + t)
    sys.exit(1 if bad else 0)
main()
