#!/usr/bin/env python3
"""The one source for the motion every app shares (2026-09-29).

Each app is a separate document inside a srcdoc iframe, so there is no stylesheet to import.
This writes the same small CSS block into each app between `mo-kit:begin/end` markers, with the
per-app selectors declared here. Edit the kit here, never in an app.

The rules it enforces (the same ones the Incubator flask follows):
  * arrival, hover and state — never a loop at rest;
  * only transform and opacity move;
  * nothing repeated in bulk gets a transition (a plate well, a table cell);
  * `backwards` fill, never `both`: a transform left on an ancestor after the animation ends
    makes it the containing block for every position:fixed popover inside it.
Reduced motion is already clamped to 1 ms by the block every app carries.

  python3 tools/sync_motion.py            write the kit into every app
  python3 tools/sync_motion.py --check    exit 1 if any app differs from this file
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

# app -> (pane selector whose `.active` copy is the visible tab, [(selector, lift px)], extra css)
APPS = {
    'echo':          ('.tabpane',  [], ''),
    'dora':          ('.panel',    [], ''),
    'bca':           ('.panel',    [], ''),
    'beacon':        ('.panel',    [('.assay-mode-card', 2)], ''),
    'lumina':        ('.tabpane',  [], ''),
    'hitfinder':     ('.tabpane',  [], ''),
    'tempo':         ('.tabpane',  [], ''),
    'blueprint':     ('.panel',    [], ''),
    'helix':         ('.panel',    [], ''),
    'protein-tools': ('.panel',    [], ''),
    'cell-archive':  ('.panel',    [('.cell-grid:not(.as-list) .cell-tile', 2)],
                      '.ca-micro{transition:transform var(--dur-2) var(--ease-out);}\n'
                      '.ca-micro:hover{transform:scale(1.025);}\n'),
    'iceberg':       ('.tab-pane', [],
                      '.box-fill-bar{transform-origin:left center;animation:moGrow 600ms var(--ease-out) backwards;}\n'
                      '@keyframes moGrow{from{transform:scaleX(0);}}\n'),
}

def kit(app):
    pane, lifts, extra = APPS[app]
    css = ['/* mo-kit:begin — generated by the sync_motion tool, do not edit here */\n',
           ':root %s.active{animation:moPane var(--dur-2) var(--ease-out) backwards;}\n' % pane,
           '@keyframes moPane{from{opacity:0;transform:translateY(6px);}to{opacity:1;transform:none;}}\n']
    # a box and a sortable header change colour when you reach for them: they ease, they do not snap (colour only — never transform, never layout)
    css.append(':root :is(input:not([type=checkbox]):not([type=radio]):not([type=range]):not([type=file]):not([type=color]),select,textarea,summary){'
               'transition:border-color var(--dur-1) var(--ease),background-color var(--dur-1) var(--ease),color var(--dur-1) var(--ease),box-shadow var(--dur-1) var(--ease);}\n')
    css.append(':root :is(tbody tr,th[onclick]){transition:background-color var(--dur-1) var(--ease),color var(--dur-1) var(--ease);}\n')
    for sel, px in lifts:
        css.append(':root %s{transition:border-color var(--dur-1) var(--ease),background-color var(--dur-1) var(--ease),'
                   'box-shadow var(--dur-1) var(--ease),transform var(--dur-2) var(--ease-out);}\n' % sel)
        css.append(':root %s:hover{transform:translateY(-%dpx);}\n' % (sel, px))
    css.append(extra)
    css.append('/* mo-kit:end */\n')
    return ''.join(css)

def put(s, block):
    s = re.sub(r'/\* mo-kit:begin.*?/\* mo-kit:end \*/\n', '', s, flags=re.S)
    # Before the icon tile block when there is one, so sync_icons (which appends its block just
    # before </style>) finds its own text exactly where it would put it and reports no drift.
    i = s.find('/* ic-tile:begin')
    if i < 0: i = s.index('</style>')
    return s[:i] + block + s[i:]

def run(check):
    bad = 0
    for app in APPS:
        p = ROOT / 'apps' / app / (app + '.html')
        s = p.read_text(encoding='utf-8')
        n = put(s, kit(app))
        if n != s:
            bad += 1
            if check: print('drift:', app)
            else: p.write_text(n, encoding='utf-8'); print('wrote', app)
    if check and not bad: print('motion kit in sync')
    return 1 if (check and bad) else 0

if __name__ == '__main__':
    sys.exit(run('--check' in sys.argv))
