#!/usr/bin/env python3
"""Carry the guided tour and the Guide tab (tools/tourkit/) into every app that has a definition.

    python3 tools/sync_tour.py            # write
    python3 tools/sync_tour.py --check    # exit 1 if a target is out of date

One definition per app, tools/tourkit/apps/<folder>.js, calls tourRegister({...}). It is written into the app
right after the engine, so it can name the app's own functions and ids directly. An app with no definition gets
nothing. The apps' own Guide panes hold only <div data-tk-guide></div>; the kit draws the Guide into it.

Edit tools/tourkit/ — the copies say so in their first comment.
"""
import sys, re, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
K = ROOT / 'tools/tourkit'
CSS = (K / 'tour.css').read_text(encoding='utf-8').rstrip('\n')
KIT = (K / 'tour.js').read_text(encoding='utf-8').rstrip('\n')
DEFS = {p.stem: p.read_text(encoding='utf-8').rstrip('\n') for p in sorted((K / 'apps').glob('*.js'))}

def targets():
    out = []
    for p in sorted((ROOT / 'apps').glob('*/*.html')):
        if p.parent.name in DEFS and p.stem == p.parent.name:
            out.append(str(p.relative_to(ROOT)))
    return out

def js_block(target):
    stem = pathlib.Path(target).stem
    body = KIT + '\n' + DEFS[stem]
    if '</script' in body.lower():
        sys.exit('a </script> inside the tour source would end the block early')
    return '/* tour-js:begin — generated by tools/sync_tour.py from tools/tourkit/tour.js + apps/' + stem + '.js; do not edit here */\n' + body + '\n/* tour-js:end */'

CSS_BLK = '/* tour-css:begin — generated by tools/sync_tour.py from tools/tourkit/tour.css; do not edit here */\n' + CSS + '\n/* tour-css:end */'

def patch(src, target):
    out = src
    for tag, blk, wo, wc, head in (('tour-css', CSS_BLK, '<style>\n', '\n</style>\n', True),
                                   ('tour-js', js_block(target), '<script>\n', '\n</script>\n', False)):
        pat = re.compile(r'/\* ' + tag + r':begin.*?/\* ' + tag + r':end \*/', re.S)
        if pat.search(out):
            out = pat.sub(lambda m: blk, out, count=1)
        else:   # the real closing tag is the one on a line of its own — the strings inside JS also contain them
            i = out.index('\n</head>') + 1 if head else out.rindex('\n</body>') + 1
            out = out[:i] + wo + blk + wc + out[i:]
    return out

def main():
    check = '--check' in sys.argv
    bad = 0
    for t in targets():
        p = ROOT / t
        src = p.read_text(encoding='utf-8')
        new = patch(src, t)
        if new != src:
            if check: print('OUT OF DATE  ' + t); bad += 1
            else: p.write_text(new, encoding='utf-8'); print('updated      ' + t)
        else:
            print('current      ' + t)
    sys.exit(1 if bad else 0)
main()
