# -*- coding: utf-8 -*-
# {pid: {old_key: (new_key, "Human label")}}
NAMES = {}

NAMES['gibson'] = {
 'valRange':('overlapLen','Primer overlap length'),
 'bindingRegionTmT':('primerTm','Primer binding Tm'),
 'exchangeNeededIncubateT':('dpniTemp','DpnI digest temp'),
 'exchangeNeededIncubateMin':('dpniTime','DpnI digest time'),
 'valX':('loadingDyeX','DNA loading dye strength'),
 'wholeThingPct':('agarosePct','Agarose gel %'),
 'firstNebhifiX':('masterMixX','HiFi Master Mix strength'),
 'bpAimAmt':('vectorAmt','Vector amount'),
 'aimVectorX':('insertExcess','Insert molar excess'),
 'incubateT':('assemblyTemp','Assembly temp'),
 'valMin':('assemblyTimeFew','Assembly time (2–3 fragments)'),
 'valMin2':('assemblyTimeMany','Assembly time (4–6 fragments)'),
 'iceT':('storageTemp','Storage temp'),
 'transformVol':('transformVol','Volume to transform'),
}

NAMES['redigest'] = {
 'mostNebEnzymesT':('digestTemp','Digest temp (most NEB enzymes)'),
 'nebEnzymesMin':('digestTime','Digest time'),
 'enzymesMarkedTsMin':('digestTimeTS','Digest time (Time-Saver enzymes)'),
 'heatInactivateT':('hiTemp','Heat-inactivation temp'),
 'hfEnzymesT':('hiTempHF','Heat-inactivation temp (HF enzymes)'),
 'heatInactivateMin':('hiTime','Heat-inactivation time'),
 'hfEnzymesMin':('hiTimeHF','Heat-inactivation time (HF enzymes)'),
 'entireDigestRange':('gelPct','Agarose gel %'),
 'coloniesEluteRange':('gelEluteVol','Gel-extraction elution volume'),
 'purifiedVectorIncubateT':('cipTemp','Dephosphorylation temp'),
 'purifiedVectorIncubateMin':('cipTime','Dephosphorylation time'),
 'valVol':('cipVol','Quick CIP / rSAP volume'),
 'heatInactivateT2':('cipHiTempQuick','CIP inactivation temp (Quick CIP)'),
 'quickCipT':('cipHiTempRsap','CIP inactivation temp (rSAP)'),
 'heatInactivateMin2':('cipHiTimeQuick','CIP inactivation time (Quick CIP)'),
 'quickCipMin':('cipHiTimeRsap','CIP inactivation time (rSAP)'),
 'iceWaterX':('ligaseBufferX','T4 Ligase Buffer strength'),
 'overnightColdRoomT':('ligTemp','Standard ligation temp'),
 'overnightColdRoomMin':('ligTime','Standard ligation time'),
 'conveniT':('quickLigTemp','Quick Ligation temp'),
 'convenientRoutineRange':('quickLigTime','Quick Ligation time'),
 'heatInactivateT3':('ligHiTemp','Ligase inactivation temp'),
 'heatInactivateMin3':('ligHiTime','Ligase inactivation time'),
 'transformRange':('transformVol','Volume to transform'),
}

NAMES['transfo'] = {
 'iceDhRange':('thawTimeDh5a','Thaw time (DH5α)'),
 'nebStableRange':('thawTimeStable','Thaw time (NEB Stable)'),
 'appropriateAntibioticT':('plateWarmTemp','Plate pre-warm temp'),
 'mixRange':('dnaVol','Plasmid DNA volume'),
 'plasmidDnaPgAmt':('dnaMaxAmt','Max plasmid DNA'),
 'pgNgRange':('cellsVol','Competent cells volume'),
 'incubateIceMin':('iceTimeBefore','Ice incubation before shock'),
 'heatShockT':('shockTemp','Heat-shock temp'),
 'heatShockRange':('shockTime','Heat-shock time'),
 'shockTypicallyMin':('shockTimeDh5a','Heat-shock time (DH5α)'),
 'typicallyMin':('shockTimeStable','Heat-shock time (NEB Stable)'),
 'backIceMin':('iceTimeAfter','Ice incubation after shock'),
 'valVol':('recoveryVol','Recovery medium volume'),
 'lbSocIncubateT':('recoveryTemp','Recovery temp'),
 'lbSocIncubateMin':('recoveryTime','Recovery time'),
 'socIncubateRange':('recoveryShake','Recovery shaking speed'),
 'lentiviralPlasmidsT':('recoveryTempLenti','Recovery temp (lentiviral)'),
 'valVol2':('platingVol','Plating volume'),
 'incubateOvernightT':('plateTemp','Plate incubation temp'),
 'lentiviralT':('plateTempLenti','Plate incubation temp (lentiviral)'),
 'singleColoniesVol':('cultureVol','Overnight culture volume'),
 'mlLbAntibioticVol':('cultureTubeVol','Culture tube size'),
 'tubeIncubateOvernightT':('cultureTemp','Overnight culture temp'),
 'tubeIncubateOvernightRange':('cultureShake','Overnight culture shaking'),
}

NAMES['miniprep'] = {
 'centrifugeVol':('cultureVol','Culture volume'),
 'centrifugeCultureN':('pelletSpeed','Pellet spin speed'),
 'cultureRpmMin':('pelletTime','Pellet spin time'),
 'valVol':('resuspVol','Resuspension Solution volume'),
 'valVol2':('lysisVol','Lysis Solution volume'),
 'invertGentlyRange':('lysisInverts','Lysis inversions'),
 'valVol3':('neutrVol','Neutralization Solution volume'),
 'invertRange':('neutrInverts','Neutralization inversions'),
 'invertCentrifugeMin':('debrisSpinTime','Debris spin time'),
 'collectionTubeCentrifuMin':('bindSpinTime','Binding spin time'),
 'valVol4':('washVol','Wash Solution volume'),
 'centrifugeRange':('washSpinTime','Wash spin time'),
 'centrifugeEmptyColumnMin':('drySpinTime','Membrane drying spin'),
 'columnCleanVol':('eluteTubeVol','Elution tube size'),
 'mlTubeVol':('eluteVol','Elution volume'),
 'preWarmedT':('eluteTemp','Elution buffer temp'),
 'higherYieldIncubateMin':('eluteWait','Elution incubation'),
 'rtCentrifugeMin':('eluteSpinTime','Elution spin time'),
}

NAMES['nucleospin'] = {
 'reactionNtiNtiVol':('pcrSampleVol','PCR sample volume'),
 'reactionVol':('ntiVol','Buffer NTI volume'),
 'loadUpVol':('columnLoadVol','Max load per spin'),
 'collectionTubeSpinMin':('bindSpinTime','Binding spin time'),
 'washVol':('washVol','NT3 wash volume'),
 'washNtSpinMin':('washSpinTime','Wash spin time'),
 'drySpinMin':('drySpinTime','Drying spin time'),
 'eluteRange':('eluteVol','Elution volume'),
 'neBufferWaitMin':('eluteWait','Elution wait at RT'),
 'freshTubeSpinMin':('eluteSpinTime','Elution spin time'),
 'ntiBufferVol':('gelNtiVol','NTI buffer per gel mass'),
 'ntiBufferAmt':('gelSliceMass','Gel mass NTI refers to'),
 'incubateT':('gelDissolveTemp','Gel dissolving temp'),
 'incubateUntilDissolvedRange':('gelDissolveTime','Gel dissolving time'),
 'columnSpinMin':('gelBindSpinTime','Binding spin time (gel)'),
 'washVol2':('gelWashVol','NT3 wash volume (gel)'),
 'washNtSpinMin2':('gelWashSpinTime','Wash spin time (gel)'),
 'onceDrySpinMin':('gelDrySpinTime','Drying spin time (gel)'),
 'eluteRange2':('gelEluteVol','Elution volume (gel)'),
 'preWarmT':('gelEluteTemp','Elution buffer temp (large fragments)'),
 'rtWaitMin':('gelEluteWait','Elution wait at RT (gel)'),
 'waitMinSpinMin':('gelEluteSpinTime','Elution spin time (gel)'),
}

NAMES['grna'] = {
 'selectN':('regionLen','Design region length'),
 'pasteYourN':('idtRegionLen','Region pasted into IDT tool'),
 'protospacerN':('seedLen','Seed region length'),
 'keepDonorN':('donorMaxLen','Max donor length'),
 'typicalDesignRange':('armLen5','5′ homology arm length'),
 'armTagMutationRange':('armLen3','3′ homology arm length'),
 'ultramerGtN':('ultramerCutoff','Ultramer length cutoff'),
 'editSiteAmpliconRange':('ampliconLen','Genotyping amplicon length'),
}

NAMES['crispr-ko'] = {
 'grnaSpacerN':('spacerLen','gRNA spacer length'),
 'asympN':('ssOligoLen','ssOligo insert total length'),
 'totalHomologyArmN':('armLen5','5′ homology arm length'),
 'cutSiteMiddotN':('oligoSpacerLen','gRNA spacer in oligo'),
 'middotHomologyArmN':('armLen3','3′ homology arm length'),
 'scaleAmt':('orderScale','Oligo synthesis scale'),
 'teBufferConc':('naclConc','NaCl in TE buffer'),
 'valConc':('oligoStockConc','ssOligo stock concentration'),
 'freezeT':('oligoStoreTemp','ssOligo storage temp'),
 'workingStockConc':('workStockConc','Working stock concentration'),
 'diluteVol':('workStockDnaVol','Stock volume to dilute'),
 'diluteConc':('workStockSrcConc','Stock concentration diluted from'),
 'stockVol':('workStockBufferVol','Buffer volume for dilution'),
 'pxAmt':('px458Amt','PX458 to digest'),
 'nebT':('bbsiTemp','BbsI digest temp'),
 'nebMin':('bbsiTime','BbsI digest time'),
 'agaroseGelPct':('agarosePct','Agarose gel %'),
 'minT':('assemblyTemp','HiFi assembly temp'),
 'valMin':('assemblyTime','HiFi assembly time'),
 'setT':('assemblyLidTemp','Thermocycler lid temp'),
 'valVol':('transformVol','Volume to transform'),
 'protocolHeatShockT':('shockTemp','Heat-shock temp'),
 'valMin2':('shockTime','Heat-shock time'),
 'lbAmpicillinConc':('ampConc','Ampicillin concentration'),
 'pxGrnaPlasmidAmt':('transfectDnaAmt','PX458-gRNA plasmid per well'),
 'optiMemVol':('optiMemVolA','Opti-MEM volume (tube A)'),
 'fugenehdVol':('fugeneVol','FugeneHD volume'),
 'optiMemVol2':('optiMemVolB','Opti-MEM volume (tube B)'),
 'rtMin':('complexTime','Complex formation time at RT'),
 'valRange':('gfpExpressTime','Time to GFP expression'),
 'tracrrnaAmt':('tracrAmt','tracrRNA amount supplied'),
 'tracrrnaNmolVol':('tracrBufferVol','Duplex buffer for tracrRNA'),
 'stockConc':('tracrStockConc','tracrRNA stock concentration'),
 'crrnaAmt':('crrnaAmt','crRNA amount supplied'),
 'crrnaNmolVol':('crrnaBufferVol','Duplex buffer for crRNA'),
 'stockConc2':('crrnaStockConc','crRNA stock concentration'),
 'valVol2':('cas9ReconVol','Cas9 reconstitution volume'),
 'casAmt':('cas9Conc','Cas9 concentration after reconstitution'),
 'spinDownIncubateMin':('cas9DissolveTime','Cas9 dissolving time on ice'),
 'valVol3':('annealVol','Volume of each RNA to anneal'),
 'incubateT':('annealTemp','Annealing temp'),
 'incubateMin':('annealTime','Annealing time'),
 'componentsIncubateMin':('rnpTime','RNP complex formation time'),
 'pbsResuspendVol':('pbsResuspendVol','PBS resuspension volume'),
 'valVol4':('platingMediaVol','Media per 6-well'),
 'fillVol':('falconVol','Falcon size for ethanol'),
 'valVol5':('electrolyteVol','Electrolyte solution volume'),
 'takeVol':('electroporationVol','Volume per electroporation'),
 'leaveCellsRange':('recoveryTime','Recovery before sorting'),
 'pooledPopulationRange':('poolTime','Pooled culture before analysis'),
 'aimGtPct':('indelTarget','Target indel % before sorting'),
 'beforeSortingGtPct':('indelGoNoGo','Go/no-go indel threshold'),
}

NAMES['crispr-ki'] = {
 'grnaSpacerN':('spacerLen','gRNA spacer length'),
 'homologyArmN':('oligoArmLen5','5′ homology arm (cloning oligo)'),
 'grnaSpacerN2':('oligoSpacerLen','gRNA spacer in oligo'),
 'homologyArmN2':('oligoArmLen3','3′ homology arm (cloning oligo)'),
 'workingStockConc':('workStockConc','ssOligo working stock'),
 'pxAmt':('px458Amt','PX458 to digest'),
 'nebT':('bbsiTemp','BbsI digest temp'),
 'nebMin':('bbsiTime','BbsI digest time'),
 'agaroseGelPct':('agarosePct','Agarose gel %'),
 'minT':('assemblyTemp','HiFi assembly temp'),
 'valMin':('assemblyTime','HiFi assembly time'),
 'lidOffT':('assemblyLidTemp','Thermocycler lid temp'),
 'transformVol':('transformVol','Volume to transform'),
 'lbAmpicillinConc':('ampConc','Ampicillin concentration'),
 'ampicillinMlOvernightT':('plateTemp','Plate incubation temp'),
 'leftHaRange':('donorArmLen5','Left homology arm (plasmid donor)'),
 'insertRightHaRange':('donorArmLen3','Right homology arm (plasmid donor)'),
 'silentDiagnosticSnpRange':('snpDistance','Diagnostic SNP distance from cut'),
 'seedCellsRange':('seedConfluency','Seeding confluency'),
 'pxAmt2':('transfectCas9Amt','PX458 per well'),
 'pxPlasmidDonorRange':('transfectDonorAmt','Plasmid donor per well'),
 'wellRatioRatio':('cas9DonorRatio','Cas9:donor ratio'),
 'incubateRange':('gfpCheckTime','Time before GFP check'),
 'fluorescenceMicroscopyRange':('gfpExpected','Expected GFP+ fraction'),
 'duringFirstMin':('noSelectionTime','No antibiotic selection window'),
 'postTransfectionTrypsiMin':('sortTime','Time to sorting'),
 'sortingBufferPbsPct':('sortFbsPct','FBS in sorting buffer'),
 'bufferPbsFbsConc':('sortHepesConc','HEPES in sorting buffer'),
 'excitationGateTopRange':('sortGate','GFP+ gate (top %)'),
 'valRange':('ssodnLen','ssODN total length'),
 'valRange2':('ssodnArmLen','ssODN homology arm each side'),
 'silentDiagnosticSnpN':('ssodnSnpDistance','Diagnostic SNP distance from cut'),
 'synthesisSufficientN':('desaltMaxLen','Max length for desalted synthesis'),
 'purifyGtN':('pageMinLen','Length above which to PAGE-purify'),
 'tePhConc':('ssodnStockConc','ssODN stock concentration'),
 'tracrrnaConc':('rnaStockConc','crRNA / tracrRNA stock'),
 'tracrrnaAnnealT':('annealTemp','Annealing temp'),
 'annealMin':('annealTime','Annealing time'),
 'finalGrnaDuplexConc':('duplexConc','Final gRNA duplex concentration'),
 'duplexCasProteinRatio':('rnpRatio','gRNA:Cas9 volume ratio'),
 'proteinVolumeVol':('rnpCas9Vol','Cas9 volume'),
 'proteinVolumeConc':('rnpCas9Conc','Cas9 concentration'),
 'volumeCasVol':('rnpGrnaVol','gRNA volume'),
 'casConc':('rnpGrnaConc','gRNA concentration'),
 'incubateRange2':('rnpTime','RNP complex formation time'),
 'logPhaseRange':('harvestConfluency','Harvest confluency'),
 'mustGtPct':('minViability','Minimum viability'),
 'pelletRange':('cellsPerReaction','Cells to pellet'),
 'cellsMin':('pelletTime','Pellet spin time'),
 'bufferVol':('neonTipVol','Neon tip size'),
 'seBufferVol':('nucleofectorVol','4D buffer volume'),
 'valRange3':('rnpAddVol','RNP volume added'),
 'casSsodnRange':('rnpCas9Amt','Cas9 amount added'),
 'valRange4':('ssodnAddVol','ssODN volume added'),
 'cellRange':('ssodnAmt','ssODN amount added'),
 'notDisturbMin':('settleTime','Undisturbed recovery time'),
 'postElectroporationCheMin':('viabilityCheckTime','Time to viability check'),
 'refreshMediumExpectRange':('expectedViability','Expected viability'),
 'harvestSmallAliquotRange':('iceHarvestTime','Time to ICE/T7E1 harvest'),
 'rnpActivityExpectRange':('expectedIndels','Expected indel %'),
 'templateExpectedAmplicRange':('genotypeAmpliconLen','Genotyping amplicon length'),
 'differenceInsertN':('gelVisibleInsert','Insert size visible on gel'),
}

NAMES['scs'] = {
 'growFlasksRange':('condMediaConfluency','Confluency for conditioned media'),
 'aliquotsT':('condMediaTempShort','Conditioned media storage (short)'),
 'fewWeeksT':('condMediaTempLong','Conditioned media storage (long)'),
 'beforeUseSpinN':('condMediaSpeed','Conditioned media spin speed'),
 'useSpinRpmMin':('condMediaSpinTime','Conditioned media spin time'),
 'diluteRatio':('condMediaDilution','Conditioned media dilution'),
 'dilutePct':('condMediaFbsPct','FBS in dilution media'),
 'aliquotVol':('wellVol','Volume per 96-well'),
 'wellLeaveT':('plateTemp','Plate incubation temp'),
 'wellLeavePct':('plateCo2','CO₂ %'),
 'facsMediaVol':('facsMediaVol','FACS media volume'),
 'mediaMlMediaVol':('facsFbsVol','FBS in FACS media'),
 'mlMediaFbsVol':('facsDapiVol','DAPI in FACS media'),
 'mediaFbsMaxVol':('sortMaxVol','Max volume for sorting'),
 'maxLtConc':('sortMaxCells','Cell count that volume covers'),
 'mlMediaPct':('sortFbsPct','FBS in sorting media'),
 'backIncubatorT':('cloneTemp','Clonal expansion temp'),
 'backIncubatorMin':('cloneTime','Undisturbed clonal expansion'),
 'afterMin':('cloneCheckDay','Day to check for colonies'),
 'valVol':('cloneFeedVol','Fresh media per chosen well'),
}

NAMES['bca'] = {
 'prepareBsaStandardsConc':('bsaLowStd','Lowest BSA standard'),
 'mlDdhVol':('stdWellVol','Standard volume per well'),
 'diluteLysatesRatio':('lysateDilution','Lysate dilution'),
 'diluteLysatesVol':('lysateVol','Lysate volume'),
 'diluteLysatesLysateVol':('lysateWaterVol','Water volume'),
 'lysateDdhRatio':('lysateDilutionHigh','Dilution for concentrated samples'),
 'veryConcentratedSampleVol':('sampleWellVol','Sample volume per well'),
 'valVol':('bcaReagentVol','BCA reagent volume'),
 'reagentMixN':('mixSpeed','Plate mixing speed'),
 'mixRpmMin':('mixTime','Plate mixing time'),
 'rpmMinIncubateT':('devTemp','Colour development temp'),
 'rpmMinIncubateMin':('devTime','Colour development time'),
}

NAMES['westernblot'] = {
 'coolCentrifugeT':('precoolTemp','Centrifuge pre-cool temp'),
 'iceRipaRange':('ripaVol6','RIPA per 6-well'),
 'iceRipaWellVol':('ripaVol12','RIPA per 12-well'),
 'wellWellX':('piFinalX','Protease inhibitor (final)'),
 'wellWellPiX':('piStockX','Protease inhibitor stock'),
 'piStockBenzonaseX':('benzonaseX','Benzonase dilution'),
 'distributeCarefullyIncMin':('lysisTime','Lysis time in fridge'),
 'centrifugeT':('clearTemp','Clearing spin temp'),
 'centrifugeMin':('clearTime','Clearing spin time'),
 'freezeT':('lysateStoreTemp','Lysate storage temp'),
 'bsaStandardsConc':('bsaLowStd','Lowest BSA standard'),
 'mlDdhVol':('stdWellVol','Standard volume per well'),
 'diluteLysatesRatio':('lysateDilution','Lysate dilution'),
 'diluteLysatesVol':('lysateVol','Lysate volume'),
 'diluteLysatesUlVol':('lysateWaterVol','Water volume'),
 'lutelysatesvolDdhRatio':('lysateDilutionHigh','Dilution for concentrated samples'),
 'loadVol':('bcaLoadVol','Standard/sample per well'),
 'duplicateVol':('bcaReagentVol','BCA reagent volume'),
 'bcaReagentMixN':('mixSpeed','Plate mixing speed'),
 'reagentMixRpmMin':('mixTime','Plate mixing time'),
 'mixRpmMinT':('devTemp','Colour development temp'),
 'mixRpmMinMin':('devTime','Colour development time'),
 'mopsStockVol':('runBufferVol','Running buffer volume'),
 'runningBufferX':('runBufferX','MOPS working strength'),
 'bufferMopsX':('mopsStockX','MOPS stock strength'),
 'nupageRange':('gelPct','Bis-Tris gel %'),
 'loadLadderVol':('ladderVol','Ladder volume'),
 'ladderUlRunMin':('runTimeH','Gel run time (hours)'),
 'ladderUlRunMin2':('runTimeMin','Gel run time (extra minutes)'),
 'filterPaperX':('membraneSize','Membrane cut size'),
 'blackRunMin':('transferTime','Transfer time'),
 'ponceauMin':('ponceauTime','Ponceau staining time'),
 'washTbsMin':('preBlockWash','Wash before blocking'),
 'washTbsBlockPct':('blockMilkPct','Milk % for blocking'),
 'blockMilkTbsMin':('blockTime','Blocking time'),
 'rtRinseTbsMin':('postBlockRinse','Rinse after blocking'),
 'primaryAntibodyPct':('primaryMilkPct','Milk % for primary'),
 'tbsOvernightT':('primaryTemp','Primary incubation temp'),
 'washX':('primaryWashCount','Washes after primary'),
 'washTbsRange':('primaryWashTime','Wash time after primary'),
 'secondaryMsRbRatio':('secondaryDilution','Secondary antibody dilution'),
 'tubulinHfabRhodamineRatio':('tubulinDilution','hFAB tubulin dilution'),
 'rhodamineTbsMin':('secondaryTime','Secondary incubation time'),
 'washRange':('finalWashCount','Washes after secondary'),
 'washTbsRange2':('finalWashTime','Wash time after secondary'),
}

NAMES['ip'] = {
 'plateConditionConc':('cellsPerPlate','Cells per 10 cm plate'),
 'cellsStartMin':('treatTime','Compound incubation time'),
 'pbsRipaVol':('lysisRipaVol','RIPA per well'),
 'ripaWellX':('piFinalX','Protease inhibitor (final)'),
 'ripaWellPiX':('piStockX','Protease inhibitor stock'),
 'wellPiBenzonaseX':('benzonaseX','Benzonase dilution'),
 'incubateMin':('lysisTime','Lysis time in fridge'),
 'eppendorfCentrifugeN':('clearSpeed','Clearing spin speed'),
 'eppendorfCentrifugeRpmMin':('clearTime','Clearing spin time'),
 'quantificationNormalizAmt':('proteinPerSample','Protein per sample'),
 'sampleSplitInputAmt':('splitTotal','Total protein to split'),
 'sampleSplitAmt':('inputAmt','INPUT fraction'),
 'sampleSplitInputAmt2':('ipAmt','IP fraction'),
 'rbmIggProteinVol':('abVolPerMg','Antibody volume per mg lysate'),
 'mgConc':('abStockConc','Antibody stock concentration'),
 'tubeRbmIggAmt':('abAmt','Antibody amount'),
 'tubeRbmIggAmt2':('abPerProtein','Protein that antibody covers'),
 'msIggControlAmt':('iggControlAmt','Control IgG per mg lysate'),
 'ripaVol':('ipTotalVol','IP reaction volume'),
 'totalIncubateOvernightT':('ipTemp','IP incubation temp'),
 'washProteinBeadsVol':('beadsVol','Beads per sample'),
 'proteinBeadsSampleVol':('beadsWashVol','Bead wash volume'),
 'sampleWashBufferConc':('trisConc','Tris in wash buffer'),
 'bufferMmTrisConc':('naclConc','NaCl in wash buffer'),
 'beadsIncubateT':('beadsTemp','Bead binding temp'),
 'beadsIncubateMin':('beadsTime','Bead binding time'),
 'washX':('washCount','Number of washes'),
 'washVol':('washVol','Wash volume'),
 'valVol':('elutionVol','Loading buffer volume'),
 'loadingBufferX':('ldsX','LDS strength'),
 'loadingBufferLdsX':('dttX','DTT strength'),
 'ldsDttBoilT':('boilTemp','Boil temp'),
 'ldsDttBoilMin':('boilTime','Boil time'),
}

NAMES['hibit'] = {
 'hibitReagentDiluteX':('blottingBufferX','Blotting Buffer dilution'),
 'waterLgbitX':('lgbitX','LgBiT dilution'),
 'regLuciferaseSubstrateX':('substrateX','Luciferase Substrate dilution'),
 'incubateMembraneMin':('membraneTime','Membrane incubation time'),
}

NAMES['hibitlytic'] = {
 'requiredTypicallyRange':('treatTime','Degrader incubation time'),
 'plateShakerN':('shakeSpeed','Plate shaker speed'),
 'plateShakerRpmMin':('shakeTime','Plate shaking time'),
 'valMin':('developTime','Signal development time'),
 'valMin2':('integrationTime','Luminescence integration time'),
}

NAMES['ctg2'] = {
 'overnightT':('thawTempFridge','Overnight thaw temp'),
 'valT':('thawTempBath','Water bath thaw temp'),
 'doNotExceedT':('thawMaxTemp','Thaw temp not to exceed'),
 'storedT':('coldStorageTemp','Cold storage temp'),
 'leaveBenchRange':('benchTime','Bench equilibration time'),
 'waterBathT':('equilTempBath','Water bath temp'),
 'requiresMlVol':('volSmall','Reagent volume (small)'),
 'mlRequiresMin':('equilTimeSmall','Equilibration time (small volume)'),
 'mlRequiresVol':('volLarge','Reagent volume (large)'),
 'minMlRequiresMin':('equilTimeLarge','Equilibration time (large volume)'),
 'valMin':('plateEquilTime','Plate equilibration time'),
 'wellWellVol':('reagentVol96','Reagent per 96-well'),
 'wellReagentVol':('mediumVol96','Medium per 96-well'),
 'mediumWellVol':('reagentVol384','Reagent per 384-well'),
 'mediumWellVol2':('mediumVol384','Medium per 384-well'),
 'valMin2':('lysisShakeTime','Orbital shaking for lysis'),
 'valMin3':('stabiliseTime','Signal stabilisation time'),
 'wellRange':('integrationTime','Luminescence integration time'),
}

NAMES['lenti'] = {
 'cellsMlVol':('seedVol','Plating volume (10 cm dish)'),
 'nextDayPct':('transfectConfluency','Confluency at transfection'),
 'tubeVol':('optiMemVolDna','Opti-MEM (DNA tube)'),
 'tubeOptimemAmt':('gagPolAmt','Gag-Pol plasmid'),
 'lentiviralTransferPlasAmt':('transferAmt','Transfer plasmid'),
 'lentiviralAmt':('envelopeAmt','Envelope plasmid'),
 'tubeVol2':('optiMemVolReagent','Opti-MEM (reagent tube)'),
 'tubeOptimemVol':('transfectReagentVol','Transfection reagent volume'),
 'incubateMin':('tubeRestTime','Tube rest time'),
 'mixGentlyIncubateMin':('complexTime','Complex formation time'),
 'valVol':('mediaVol','Pre-warmed media volume'),
 'replaceFreshVol':('refreshVol','Fresh media volume'),
 'freshMlIncubateMin':('harvestTime','Time to virus harvest'),
 'removeMediaCentrifugeMin':('clearSpinTime','Virus clearing spin time'),
 'storeT':('virusStoreTemp','Virus storage temp'),
 'wellPlateOvernightConc':('transduceCells','Cells per well'),
 'overnightCellsWellVol':('transduceVol','Media per well'),
 'onlyVirusMediaRatio':('virusDilution','Virus:media dilution'),
 'polybreneConc':('polybreneConc','Polybrene concentration'),
 'polybreneMlVol':('polybreneVol','Polybrene volume'),
 'polybreneMlVol2':('polybreneMediaVol','Media Polybrene is added to'),
 'wellIncubateMin':('transduceTime','Transduction time'),
 'selectionAntibioticRange':('selectionStart','Time to start selection'),
}

NAMES['transfection'] = {
 'soTheyReachRange':('seedConfluency','Confluency at transfection'),
 'overnightNbspPct':('co2Pct','CO₂ %'),
 'incubateRange':('complexTime','Complex formation time'),
 'formComplexesRange':('complexTimeRange','Complex time (reagent-dependent)'),
 'incubateNbspNbspPct':('co2PctEndpoint','CO₂ % (endpoint incubation)'),
}

NAMES['revtx'] = {
 'plasmidDnaAmt':('dnaAmt','Plasmid DNA per well'),
 'fugeneHdVol':('fugeneVol','FuGENE HD volume'),
 'optiMemVol':('optiMemVol','Opti-MEM volume'),
 'cellSuspensionVol':('suspensionVol','Cell suspension volume'),
 'suspensionMlContainingRange':('suspensionCells','Cells in suspension'),
 'seedRange':('seedCells','Cells per 12-well'),
 'pipetteIncubateRange':('complexTime','Complex formation time'),
 'wellVol':('overlayVol','Overlay medium volume'),
 'completeMediumContainiRange':('overlayCells','Cells in overlay'),
 'underStandardConditionT':('incubateTemp','Incubation temp'),
 'underStandardConditionPct':('co2Pct','CO₂ %'),
}

NAMES['strap'] = {
 'dttVialAmt':('dttMass','DTT per vial'),
 'dttVialMgVol':('dttWaterVol','Water to dissolve DTT'),
 'dttVialMgConc':('dttStockConc','DTT stock concentration'),
 'volumeConc':('dttFinalConc','DTT final concentration'),
 'incubateT':('reduceTemp','Reduction temp'),
 'incubateRange':('reduceTime','Reduction time'),
 'teabStockConc':('teabWorkConc','TEAB working concentration'),
 'mmTeabConc':('teabStockConc','TEAB stock concentration'),
 'stockVol':('alkylatorTeabVol','TEAB added to alkylator vial'),
 'alkylatorVialConc':('alkylatorStockConc','Alkylator stock concentration'),
 'mmConc':('alkylatorFinalConc','Alkylator final concentration'),
 'incubateMin':('alkylateTime','Alkylation time'),
 'valRatio':('acidRatio','Phosphoric acid ratio'),
 'valPct':('acidPct','Phosphoric acid %'),
 'phosphoricAcidVol':('acidVol','Acid volume'),
 'phosphoricAcidVol2':('acidSampleVol','Sample volume'),
 'bindingWashBufferVol':('bindTeabVol','TEAB in binding buffer'),
 'washBufferTeabConc':('bindTeabStock','TEAB stock for binding buffer'),
 'bufferMlTeabVol':('bindMeohVol','MeOH in binding buffer'),
 'indingwashbuffervolTeaConc':('bindTeabFinal','TEAB final in binding buffer'),
 'meohTeabPct':('bindMeohPct','MeOH % in binding buffer'),
 'valX':('bindBufferX','Binding buffer per sample volume'),
 'trapVol':('trapTubeVol','S-Trap tube size'),
 'centrifugeMin':('loadSpinTime','Loading spin time'),
 'valVol':('washVol','Binding/Wash buffer volume'),
 'washBufferCentrifugeMin':('washSpinTime','Wash spin time'),
 'finalCentrifugeMin':('finalSpinTime','Final spin time'),
 'ratioRatio':('trypsinRatio','Trypsin:protein ratio'),
 'ratioRecommendedAmt':('digestProteinAmt','Protein digested'),
 'ratioRecommendedProteiAmt':('trypsinAmt','Trypsin used'),
 'proteinTrypsinMixAmt':('trypsinVialAmt','Trypsin per vial'),
 'mixTrypsinVol':('trypsinDissolveVol','Volume to dissolve trypsin'),
 'mixTrypsinConc':('trypsinTeabConc','TEAB concentration for trypsin'),
 'mmTeabVol':('trypsinTeabVol','TEAB volume for trypsin'),
 'incubateT2':('digestTemp','Digestion temp'),
 'mmTeabVol2':('elute1Vol','Elution 1 volume (TEAB)'),
 'teabConc':('elute1Conc','Elution 1 TEAB concentration'),
 'mmTeabMin':('elute1SpinTime','Elution 1 spin time'),
 'formicAcidFormVol':('elute2Vol','Elution 2 volume (formic acid)'),
 'formicAcidFormicacidPct':('elute2Pct','Formic acid %'),
 'formicAcidMin':('elute2SpinTime','Elution 2 spin time'),
 'acnVol':('elute3Vol','Elution 3 volume (ACN)'),
 'acnPct':('elute3Pct','ACN %'),
 'acnMin':('elute3SpinTime','Elution 3 spin time'),
 'labelledTubesTakeAmt':('submitAmt','Peptide submitted'),
}

NAMES['miseq'] = {
 'interestOptimalAmplicoN':('ampliconLen','Optimal amplicon length'),
 'templateSetRangeN':('templateLen','Template length for Primer-Blast'),
 'desaltedReconstituteConc':('primerStockConc','Primer stock concentration'),
 'stockWorkingConc':('primerWorkConc','Primer working concentration'),
 'runVol':('gelLoadVol1','Gel load volume (test PCR)'),
 'runPct':('gelPct1','Agarose gel % (test PCR)'),
 'agaroseGelExpectN':('expectedBandLen','Expected band with tags'),
 'expectBpN':('ampliconLenNoTag','Amplicon without tags'),
 'runVol2':('gelLoadVol2','Gel load volume (full PCR)'),
 'runPct2':('gelPct2','Agarose gel % (full PCR)'),
 'rtVortexMin':('beadVortexTime','Bead vortex time'),
 'incubateRtMin':('beadBindTime','Bead binding time'),
 'minMagneticSeparatorMin':('magnetTime','Time on magnet'),
 'valVol':('etohVol','EtOH volume'),
 'freshPct':('etohPct','EtOH %'),
 'freshEtohWashesMin':('etohWashTime','EtOH wash time'),
 'cracksAppearVol':('eluteVol','Elution water volume'),
 'molecularGradeIncubateMin':('eluteTime','Elution incubation'),
 'submitVol':('submitVol','Volume to submit'),
 'submitRange':('submitConc','Concentration to submit'),
}

NAMES['geneseq'] = { 'tataBoxN':('tataDistance','TATA box distance upstream') }
NAMES['alphafold'] = { 'sequenceWaitRange':('predictTime','AF3 prediction time') }

NAMES['trfret'] = {
 'nmAcceptorRatioX':('ratioScale','Ratio scaling factor'),
 'typicallyPct':('dmsoMaxPct','Max DMSO final'),
 'flatUpPct':('dmsoFlatPct','DMSO tolerated (flat signal)'),
 'dropOnlyAbovePct':('dmsoDropPct','DMSO where signal drops'),
 'bufferConc':('hepesConc','HEPES'),
 'mmHepesPhConc':('naclConc','NaCl'),
 'phMmNaclConc':('tcepConc','TCEP'),
 'phNaclTcepPct':('tween20Pct','Tween-20'),
 'naclTcepTweenPct':('bsaPct','BSA'),
 'bdCheckPurityPct':('minPurity','Minimum protein purity'),
 'wallsMaximiseSignalRange':('reactionVol','Reaction volume'),
 'doseResponseTypicallyConc':('doseTop','Dose-response top'),
 'doseResponseTypicallyConc2':('doseBottom','Dose-response bottom'),
 'foldDilutionsPct':('dmsoStockPct','DMSO in compound plate'),
 'assayAchievePct':('dmsoAssayPct','DMSO in assay'),
 'dmsoDiluteRatio':('dmsoDilution','Dilution into assay'),
 'titrateDonorAbRange':('donorAbRange','Donor antibody titration range'),
 'acceptorAbRange':('acceptorAbRange','Acceptor antibody titration range'),
 'tbAntiHisConc':('donorAbConc','Optimal donor antibody'),
 'afAntiGstRange':('acceptorAbConc','Optimal acceptor antibody'),
 'titratePoiRange':('proteinTitrRange','Protein titration range'),
 'protacsGstBrdConc':('poiConc','Optimal POI concentration'),
 'hisCrbnDdbConc':('e3Conc','Optimal E3 concentration'),
 'measureSignalMin':('timeCourseMax','Longest time point'),
 'minTypicallyRange':('incubateTime','Typical incubation time'),
 'valPct':('dmsoTestMax','Top DMSO tested'),
 'stablePct':('dmsoStablePct','DMSO where assay is stable'),
 'prepareAssayBufferConc':('hepesConc2','HEPES (LANCE buffer)'),
 'mmHepesPhConc2':('naclConc2','NaCl (LANCE buffer)'),
 'phMmNaclConc2':('tcepConc2','TCEP (LANCE buffer)'),
 'naclTcepPct':('tween20Pct2','Tween-20 (LANCE buffer)'),
 'valConc':('proteinAConc','Alexa647 Protein A'),
 'valConc2':('proteinBConc','Biotinylated Protein B'),
 'valConc3':('streptavidinConc','LANCE Streptavidin Fluorophore'),
 'wellVol':('wellVol','Final volume per well'),
 'valMin':('lanceIncubateTime','LANCE incubation time'),
}

NAMES['fp'] = {
 'polarizationMpX':('mpScale','mP scaling factor'),
 'poiBrdX':('coopPoiX','POI excess over KD (cooperativity)'),
 'hifPeptideTracerRange':('tracerConc','Tracer concentration'),
 'soCompetitionRange':('tracerKd','Tracer KD'),
 'typicalAssayConcentratRange':('vcbConc','VCB assay concentration'),
 'bufferConc':('hepesConc','HEPES'),
 'mmHepesPhConc':('naclConc','NaCl'),
 'phMmNaclConc':('tcepConc','TCEP'),
 'phNaclTcepPct':('tween20Pct','Tween-20'),
 'minimiseBackgroundFluoRange':('reactionVol','Reaction volume'),
 'pointsFoldTopRange':('doseTop','Top compound concentration'),
 'foldTopMaximumPct':('dmsoMaxPct','Max DMSO final'),
 'mixVcbX':('vcbMixX','VCB mix strength'),
 'famTracerX':('tracerMixX','Tracer mix strength'),
 'bufferPreIncubateMin':('preIncubateTime','Pre-incubation on ice'),
 'valVol':('compoundVol','Compound volume'),
 'wellsVol':('mixVol','Protein-tracer mix volume'),
 'tracerMixTotalVol':('totalVol','Total well volume'),
 'incubateRange':('incubateTime','Incubation time'),
 'proteinX':('directFitX','Protein excess for direct fit'),
 'lenalidomideDerivativeRange':('crbnTracerConc','CRBN tracer concentration'),
 'crbnDdbComplexRange':('crbnConc','CRBN-DDB1 concentration'),
 'lenalidomideRange':('pomalidomideKd','Pomalidomide KD'),
 'lenalidomideRange2':('lenalidomideKd','Lenalidomide KD'),
 'brdBdX':('coopPoiTernaryX','POI excess for ternary FP'),
}

NAMES['spr'] = {
 'protacAloneTypicallyRange':('analyteRange','PROTAC range (× KD)'),
 'ltConc':('mckThreshold','KD below which to use MCK'),
 'saturatingPoiConc':('preformPoiConc','Saturating POI for pre-form'),
 'brdBdConc':('preformProtacConc','PROTAC in pre-form'),
 'bdProtacMin':('preformTime','Pre-incubation time'),
 'pbsCytivaConc':('hepesConc','HEPES'),
 'mmHepesPhConc':('naclConc','NaCl'),
 'hepesPhNaclPct':('tween20Pct','Tween-20'),
 'mmNaclTweenConc':('tcepConc','TCEP'),
 'smallMoleculesRange':('dmsoPct','DMSO for small molecules'),
 'performDmsoCalibrationRange':('dmsoCalRange','DMSO calibration range'),
 'dissociatesSlowlyShortConc':('glycineConc','Glycine for regeneration'),
 'phPulseConc':('naclRegenConc','NaCl for regeneration'),
 'glycinePhPulseMin':('regenPulseTime','Regeneration pulse time'),
 'conditionChipX':('conditionInjections','Chip conditioning injections'),
 'saChipInjectRange':('captureConc','VCB-biotin capture concentration'),
 'vcbBiotinVol':('captureFlow','Capture flow rate'),
 'saSitesX':('blockInjections','Blocking injections'),
 'saSitesMin':('blockTime','Blocking injection time'),
 'runningBufferPct':('runDmsoPct','DMSO in running buffer'),
 'dmsoFinalTypicalConc':('doseBottom','Lowest PROTAC concentration'),
 'concentrationAssociatiRange':('assocTime','Association time'),
 'concentrationAssociatiRange2':('dissocTime','Dissociation time'),
 'dissociationFlowRateRange':('flowRate','Flow rate'),
 'fitRatio':('binaryFitModel','Binding model (binary)'),
 'saturatingPoiConc2':('ternaryPoiConc','Saturating POI (ternary)'),
 'bdTitratedProtacConc':('ternaryDoseBottom','Lowest PROTAC (ternary)'),
 'runningBufferMin':('ternaryPreformTime','Pre-incubation time (ternary)'),
 'withoutRegenerationAssMin':('sckAssocTime','Association per concentration (SCK)'),
 'concentrationFinalDissRange':('sckDissocTime','Final dissociation (SCK)'),
 'fitRatio2':('ternaryFitModel','Binding model (ternary)'),
 'valMin':('mz1Koff','MZ1 koff'),
 'asympMin':('mz1HalfLife','MZ1 ternary complex half-life'),
}
